/* Canvasだけで前処理・矩形候補を作る。写真は送信しない。 */
(function(root){
 'use strict';
 const canvas=(w,h)=>{const c=document.createElement('canvas');c.width=Math.max(1,Math.round(w));c.height=Math.max(1,Math.round(h));return c;};
 function resize(source,max=3600){const scale=Math.min(1,max/Math.max(source.width||source.videoWidth,source.height||source.videoHeight)),c=canvas((source.width||source.videoWidth)*scale,(source.height||source.videoHeight)*scale);c.getContext('2d').drawImage(source,0,0,c.width,c.height);return c;}
 async function load(file){if(file.size>40*1024*1024)throw Error('40MB以下の画像を選んでください。');const url=URL.createObjectURL(file);try{const img=new Image();img.src=url;await img.decode();return resize(img);}catch{throw Error('この画像を開けません。写真アプリからJPEGまたはPNGで保存して選び直してください。');}finally{URL.revokeObjectURL(url);}}
 function rotate(source){const c=canvas(source.height,source.width),x=c.getContext('2d');x.translate(c.width,0);x.rotate(Math.PI/2);x.drawImage(source,0,0);return c;}
 function crop(source,r){const c=canvas(source.width*r.w,source.height*r.h);c.getContext('2d').drawImage(source,source.width*r.x,source.height*r.y,source.width*r.w,source.height*r.h,0,0,c.width,c.height);return c;}
 function region(source,r,{brightness=0,contrast=1.35,binary=false}={}){const raw=crop(source,r),c=canvas(Math.max(650,raw.width*2),Math.max(650,raw.width*2)*raw.height/raw.width),ctx=c.getContext('2d');ctx.drawImage(raw,0,0,c.width,c.height);const im=ctx.getImageData(0,0,c.width,c.height);for(let i=0;i<im.data.length;i+=4){let v=.299*im.data[i]+.587*im.data[i+1]+.114*im.data[i+2];v=Math.max(0,Math.min(255,(v-128)*contrast+128+brightness));v=binary?(v>150?0:255):255-v;im.data[i]=im.data[i+1]=im.data[i+2]=v;}ctx.putImageData(im,0,0);return c;}
 function detectBasic(source){const c=resize(source,900),w=c.width,h=c.height,data=c.getContext('2d').getImageData(0,0,w,h).data,mask=new Uint8Array(w*h),seen=new Uint8Array(w*h),queue=new Int32Array(w*h),boxes=[];
  for(let y=2;y<h-2;y++)for(let x=2;x<w-2;x++){const i=y*w+x,p=i*4;if(.299*data[p]+.587*data[p+1]+.114*data[p+2]<100){for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++)mask[i+dy*w+dx]=1;}}
  for(let i=0;i<mask.length;i++){if(!mask[i]||seen[i])continue;let head=0,tail=1,minX=w,maxX=0,minY=h,maxY=0;queue[0]=i;seen[i]=1;while(head<tail){const k=queue[head++],x=k%w,y=Math.floor(k/w);minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y);for(const n of [x>0?k-1:-1,x<w-1?k+1:-1,y>0?k-w:-1,y<h-1?k+w:-1])if(n>=0&&mask[n]&&!seen[n]){seen[n]=1;queue[tail++]=n;}}const bw=maxX-minX+1,bh=maxY-minY+1,area=bw*bh,ratio=bw/bh;if(area>w*h*.007&&area<w*h*.94&&tail/area>.23&&((ratio>.39&&ratio<.91)||(ratio>1.1&&ratio<2.5))){boxes.push({x:Math.max(0,(minX-2)/w),y:Math.max(0,(minY-2)/h),w:Math.min(w-minX,bw+4)/w,h:Math.min(h-minY,bh+4)/h});}}
  const biggest=boxes.sort((a,b)=>b.w*b.h-a.w*a.h).filter((b,i,list)=>!list.slice(0,i).some(a=>b.x>=a.x&&b.y>=a.y&&b.x+b.w<=a.x+a.w&&b.y+b.h<=a.y+a.h)).slice(0,15);
  return biggest.sort((a,b)=>Math.abs(a.y-b.y)<Math.min(a.h,b.h)*.4?a.x-b.x:a.y-b.y);
 }

 let visionWorker=null,visionId=0;const jobs=new Map();
 function visionJob(kind,source,rect){if(!visionWorker){visionWorker=new Worker('camera-vision-worker.js');visionWorker.onmessage=({data:m})=>{const j=jobs.get(m.id);if(j){clearTimeout(j.timer);jobs.delete(m.id);m.error?j.reject(Error(m.error)):j.resolve(m.result);}};visionWorker.onerror=()=>stopVision();}const image=source.getContext('2d').getImageData(0,0,source.width,source.height);return new Promise((resolve,reject)=>{const id=++visionId,timer=setTimeout(()=>stopVision(),30000);jobs.set(id,{resolve,reject,timer});visionWorker.postMessage({id,kind,image,rect},[image.data.buffer]);});}
 function stopVision(){visionWorker?.terminate();visionWorker=null;for(const j of jobs.values()){clearTimeout(j.timer);j.reject(Error('枠の自動検出を中断しました。枠を手動で追加できます。'));}jobs.clear();}
 async function detect(source){const found=await visionJob('detect',resize(source,1200));const extras=detectBasic(source).flatMap(b=>{const ratio=b.w*source.width/(b.h*source.height),n=ratio>1.0?Math.round(ratio/.66):1;return Array.from({length:n},(_,i)=>({...b,x:b.x+b.w*i/n,w:b.w/n}));});for(const b of extras){if(!found.some(a=>{const inter=Math.max(0,Math.min(a.x+a.w,b.x+b.w)-Math.max(a.x,b.x))*Math.max(0,Math.min(a.y+a.h,b.y+b.h)-Math.max(a.y,b.y));return inter/Math.min(a.w*a.h,b.w*b.h)>.55;}))found.push(b);}return found.slice(0,15).sort((a,b)=>Math.abs(a.y-b.y)<Math.min(a.h,b.h)*.4?a.x-b.x:a.y-b.y);}
 async function straighten(source,r){if(!r.points)return crop(source,r);const cut=crop(source,r),adjusted={...r,points:r.points.map(p=>({x:(p.x-r.x)/r.w,y:(p.y-r.y)/r.h}))},result=await visionJob('straighten',cut,adjusted),c=canvas(result.width,result.height);c.getContext('2d').putImageData(new ImageData(result.data,result.width,result.height),0,0);return c;}
 let worker=null,loading=null,ocrGeneration=0;
 async function engine(progress=()=>{}){if(worker)return worker;const ticket=ocrGeneration;if(!loading)loading=(async()=>{if(!root.Tesseract)await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='vendor/ocr/tesseract.min.js';s.onload=resolve;s.onerror=()=>reject(Error('OCR本体を読み込めません。通信を確認して再試行してください。'));document.head.append(s);});const base=new URL('vendor/ocr/',document.baseURI).href;const created=await Tesseract.createWorker('jpn+eng',1,{workerPath:base+'worker.min.js',corePath:base,langPath:base,gzip:false,workerBlobURL:false,logger:m=>progress(m.status)});if(ticket!==ocrGeneration){await created.terminate();throw Error('認識を中断しました');}worker=created;await worker.setParameters({tessedit_pageseg_mode:'6',preserve_interword_spaces:'1'});return worker;})().catch(e=>{if(ticket===ocrGeneration)loading=null;throw e;});return loading;}
 async function recognize(source,settings={},progress=()=>{}){const w=await engine(progress),names=[];await w.reinitialize('jpn');await w.setParameters({tessedit_pageseg_mode:'6',tessedit_char_whitelist:''});const nameArea={x:.24,y:.04,w:.54,h:.15};for(const binary of [false,true]){const {data}=await w.recognize(region(source,nameArea,{...settings,binary}));names.push(data.text.trim());}
  await w.reinitialize('eng');await w.setParameters({tessedit_pageseg_mode:'7',tessedit_char_whitelist:'SUR'});const rarity=(await w.recognize(region(source,{x:.02,y:.045,w:.20,h:.085},settings))).data.text.trim();await w.setParameters({tessedit_char_whitelist:'SUR0123456789/'});let number='';let candidates=CameraMatch.rank({names,rarity});if(!CameraMatch.high(candidates)){number=(await w.recognize(region(source,{x:.68,y:.935,w:.31,h:.06},settings))).data.text.trim();candidates=CameraMatch.rank({names,rarity,number});}return {names,rarity,number,candidates,high:CameraMatch.high(candidates)};
 }
 async function stop(){stopVision();ocrGeneration++;loading=null;if(worker){const old=worker;worker=null;loading=null;await old.terminate();}}
 root.CameraImage={canvas,resize,load,rotate,crop,region,detect,detectBasic,straighten,recognize,stop};
})(globalThis);
