// Excel原文から自動生成。直接編集しないでください。
globalThis.CARD_SOURCE = {
  "file": "英雄列伝バトル_108枚統合管理表.xlsx",
  "sha256": "8db963b77d0a60fd9be8922ec4f94c558a6793a7d402abd421333b5d0f5feaee",
  "sheet": "108枚統合管理表",
  "headerRow": 5,
  "count": 108,
  "rarities": {
    "UR": 9,
    "SSR": 27,
    "SR": 27,
    "R": 45
  },
  "columns": [
    "番号",
    "人物",
    "レアリティ",
    "タイプ・得意分野",
    "能力の方向性",
    "コスト",
    "攻撃力",
    "防御力",
    "兵力",
    "スキル名",
    "スキル内容",
    "特性名",
    "特性内容",
    "二つ名",
    "決め台詞（創作）",
    "画像制作状況",
    "設定状況",
    "備考"
  ]
};
globalThis.CARD_DATA = [
  {
    "id": "UR01",
    "name": "ゼウス",
    "rarity": "UR",
    "type": "雷撃・全能",
    "direction": "敵全体への大ダメージ＋行動妨害",
    "cost": 10,
    "attack": 10,
    "defense": 9,
    "troop": 9,
    "skillName": "神罰の雷霆",
    "skillText": "登場時、敵全体に３ダメージを与える。敵１体を次の相手ターン終了まで攻撃不能にする。",
    "traitName": "神王",
    "traitText": "自分のターン開始時、カードを１枚引く。そのターン、このカードの攻撃力＋１。",
    "title": "全知全能の天空神",
    "quote": "天雷よ轟け、神々の王が世界を裁く！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 6
  },
  {
    "id": "UR02",
    "name": "オーディン",
    "rarity": "UR",
    "type": "戦神・統率",
    "direction": "単体大ダメージ＋味方全体強化",
    "cost": 10,
    "attack": 10,
    "defense": 8,
    "troop": 11,
    "skillName": "神槍グングニル",
    "skillText": "登場時、敵１体に５ダメージを与える。そのターン、味方全体の攻撃力＋２。",
    "traitName": "大神の統率",
    "traitText": "自分の場に他の味方がいる間、このカードの防御力＋２。",
    "title": "戦場を見渡す叡智の大神",
    "quote": "叡智の槍よ、勝利への道を開け！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 7
  },
  {
    "id": "UR03",
    "name": "天照大神",
    "rarity": "UR",
    "type": "太陽・支援",
    "direction": "味方全体の兵力強化＋ライフ回復",
    "cost": 10,
    "attack": 7,
    "defense": 9,
    "troop": 11,
    "skillName": "天照の祝福",
    "skillText": "登場時、味方全体の兵力上限と現在兵力を２増やす。自分のライフを４回復する（上限まで）。",
    "traitName": "太陽の加護",
    "traitText": "自分のターン開始時、このカードの兵力を１回復する（上限まで）。",
    "title": "天地を照らす太陽の女神",
    "quote": "天の光よ、すべての命を照らせ！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 8
  },
  {
    "id": "UR04",
    "name": "ルーナ",
    "rarity": "UR",
    "type": "月・回復",
    "direction": "味方全体回復＋防御力強化",
    "cost": 9,
    "attack": 6,
    "defense": 9,
    "troop": 10,
    "skillName": "月光の癒やし",
    "skillText": "登場時、味方全体の兵力を４回復する（上限まで）。そのターン、味方全体の防御力＋２。",
    "traitName": "静夜の守り",
    "traitText": "自分の場に他の味方がいる間、このカードの防御力＋１。",
    "title": "月光で命を包む癒やしの女神",
    "quote": "月の光よ、傷ついた仲間を包め！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 9
  },
  {
    "id": "UR05",
    "name": "ガネーシャ",
    "rarity": "UR",
    "type": "福徳・守護",
    "direction": "回復＋ドロー＋防御支援",
    "cost": 9,
    "attack": 7,
    "defense": 9,
    "troop": 11,
    "skillName": "福徳の祝福",
    "skillText": "登場時、味方１体の兵力を４回復する（上限まで）。さらにカードを２枚引く。",
    "traitName": "障害を除く守り",
    "traitText": "このカードが場にいる間、他の味方全体の防御力＋１。",
    "title": "福徳と知恵で道を開く守護神",
    "quote": "幸いの光で、仲間の道を開こう！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 10
  },
  {
    "id": "UR06",
    "name": "スサノオ",
    "rarity": "UR",
    "type": "武勇・暴風",
    "direction": "高火力攻撃＋敵能力の一時無効",
    "cost": 10,
    "attack": 11,
    "defense": 7,
    "troop": 10,
    "skillName": "暴風の神剣",
    "skillText": "登場時、敵１体に５ダメージを与える。その敵のスキルと特性を次の自分のターンまで無効にする。",
    "traitName": "荒魂の武勇",
    "traitText": "登場したターン、このカードの攻撃力＋２。",
    "title": "荒ぶる嵐を従える武勇の神",
    "quote": "嵐を起こせ、我が剣で道を拓く！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 11
  },
  {
    "id": "UR07",
    "name": "ラー",
    "rarity": "UR",
    "type": "太陽・制圧",
    "direction": "敵全体ダメージ＋防御力低下",
    "cost": 10,
    "attack": 9,
    "defense": 8,
    "troop": 11,
    "skillName": "太陽神の灼光",
    "skillText": "登場時、敵全体に３ダメージを与える。そのターン、敵全体の防御力－２。",
    "traitName": "太陽の威光",
    "traitText": "このカードの兵力が上限の間、攻撃力＋２。",
    "title": "天を巡り世界を照らす太陽神",
    "quote": "太陽の輝きよ、戦場を照らせ！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 12
  },
  {
    "id": "UR08",
    "name": "アテナ",
    "rarity": "UR",
    "type": "戦略・守護",
    "direction": "攻防両立＋味方全体の防御強化",
    "cost": 10,
    "attack": 9,
    "defense": 10,
    "troop": 10,
    "skillName": "戦女神の一閃",
    "skillText": "登場時、敵１体に４ダメージを与える。",
    "traitName": "アイギスの守護",
    "traitText": "このカードが場にいる間、味方全体の防御力＋２。",
    "title": "知恵と盾で勝利を導く戦女神",
    "quote": "知恵を刃に、守りを勝利へ！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 13
  },
  {
    "id": "UR09",
    "name": "アポロン",
    "rarity": "UR",
    "type": "光・音律",
    "direction": "全体攻撃＋ドロー＋味方攻撃強化",
    "cost": 10,
    "attack": 9,
    "defense": 8,
    "troop": 10,
    "skillName": "光明の旋律",
    "skillText": "登場時、敵全体に２ダメージを与え、カードを１枚引く。そのターン、味方全体の攻撃力＋１。",
    "traitName": "調和の音律",
    "traitText": "自分の手札が４枚以上ある間、このカードの攻撃力＋１。",
    "title": "光と音律で希望を奏でる神",
    "quote": "光の調べよ、勝利の歌となれ！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 14
  },
  {
    "id": "SSR01",
    "name": "織田信長",
    "rarity": "SSR",
    "type": "攻撃・革新",
    "direction": "高火力＋敵手札妨害",
    "cost": 7,
    "attack": 8,
    "defense": 5,
    "troop": 9,
    "skillName": "天下布武",
    "skillText": "登場時、敵１体に３ダメージを与え、相手は手札を１枚選んで捨てる。",
    "traitName": "革新の炎",
    "traitText": "登場したターン、このカードの攻撃力＋２。",
    "title": "革新の炎で天下を切り拓く覇王",
    "quote": "古き壁を破り、天下へ進め！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 15
  },
  {
    "id": "SSR02",
    "name": "豊臣秀吉",
    "rarity": "SSR",
    "type": "支援・統率",
    "direction": "味方全体強化＋ドロー",
    "cost": 7,
    "attack": 5,
    "defense": 6,
    "troop": 9,
    "skillName": "天下人の采配",
    "skillText": "登場時、カードを１枚引く。そのターン、味方全体の攻撃力＋２。",
    "traitName": "結束の力",
    "traitText": "他の味方が２体以上いる間、このカードの防御力＋２。",
    "title": "人の力を束ねて天下をつかむ将",
    "quote": "皆の力で、勝利の城を築こう！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 16
  },
  {
    "id": "SSR03",
    "name": "徳川家康",
    "rarity": "SSR",
    "type": "防御・持久",
    "direction": "ライフ回復＋高防御",
    "cost": 7,
    "attack": 5,
    "defense": 8,
    "troop": 10,
    "skillName": "泰平への礎",
    "skillText": "登場時、自分のライフを３回復する（上限まで）。",
    "traitName": "不動の守り",
    "traitText": "自分の場に他の味方がいる間、このカードの防御力＋２。",
    "title": "忍耐と守りで泰平を築く将",
    "quote": "耐え抜いた先に、泰平は開ける！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 17
  },
  {
    "id": "SSR04",
    "name": "真田幸村",
    "rarity": "SSR",
    "type": "突撃・逆境",
    "direction": "劣勢になるほど攻撃力上昇",
    "cost": 7,
    "attack": 7,
    "defense": 5,
    "troop": 9,
    "skillName": "六文銭の突撃",
    "skillText": "このカードの減った兵力２につき、攻撃力＋１（最大＋４）。",
    "traitName": "不屈の闘志",
    "traitText": "自分のライフが相手より少ない間、このカードの攻撃力＋２。",
    "title": "逆境を貫く日本一の兵",
    "quote": "逆境こそ、我が槍の見せ場よ！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 18
  },
  {
    "id": "SSR05",
    "name": "源義経",
    "rarity": "SSR",
    "type": "神速・奇襲",
    "direction": "敵防御低下＋先制攻撃",
    "cost": 7,
    "attack": 7,
    "defense": 5,
    "troop": 8,
    "skillName": "神速の奇襲",
    "skillText": "登場したターン、敵１体の防御力－２。最初の戦闘では相手より先に攻撃する。",
    "traitName": "軽やかな身のこなし",
    "traitText": "自分の場に他の味方がいる間、このカードの防御力＋１。",
    "title": "風より速く戦場を駆ける若武者",
    "quote": "風を越え、一瞬の勝機をつかめ！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 19
  },
  {
    "id": "SSR06",
    "name": "武田信玄",
    "rarity": "SSR",
    "type": "軍略・攻撃",
    "direction": "自己強化＋攻撃継続",
    "cost": 8,
    "attack": 7,
    "defense": 7,
    "troop": 10,
    "skillName": "風林火山",
    "skillText": "登場したターン、攻撃力＋２。敵を撃破した時、一度だけ再び攻撃できる。",
    "traitName": "揺るがぬ軍略",
    "traitText": "自分の場に他の味方がいる間、このカードの防御力＋１。",
    "title": "風林火山の采配を振るう猛将",
    "quote": "動く時は、烈火のごとく！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 20
  },
  {
    "id": "SSR07",
    "name": "上杉謙信",
    "rarity": "SSR",
    "type": "武勇・守護",
    "direction": "攻撃＋防御のバランス型",
    "cost": 7,
    "attack": 7,
    "defense": 7,
    "troop": 9,
    "skillName": "義の一閃",
    "skillText": "登場時、敵１体に３ダメージを与える。そのターン、このカードの防御力＋２。",
    "traitName": "守護の武勇",
    "traitText": "自分の場に他の味方がいる間、このカードの攻撃力＋１。",
    "title": "義の刃で仲間を守る軍神",
    "quote": "義を胸に、攻めて守り抜く！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 21
  },
  {
    "id": "SSR08",
    "name": "坂本龍馬",
    "rarity": "SSR",
    "type": "維新・特殊",
    "direction": "ドロー＋コスト軽減",
    "cost": 6,
    "attack": 5,
    "defense": 5,
    "troop": 8,
    "skillName": "維新への航路",
    "skillText": "登場時、カードを２枚引く。このターン、次に出すカードのコスト－１。",
    "traitName": "自由な発想",
    "traitText": "自分の手札が４枚以上ある間、このカードの防御力＋１。",
    "title": "新しい時代への航路を開く志士",
    "quote": "新しい時代へ、共に船を出そう！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 22
  },
  {
    "id": "SSR09",
    "name": "卑弥呼",
    "rarity": "SSR",
    "type": "巫女・策略",
    "direction": "敵妨害＋手札補充",
    "cost": 7,
    "attack": 4,
    "defense": 6,
    "troop": 9,
    "skillName": "神託の導き",
    "skillText": "登場時、敵１体を次の相手ターン終了まで攻撃不能にし、カードを１枚引く。",
    "traitName": "祈りの守り",
    "traitText": "自分の手札が４枚以上ある間、このカードの防御力＋２。",
    "title": "神託で運命を導く倭の女王",
    "quote": "神託の光よ、進む道を示せ！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 23
  },
  {
    "id": "SSR10",
    "name": "ジャンヌ・ダルク",
    "rarity": "SSR",
    "type": "聖女・支援",
    "direction": "味方全体回復＋劣勢時強化",
    "cost": 7,
    "attack": 5,
    "defense": 7,
    "troop": 9,
    "skillName": "聖なる祈り",
    "skillText": "登場時、味方全体の兵力を３回復する（上限まで）。",
    "traitName": "希望の旗",
    "traitText": "味方の数が敵より少ない間、味方全体の攻撃力＋１。",
    "title": "希望の旗で仲間を導く聖女",
    "quote": "希望の旗のもと、共に立ち上がろう！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 24
  },
  {
    "id": "SSR11",
    "name": "ナポレオン",
    "rarity": "SSR",
    "type": "指揮・進軍",
    "direction": "ドロー＋エネルギー増加",
    "cost": 7,
    "attack": 6,
    "defense": 6,
    "troop": 9,
    "skillName": "皇帝の進軍",
    "skillText": "登場時、カードを２枚引き、自分のエネルギーを１増やす。",
    "traitName": "勝利への指揮",
    "traitText": "他の味方が２体以上いる間、このカードの攻撃力＋１。",
    "title": "大胆な指揮で勝利へ進む皇帝",
    "quote": "勝機を見定め、前へ進め！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 25
  },
  {
    "id": "SSR12",
    "name": "アレクサンドロス大王",
    "rarity": "SSR",
    "type": "征服・攻撃",
    "direction": "敵撃破で連続強化",
    "cost": 8,
    "attack": 8,
    "defense": 6,
    "troop": 10,
    "skillName": "征服王の進撃",
    "skillText": "このカードが敵を撃破するたび、攻撃力＋１（最大＋３）。",
    "traitName": "勝利の勢い",
    "traitText": "敵を撃破した時、このカードの兵力を２回復する（上限まで）。",
    "title": "果てなき世界へ進む征服王",
    "quote": "まだ見ぬ世界へ、勝利を重ねよ！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 26
  },
  {
    "id": "SSR13",
    "name": "ジュリアス・シーザー",
    "rarity": "SSR",
    "type": "軍略・統率",
    "direction": "敵弱体化＋カード補充",
    "cost": 7,
    "attack": 6,
    "defense": 6,
    "troop": 9,
    "skillName": "勝利への布石",
    "skillText": "登場したターン、敵全体の攻撃力－１。さらにカードを１枚引く。",
    "traitName": "揺るがぬ統率",
    "traitText": "他の味方が２体以上いる間、このカードの防御力＋１。",
    "title": "知略と決断で歴史を動かす将",
    "quote": "決断の時だ、勝利への道を開け！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 27
  },
  {
    "id": "SSR14",
    "name": "ハンニバル",
    "rarity": "SSR",
    "type": "奇襲・軍略",
    "direction": "敵防御低下＋後攻時強化",
    "cost": 7,
    "attack": 7,
    "defense": 5,
    "troop": 9,
    "skillName": "アルプスの奇襲",
    "skillText": "登場したターン、敵全体の防御力－２。",
    "traitName": "逆転の軍略",
    "traitText": "この対戦で自分が後攻なら、このカードの攻撃力＋２。",
    "title": "意表を突く策で大軍を破る将",
    "quote": "険しき道にこそ、勝機はある！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 28
  },
  {
    "id": "SSR15",
    "name": "チンギス・ハン",
    "rarity": "SSR",
    "type": "騎兵・制圧",
    "direction": "敵全体攻撃＋最大兵力時強化",
    "cost": 8,
    "attack": 7,
    "defense": 6,
    "troop": 10,
    "skillName": "蒼き狼の進撃",
    "skillText": "登場時、敵全体に２ダメージを与える。",
    "traitName": "万全の進軍",
    "traitText": "このカードの兵力が上限の間、攻撃力＋２。",
    "title": "大草原を駆けて世界を揺るがす王",
    "quote": "草原の風と共に、道を切り拓け！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 29
  },
  {
    "id": "SSR16",
    "name": "レオニダス",
    "rarity": "SSR",
    "type": "防御・反撃",
    "direction": "高防御＋劣勢時に耐久上昇",
    "cost": 7,
    "attack": 6,
    "defense": 8,
    "troop": 10,
    "skillName": "不退の守り",
    "skillText": "味方の数が敵より少ない間、このカードの防御力＋２。",
    "traitName": "鋼の忍耐",
    "traitText": "受けるダメージを１減らす（最小０）。",
    "title": "不退の盾で道を守り抜く王",
    "quote": "この盾と共に、最後まで守り抜く！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 30
  },
  {
    "id": "SSR17",
    "name": "リチャード獅子心王",
    "rarity": "SSR",
    "type": "武勇・突撃",
    "direction": "単体大ダメージ＋逆境強化",
    "cost": 8,
    "attack": 8,
    "defense": 6,
    "troop": 9,
    "skillName": "獅子王の一撃",
    "skillText": "登場時、敵１体に４ダメージを与える。",
    "traitName": "獅子の闘志",
    "traitText": "自分のライフが相手より少ない間、このカードの攻撃力＋２。",
    "title": "獅子の勇気で逆境を打ち砕く王",
    "quote": "獅子の心で、逆境を越えよ！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 31
  },
  {
    "id": "SSR18",
    "name": "始皇帝",
    "rarity": "SSR",
    "type": "統治・制圧",
    "direction": "敵全体弱体化＋自己回復",
    "cost": 8,
    "attack": 6,
    "defense": 7,
    "troop": 10,
    "skillName": "天下統一",
    "skillText": "登場したターン、敵全体の攻撃力－２。このカードの兵力を３回復する（上限まで）。",
    "traitName": "皇帝の威厳",
    "traitText": "自分の手札が４枚以上ある間、このカードの防御力＋１。",
    "title": "天下を統べて新たな秩序を築く帝",
    "quote": "天下を束ね、揺るがぬ国を築く！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 32
  },
  {
    "id": "SSR19",
    "name": "空海",
    "rarity": "SSR",
    "type": "祈り・回復",
    "direction": "味方回復＋状態異常解除",
    "cost": 7,
    "attack": 4,
    "defense": 7,
    "troop": 9,
    "skillName": "大師の祈り",
    "skillText": "登場時、味方１体の兵力を４回復し、その味方の状態異常をすべて解除する。",
    "traitName": "慈悲の心",
    "traitText": "自分の場に他の味方がいる間、このカードの防御力＋１。",
    "title": "祈りの光で仲間を救う大師",
    "quote": "祈りの光よ、仲間を照らせ！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 33
  },
  {
    "id": "SSR20",
    "name": "聖徳太子",
    "rarity": "SSR",
    "type": "統率・政治",
    "direction": "複数の味方カードを同時強化",
    "cost": 7,
    "attack": 5,
    "defense": 7,
    "troop": 9,
    "skillName": "和の采配",
    "skillText": "登場したターン、味方を最大３体選び、攻撃力と防御力を＋１する。",
    "traitName": "協調の力",
    "traitText": "他の味方が２体以上いる間、このカードの防御力＋１。",
    "title": "和の心で人々を束ねる賢者",
    "quote": "心を合わせ、共に道を築こう！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 34
  },
  {
    "id": "SSR21",
    "name": "孔子",
    "rarity": "SSR",
    "type": "教育・支援",
    "direction": "味方の能力強化＋手札補充",
    "cost": 7,
    "attack": 4,
    "defense": 6,
    "troop": 9,
    "skillName": "学びの導き",
    "skillText": "登場時、カードを１枚引く。そのターン、味方１体の攻撃力と防御力＋２。",
    "traitName": "仁の教え",
    "traitText": "他の味方が２体以上いる間、このカードの防御力＋１。",
    "title": "学びの道で仲間を育てる師",
    "quote": "学びを重ね、共に成長しよう！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 35
  },
  {
    "id": "SSR22",
    "name": "諸葛孔明",
    "rarity": "SSR",
    "type": "軍略・策略",
    "direction": "山札操作＋敵行動妨害",
    "cost": 7,
    "attack": 5,
    "defense": 6,
    "troop": 9,
    "skillName": "神算の布陣",
    "skillText": "登場時、山札の上３枚を見て好きな順に戻す。敵１体を次の相手ターン終了まで攻撃不能にする。",
    "traitName": "軍師の備え",
    "traitText": "自分の手札が４枚以上ある間、このカードの防御力＋１。",
    "title": "先を読む知略で戦局を導く軍師",
    "quote": "先を読み、勝利への道を描こう！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 36
  },
  {
    "id": "SSR23",
    "name": "レオナルド・ダ・ヴィンチ",
    "rarity": "SSR",
    "type": "発明・万能",
    "direction": "状況に応じて能力を選択",
    "cost": 7,
    "attack": 5,
    "defense": 6,
    "troop": 9,
    "skillName": "万能の発想",
    "skillText": "登場時、１つ選ぶ。２枚引く／味方１体の兵力を３回復する／このターン、味方１体の攻撃力＋３。",
    "traitName": "探究の積み重ね",
    "traitText": "自分の手札が４枚以上ある間、このカードの防御力＋１。",
    "title": "発想と技で可能性を広げる万能人",
    "quote": "ひらめきから、新たな道を創ろう！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 37
  },
  {
    "id": "SSR24",
    "name": "ニュートン",
    "rarity": "SSR",
    "type": "科学・知略",
    "direction": "敵能力低下＋高効率ドロー",
    "cost": 7,
    "attack": 4,
    "defense": 6,
    "troop": 9,
    "skillName": "万有引力",
    "skillText": "登場したターン、敵１体の攻撃力－３。さらにカードを２枚引く。",
    "traitName": "法則の洞察",
    "traitText": "自分の手札が５枚以上ある間、このカードの防御力＋２。",
    "title": "自然の法則を見いだす探究者",
    "quote": "自然の中に、答えを見つけよう！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 38
  },
  {
    "id": "SSR25",
    "name": "アインシュタイン",
    "rarity": "SSR",
    "type": "科学・特殊",
    "direction": "コスト操作＋ターン展開補助",
    "cost": 7,
    "attack": 4,
    "defense": 6,
    "troop": 9,
    "skillName": "時空の発想",
    "skillText": "登場時、エネルギーを１増やす。このターン、次に出すカードのコスト－２。",
    "traitName": "柔軟な思考",
    "traitText": "自分の手札が４枚以上ある間、このカードの防御力＋１。",
    "title": "自由な思考で常識を越える科学者",
    "quote": "想像を広げ、新しい一手へ！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 39
  },
  {
    "id": "SSR26",
    "name": "ガリレオ・ガリレイ",
    "rarity": "SSR",
    "type": "観測・知略",
    "direction": "山札確認＋必要カードを選択",
    "cost": 6,
    "attack": 4,
    "defense": 6,
    "troop": 8,
    "skillName": "星空の観測",
    "skillText": "登場時、山札の上４枚を見て１枚を手札に加える。残りを好きな順で山札の下に戻す。",
    "traitName": "観測の積み重ね",
    "traitText": "自分の手札が４枚以上ある間、このカードの防御力＋１。",
    "title": "星の観測で真理へ近づく賢者",
    "quote": "星を見つめ、確かな一手を選ぼう！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 40
  },
  {
    "id": "SSR27",
    "name": "ソクラテス",
    "rarity": "SSR",
    "type": "哲学・精神",
    "direction": "敵スキル妨害＋味方防御強化",
    "cost": 7,
    "attack": 4,
    "defense": 7,
    "troop": 9,
    "skillName": "哲人の問答",
    "skillText": "登場時、敵１体のスキルを次の自分のターンまで無効にする。そのターン、味方全体の防御力＋１。",
    "traitName": "揺るがぬ精神",
    "traitText": "自分の場に他の味方がいる間、このカードの防御力＋１。",
    "title": "問いかけで知恵を照らす哲人",
    "quote": "問いを重ね、真の強さを見つけよう！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 41
  },
  {
    "id": "SR01",
    "name": "伊達政宗",
    "rarity": "SR",
    "type": "攻撃・奇襲",
    "direction": "登場ターンの攻撃強化",
    "cost": 5,
    "attack": 6,
    "defense": 4,
    "troop": 7,
    "skillName": "独眼竜の奇襲",
    "skillText": "登場したターン、このカードの攻撃力＋３。",
    "traitName": "攻めの采配",
    "traitText": "自分の場に他の味方がいる間、このカードの防御力＋１。",
    "title": "隻眼に野望を宿す独眼竜",
    "quote": "機を逃すな、竜のごとく駆けよ！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 42
  },
  {
    "id": "SR02",
    "name": "明智光秀",
    "rarity": "SR",
    "type": "策略",
    "direction": "相手の能力を一時無効",
    "cost": 5,
    "attack": 4,
    "defense": 5,
    "troop": 7,
    "skillName": "静謐の策略",
    "skillText": "登場時、敵１体のスキルと特性を次の自分のターン開始まで無効にする。",
    "traitName": "冷静な判断",
    "traitText": "自分の手札が３枚以上ある間、このカードの防御力＋１。",
    "title": "静かな知略で戦局を覆す将",
    "quote": "勝機は、静かな一手に宿る！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 43
  },
  {
    "id": "SR03",
    "name": "石田三成",
    "rarity": "SR",
    "type": "統率",
    "direction": "味方が多いほど強化",
    "cost": 5,
    "attack": 4,
    "defense": 5,
    "troop": 8,
    "skillName": "結束の采配",
    "skillText": "自分の場の他の味方１体につき、このカードの攻撃力＋１（最大＋３）。",
    "traitName": "義の結束",
    "traitText": "他の味方が２体以上いる間、このカードの防御力＋１。",
    "title": "義と采配で仲間を束ねる将",
    "quote": "志を合わせ、勝利をつかめ！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 44
  },
  {
    "id": "SR04",
    "name": "本多忠勝",
    "rarity": "SR",
    "type": "防御・武勇",
    "direction": "高防御＋一度だけ耐える",
    "cost": 6,
    "attack": 5,
    "defense": 8,
    "troop": 8,
    "skillName": "不屈の武勇",
    "skillText": "兵力が０になる時、一度だけ兵力１で場に残る。",
    "traitName": "堅牢な守り",
    "traitText": "自分の場に他の味方がいる間、このカードの防御力＋１。",
    "title": "揺るがぬ武勇の守護神",
    "quote": "この槍がある限り、退かぬ！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 45
  },
  {
    "id": "SR05",
    "name": "宮本武蔵",
    "rarity": "SR",
    "type": "一騎討ち",
    "direction": "敵1体への大ダメージ",
    "cost": 6,
    "attack": 7,
    "defense": 4,
    "troop": 7,
    "skillName": "二天一流",
    "skillText": "登場時、敵１体に４ダメージを与える。",
    "traitName": "一騎討ちの心得",
    "traitText": "相手の場に敵が１体だけなら、このカードの攻撃力＋２。",
    "title": "二天の剣で道を切り拓く剣豪",
    "quote": "二つの刃で、勝機を開く！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 46
  },
  {
    "id": "SR06",
    "name": "平清盛",
    "rarity": "SR",
    "type": "経済",
    "direction": "エネルギー獲得",
    "cost": 5,
    "attack": 4,
    "defense": 5,
    "troop": 7,
    "skillName": "日宋貿易",
    "skillText": "登場時、自分のエネルギーを２増やす。",
    "traitName": "交易の繁栄",
    "traitText": "自分の手札が４枚以上ある間、このカードの防御力＋１。",
    "title": "海の交易で栄華を築く棟梁",
    "quote": "海を開き、新たな力を得よ！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 47
  },
  {
    "id": "SR07",
    "name": "北条政子",
    "rarity": "SR",
    "type": "支援",
    "direction": "味方全体を強化",
    "cost": 5,
    "attack": 3,
    "defense": 6,
    "troop": 8,
    "skillName": "尼御台の号令",
    "skillText": "登場したターン、味方全体の攻撃力と防御力を＋１する。",
    "traitName": "支えの言葉",
    "traitText": "登場時、味方１体の兵力を２回復する（上限まで）。",
    "title": "揺るがぬ意志で仲間を導く尼御台",
    "quote": "心を一つに、共に立ち上がれ！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 48
  },
  {
    "id": "SR08",
    "name": "西郷隆盛",
    "rarity": "SR",
    "type": "統率",
    "direction": "劣勢時に味方を強化",
    "cost": 5,
    "attack": 5,
    "defense": 5,
    "troop": 8,
    "skillName": "不屈の号令",
    "skillText": "登場時、味方の数が敵より少ないなら、そのターン、味方全体の攻撃力＋２。",
    "traitName": "仲間への信頼",
    "traitText": "自分の場に他の味方がいる間、このカードの防御力＋１。",
    "title": "大きな志で仲間を奮い立たせる将",
    "quote": "苦しい時こそ、共に踏ん張ろう！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 49
  },
  {
    "id": "SR09",
    "name": "紫式部",
    "rarity": "SR",
    "type": "知略",
    "direction": "手札補充・カード選択",
    "cost": 5,
    "attack": 3,
    "defense": 5,
    "troop": 7,
    "skillName": "物語の選択",
    "skillText": "登場時、カードを３枚引き、その後、手札を１枚捨てる。",
    "traitName": "深い洞察",
    "traitText": "自分の手札が５枚以上ある間、このカードの防御力＋２。",
    "title": "言の葉で未来を紡ぐ才女",
    "quote": "言の葉に、次の一手を見いだそう！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 50
  },
  {
    "id": "SR10",
    "name": "クレオパトラ",
    "rarity": "SR",
    "type": "魅了・策略",
    "direction": "敵の攻撃力低下",
    "cost": 5,
    "attack": 4,
    "defense": 5,
    "troop": 8,
    "skillName": "女王の魅惑",
    "skillText": "登場時、敵１体の攻撃力を２下げる。効果は次の自分のターン開始時まで。",
    "traitName": "王家の策略",
    "traitText": "攻撃力が下がっている敵との戦闘中、このカードの防御力＋１。",
    "title": "ナイルの麗しき女王",
    "quote": "微笑みひとつで、運命を変える！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 51
  },
  {
    "id": "SR11",
    "name": "スパルタクス",
    "rarity": "SR",
    "type": "反撃",
    "direction": "劣勢時に攻撃力上昇",
    "cost": 5,
    "attack": 7,
    "defense": 3,
    "troop": 9,
    "skillName": "不屈の反撃",
    "skillText": "自分の兵力が４以下の間、このカードの攻撃力＋３。",
    "traitName": "解放の意志",
    "traitText": "１ターンに１回、戦闘で生き残った時、自分の兵力を１回復する。",
    "title": "自由を求める剣闘士",
    "quote": "この鎖を砕き、自由をつかむ！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 52
  },
  {
    "id": "SR12",
    "name": "サラディン",
    "rarity": "SR",
    "type": "騎兵・回復",
    "direction": "攻撃＋味方回復",
    "cost": 5,
    "attack": 6,
    "defense": 5,
    "troop": 8,
    "skillName": "慈悲の進軍",
    "skillText": "攻撃後、味方１体の兵力を２回復する。兵力は初期値を超えない。",
    "traitName": "騎兵の統率",
    "traitText": "自分の場に他の味方がいる間、このカードの攻撃力＋１。",
    "title": "慈悲深き騎士王",
    "quote": "勇気で進み、慈悲で守る！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 53
  },
  {
    "id": "SR13",
    "name": "ウィリアム1世",
    "rarity": "SR",
    "type": "征服",
    "direction": "敵撃破で強化",
    "cost": 5,
    "attack": 6,
    "defense": 5,
    "troop": 9,
    "skillName": "征服者の進撃",
    "skillText": "戦闘で敵を倒すたび、このカードの攻撃力＋１（最大＋３）。",
    "traitName": "ノルマンの盾",
    "traitText": "兵力が初期値の時、このカードの防御力＋１。",
    "title": "海を越えた征服王",
    "quote": "この一歩から、新たな王国を！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 54
  },
  {
    "id": "SR14",
    "name": "エリザベス1世",
    "rarity": "SR",
    "type": "支援",
    "direction": "味方全体を強化",
    "cost": 6,
    "attack": 3,
    "defense": 5,
    "troop": 8,
    "skillName": "女王の号令",
    "skillText": "登場時、味方全体の攻撃力＋１。効果はこのターン終了時まで。",
    "traitName": "王国の結束",
    "traitText": "このカードが場にいる間、他の味方全体の防御力＋１。",
    "title": "黄金時代を導く女王",
    "quote": "皆の力で、黄金の時代へ！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 55
  },
  {
    "id": "SR15",
    "name": "ルイ14世",
    "rarity": "SR",
    "type": "王権",
    "direction": "場の味方が多いほど強い",
    "cost": 6,
    "attack": 4,
    "defense": 5,
    "troop": 9,
    "skillName": "太陽王の威光",
    "skillText": "他の味方１体につき、このカードの攻撃力＋１（最大＋３）。",
    "traitName": "宮廷の守り",
    "traitText": "他の味方が２体以上いる間、このカードの防御力＋１。",
    "title": "栄光をまとう太陽王",
    "quote": "我が宮廷に、栄光あれ！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 56
  },
  {
    "id": "SR16",
    "name": "ピョートル大帝",
    "rarity": "SR",
    "type": "改革",
    "direction": "弱いカードを強化",
    "cost": 5,
    "attack": 5,
    "defense": 5,
    "troop": 9,
    "skillName": "大改革",
    "skillText": "登場時、攻撃力４以下の味方１体の攻撃力と防御力をそれぞれ２上げる。",
    "traitName": "技術の導入",
    "traitText": "自分のターン開始時、攻撃力４以下の味方１体の兵力を１回復する。",
    "title": "未来を切り拓く改革者",
    "quote": "学び、造り、新たな国へ！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 57
  },
  {
    "id": "SR17",
    "name": "孫子",
    "rarity": "SR",
    "type": "軍略",
    "direction": "相手の行動を読む・妨害",
    "cost": 5,
    "attack": 3,
    "defense": 6,
    "troop": 8,
    "skillName": "兵法の洞察",
    "skillText": "登場時、相手の手札を１枚ランダムに見る。さらに、敵１体の攻撃力を次のターンまで１下げる。",
    "traitName": "備えの軍略",
    "traitText": "相手のターン中、このカードの防御力＋２。",
    "title": "戦わずして勝つ軍略家",
    "quote": "敵を知り、勝利への道を読む！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 58
  },
  {
    "id": "SR18",
    "name": "岳飛",
    "rarity": "SR",
    "type": "忠義・防御",
    "direction": "味方をかばう",
    "cost": 5,
    "attack": 5,
    "defense": 7,
    "troop": 10,
    "skillName": "忠義の守護",
    "skillText": "１ターンに１回、他の味方が受ける攻撃を、このカードが代わりに受ける。",
    "traitName": "不屈の忠誠",
    "traitText": "味方をかばう戦闘中、このカードの防御力＋２。",
    "title": "忠義を貫く守護将軍",
    "quote": "この身を盾に、仲間を守る！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 59
  },
  {
    "id": "SR19",
    "name": "マルコ・ポーロ",
    "rarity": "SR",
    "type": "探索",
    "direction": "山札からカードを探す",
    "cost": 5,
    "attack": 4,
    "defense": 4,
    "troop": 8,
    "skillName": "東方への道",
    "skillText": "登場時、山札からコスト４以下のカードを１枚公開して手札に加え、山札を切る。",
    "traitName": "旅の知恵",
    "traitText": "自分の手札が５枚以上ある間、このカードの防御力＋２。",
    "title": "東西を結ぶ旅の語り部",
    "quote": "まだ見ぬ世界が、私を待っている！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 60
  },
  {
    "id": "SR20",
    "name": "コロンブス",
    "rarity": "SR",
    "type": "探索",
    "direction": "ドロー能力",
    "cost": 5,
    "attack": 4,
    "defense": 5,
    "troop": 8,
    "skillName": "大西洋の航路",
    "skillText": "登場時、山札からカードを２枚引き、その後、手札を１枚捨てる。",
    "traitName": "航海の備え",
    "traitText": "自分の手札が４枚以上ある間、このカードの防御力＋１。",
    "title": "大西洋へ挑む航海者",
    "quote": "水平線の先へ、帆を上げよう！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 61
  },
  {
    "id": "SR21",
    "name": "マゼラン",
    "rarity": "SR",
    "type": "航海",
    "direction": "デッキ操作",
    "cost": 5,
    "attack": 5,
    "defense": 4,
    "troop": 8,
    "skillName": "未知なる海峡",
    "skillText": "登場時、山札の上から３枚を見る。好きな順番で山札の上に戻す。",
    "traitName": "航路の選択",
    "traitText": "自分のターン開始時、山札の一番上の１枚を見て、山札の下に移してもよい。",
    "title": "世界をつなぐ航路の先駆者",
    "quote": "未知の海にも、進む道はある！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 62
  },
  {
    "id": "SR22",
    "name": "エジソン",
    "rarity": "SR",
    "type": "発明",
    "direction": "味方カードを強化",
    "cost": 5,
    "attack": 3,
    "defense": 5,
    "troop": 8,
    "skillName": "発明のひらめき",
    "skillText": "登場時、他の味方１体の攻撃力と防御力をそれぞれ２上げる。",
    "traitName": "改良の積み重ね",
    "traitText": "自分のターン開始時、他の味方１体の攻撃力＋１（この特性では最大＋２）。",
    "title": "ひらめきを灯す発明家",
    "quote": "ひらめきを、みんなの力に！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": "背景英字を除去した修正版が最終版",
    "sourceRow": 63
  },
  {
    "id": "SR23",
    "name": "ファラデー",
    "rarity": "SR",
    "type": "科学",
    "direction": "エネルギー増加",
    "cost": 5,
    "attack": 3,
    "defense": 5,
    "troop": 8,
    "skillName": "電磁誘導",
    "skillText": "登場時、自分のエネルギーを２増やす。",
    "traitName": "実験の積み重ね",
    "traitText": "自分のターン開始時、自分のエネルギーを１増やす。",
    "title": "電磁の力を解き明かす科学者",
    "quote": "見えない力が、未来を動かす！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": "背景英字を除去した修正版が最終版",
    "sourceRow": 64
  },
  {
    "id": "SR24",
    "name": "パスカル",
    "rarity": "SR",
    "type": "知略",
    "direction": "コスト軽減",
    "cost": 5,
    "attack": 3,
    "defense": 6,
    "troop": 7,
    "skillName": "計算する知恵",
    "skillText": "登場時、このターンに次に使うカード１枚のコストを２下げる（最低１）。",
    "traitName": "思考の節約",
    "traitText": "自分の手札が３枚以下なら、毎ターン最初に使うカードのコスト－１（最低１）。",
    "title": "数理で未来をひらく知恵者",
    "quote": "考える力で、可能性をひらく！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 65
  },
  {
    "id": "SR25",
    "name": "ベートーヴェン",
    "rarity": "SR",
    "type": "鼓舞",
    "direction": "味方全体の兵力強化",
    "cost": 6,
    "attack": 4,
    "defense": 5,
    "troop": 8,
    "skillName": "運命の交響曲",
    "skillText": "登場時、味方全体の兵力と兵力の上限をそれぞれ２増やす。",
    "traitName": "不屈の旋律",
    "traitText": "兵力が初期値の半分以下の味方は、このカードが場にいる間、攻撃力＋１。",
    "title": "魂を奮い立たせる楽聖",
    "quote": "この響きで、心よ立ち上がれ！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 66
  },
  {
    "id": "SR26",
    "name": "モーツァルト",
    "rarity": "SR",
    "type": "支援",
    "direction": "手札・回復支援",
    "cost": 5,
    "attack": 3,
    "defense": 4,
    "troop": 8,
    "skillName": "癒やしのセレナーデ",
    "skillText": "登場時、カードを１枚引く。味方１体の兵力を２回復する（上限まで）。",
    "traitName": "調和のしらべ",
    "traitText": "自分のターン開始時、味方１体の兵力を１回復する（上限まで）。",
    "title": "優雅に奏でる音楽の天才",
    "quote": "軽やかな調べで、笑顔を届けよう！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 67
  },
  {
    "id": "SR27",
    "name": "シェイクスピア",
    "rarity": "SR",
    "type": "特殊",
    "direction": "状況に応じて能力変化",
    "cost": 5,
    "attack": 4,
    "defense": 4,
    "troop": 8,
    "skillName": "運命の一幕",
    "skillText": "登場時、手札が３枚以下なら１枚引く。４枚以上なら味方１体の攻撃力＋２。",
    "traitName": "喜劇と悲劇",
    "traitText": "兵力が５以上なら攻撃力＋１。兵力が４以下なら防御力＋２。",
    "title": "幾千の物語を紡ぐ劇作家",
    "quote": "さあ、君だけの物語を始めよう！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": null,
    "sourceRow": 68
  },
  {
    "id": "R01",
    "name": "聖武天皇",
    "rarity": "R",
    "type": "守護",
    "direction": "味方防御強化＋兵力回復",
    "cost": 3,
    "attack": 2,
    "defense": 5,
    "troop": 7,
    "skillName": "鎮護の祈り",
    "skillText": "登場時、味方１体の防御力＋２。効果は次の自分のターン開始時まで。",
    "traitName": "慈しみの心",
    "traitText": "登場時、味方１体の兵力を１回復する（上限まで）。",
    "title": "祈りで国を守る帝",
    "quote": "人々の安らぎを、この国に！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": "能力の方向性は既存効果文の要約",
    "sourceRow": 69
  },
  {
    "id": "R02",
    "name": "桓武天皇",
    "rarity": "R",
    "type": "統率",
    "direction": "味方攻撃強化＋自己防御強化",
    "cost": 3,
    "attack": 3,
    "defense": 4,
    "troop": 7,
    "skillName": "新都の号令",
    "skillText": "登場時、他の味方１体の攻撃力＋１。効果はこのターン終了時まで。",
    "traitName": "都の統率",
    "traitText": "自分の場に他の味方がいる間、このカードの防御力＋１。",
    "title": "新たな都をひらく帝",
    "quote": "ここから、新しい都の未来を！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": "能力の方向性は既存効果文の要約",
    "sourceRow": 70
  },
  {
    "id": "R03",
    "name": "藤原道長",
    "rarity": "R",
    "type": "政治",
    "direction": "エネルギー獲得＋味方数に応じた自己防御強化",
    "cost": 3,
    "attack": 2,
    "defense": 4,
    "troop": 6,
    "skillName": "宮廷の采配",
    "skillText": "登場時、自分のエネルギーを１増やす。",
    "traitName": "貴族の結束",
    "traitText": "他の味方が２体以上いる間、このカードの防御力＋１。",
    "title": "栄華を築く宮廷の実力者",
    "quote": "知恵を巡らせ、栄華を築こう！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": "能力の方向性は既存効果文の要約",
    "sourceRow": 71
  },
  {
    "id": "R04",
    "name": "菅原道真",
    "rarity": "R",
    "type": "学問",
    "direction": "ドロー＋手札数に応じた自己防御強化",
    "cost": 3,
    "attack": 2,
    "defense": 4,
    "troop": 6,
    "skillName": "学問のひらめき",
    "skillText": "登場時、山札からカードを１枚引く。",
    "traitName": "知恵の蓄え",
    "traitText": "自分の手札が４枚以上ある間、このカードの防御力＋１。",
    "title": "学びの道を照らす才人",
    "quote": "学ぶ心が、明日の道をひらく！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": "能力の方向性は既存効果文の要約",
    "sourceRow": 72
  },
  {
    "id": "R05",
    "name": "源頼朝",
    "rarity": "R",
    "type": "統率",
    "direction": "味方攻撃強化＋味方数に応じた自己防御強化",
    "cost": 4,
    "attack": 4,
    "defense": 4,
    "troop": 7,
    "skillName": "鎌倉の号令",
    "skillText": "登場時、他の味方１体の攻撃力＋１。効果は次の自分のターン開始時まで。",
    "traitName": "武家の結束",
    "traitText": "他の味方が２体以上いる間、このカードの防御力＋１。",
    "title": "鎌倉に武家の世を築く将",
    "quote": "武士の力を、一つに束ねよう！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": "能力の方向性は既存効果文の要約",
    "sourceRow": 73
  },
  {
    "id": "R06",
    "name": "足利尊氏",
    "rarity": "R",
    "type": "攻撃",
    "direction": "登場時攻撃強化＋兵力最大時強化",
    "cost": 4,
    "attack": 5,
    "defense": 3,
    "troop": 7,
    "skillName": "突破の太刀",
    "skillText": "登場したターン、このカードの攻撃力＋２。",
    "traitName": "攻めの気迫",
    "traitText": "自分の兵力が初期値の時、このカードの攻撃力＋１。",
    "title": "戦場を駆ける武家の棟梁",
    "quote": "いざ進め、勝利への道を！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": "能力の方向性は既存効果文の要約",
    "sourceRow": 74
  },
  {
    "id": "R07",
    "name": "足利義満",
    "rarity": "R",
    "type": "交易",
    "direction": "エネルギー獲得＋味方数に応じたドロー",
    "cost": 3,
    "attack": 2,
    "defense": 4,
    "troop": 7,
    "skillName": "交易の実り",
    "skillText": "登場時、自分のエネルギーを１増やす。",
    "traitName": "繁栄の支え",
    "traitText": "他の味方が２体以上いる時に登場すると、山札からカードを１枚引く。",
    "title": "黄金の都と交易を育む将",
    "quote": "海の向こうと、豊かさをつなごう！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": "能力の方向性は既存効果文の要約",
    "sourceRow": 75
  },
  {
    "id": "R08",
    "name": "北条早雲",
    "rarity": "R",
    "type": "奇襲",
    "direction": "敵防御を低く扱う＋劣勢時攻撃強化",
    "cost": 3,
    "attack": 4,
    "defense": 3,
    "troop": 6,
    "skillName": "夜明けの奇襲",
    "skillText": "登場したターン、攻撃する敵の防御力を１低いものとして扱う。",
    "traitName": "機をうかがう目",
    "traitText": "相手の場のカード数が自分より多い間、このカードの攻撃力＋１。",
    "title": "乱世の扉をひらく智将",
    "quote": "好機をつかみ、道を切りひらく！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": "能力の方向性は既存効果文の要約",
    "sourceRow": 76
  },
  {
    "id": "R09",
    "name": "毛利元就",
    "rarity": "R",
    "type": "知略",
    "direction": "敵攻撃低下＋味方数に応じた自己強化",
    "cost": 4,
    "attack": 3,
    "defense": 4,
    "troop": 7,
    "skillName": "三矢の策",
    "skillText": "登場時、敵１体の攻撃力を１下げる。効果は次の自分のターン開始時まで。",
    "traitName": "三本の矢",
    "traitText": "他の味方が２体以上いる間、このカードの攻撃力と防御力＋１。",
    "title": "三矢の知恵を授ける謀将",
    "quote": "知恵と絆で、勝利をつかもう！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": "能力の方向性は既存効果文の要約",
    "sourceRow": 77
  },
  {
    "id": "R10",
    "name": "長宗我部元親",
    "rarity": "R",
    "type": "統率",
    "direction": "味方攻撃強化＋低コストの味方で自己強化",
    "cost": 4,
    "attack": 4,
    "defense": 4,
    "troop": 7,
    "skillName": "土佐の号令",
    "skillText": "登場時、他の味方１体の攻撃力＋１。効果はこのターン終了時まで。",
    "traitName": "一領具足の絆",
    "traitText": "コスト３以下の味方がいる間、このカードの攻撃力＋１。",
    "title": "土佐から翔ける雄将",
    "quote": "心を一つに、四国の先へ！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": "能力の方向性は既存効果文の要約",
    "sourceRow": 78
  },
  {
    "id": "R11",
    "name": "島津義弘",
    "rarity": "R",
    "type": "攻撃",
    "direction": "登場時攻撃強化＋兵力低下時強化",
    "cost": 4,
    "attack": 5,
    "defense": 3,
    "troop": 7,
    "skillName": "薩摩の猛攻",
    "skillText": "登場したターン、このカードの攻撃力＋２。",
    "traitName": "不屈の武勇",
    "traitText": "自分の兵力が３以下の間、このカードの攻撃力＋１。",
    "title": "薩摩の誇りを貫く猛将",
    "quote": "退かぬ心で、道を切りひらく！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": "能力の方向性は既存効果文の要約",
    "sourceRow": 79
  },
  {
    "id": "R12",
    "name": "井伊直虎",
    "rarity": "R",
    "type": "防御",
    "direction": "味方防御強化＋自己防御強化",
    "cost": 3,
    "attack": 3,
    "defense": 5,
    "troop": 7,
    "skillName": "女城主の守り",
    "skillText": "登場時、他の味方１体の防御力＋２。効果は次の自分のターン開始時まで。",
    "traitName": "里を守る決意",
    "traitText": "自分の場に他の味方がいる間、このカードの防御力＋１。",
    "title": "井伊の里を守る女城主",
    "quote": "この里も、仲間も、私が守る！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": "能力の方向性は既存効果文の要約",
    "sourceRow": 80
  },
  {
    "id": "R13",
    "name": "大久保利通",
    "rarity": "R",
    "type": "改革",
    "direction": "弱い味方の攻防強化＋自己防御強化",
    "cost": 3,
    "attack": 2,
    "defense": 4,
    "troop": 7,
    "skillName": "改革の一歩",
    "skillText": "登場時、攻撃力３以下の味方１体の攻撃力と防御力をそれぞれ１上げる。",
    "traitName": "実務の積み重ね",
    "traitText": "コスト３以下の他の味方がいる間、このカードの防御力＋１。",
    "title": "新たな国の礎を築く改革者",
    "quote": "確かな一歩で、新しい国へ！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": "能力の方向性は既存効果文の要約",
    "sourceRow": 81
  },
  {
    "id": "R14",
    "name": "伊藤博文",
    "rarity": "R",
    "type": "政治",
    "direction": "エネルギー獲得＋手札交換",
    "cost": 3,
    "attack": 2,
    "defense": 4,
    "troop": 6,
    "skillName": "政治の調整",
    "skillText": "登場時、自分のエネルギーを１増やす。",
    "traitName": "対話の手腕",
    "traitText": "登場時、手札が３枚以下なら、カードを１枚引き、その後１枚捨てる。",
    "title": "近代政治の道を拓く宰相",
    "quote": "知恵を交わし、国の形を築こう！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": "能力の方向性は既存効果文の要約",
    "sourceRow": 82
  },
  {
    "id": "R15",
    "name": "福沢諭吉",
    "rarity": "R",
    "type": "学問",
    "direction": "ドロー＋単独時の攻防強化",
    "cost": 3,
    "attack": 2,
    "defense": 4,
    "troop": 6,
    "skillName": "学びのすすめ",
    "skillText": "登場時、山札からカードを１枚引く。",
    "traitName": "独立の精神",
    "traitText": "自分の場に他の味方がいない間、このカードの攻撃力と防御力＋１。",
    "title": "学びで未来を拓く啓蒙家",
    "quote": "学ぶ力で、自分の道を歩もう！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": "能力の方向性は既存効果文の要約",
    "sourceRow": 83
  },
  {
    "id": "R16",
    "name": "ペリクレス",
    "rarity": "R",
    "type": "統率",
    "direction": "味方攻撃強化＋自己防御強化",
    "cost": 4,
    "attack": 3,
    "defense": 4,
    "troop": 7,
    "skillName": "雄弁なる号令",
    "skillText": "登場時、他の味方１体の攻撃力＋１。効果は次の自分のターン開始時まで。",
    "traitName": "都市の結束",
    "traitText": "他の味方が２体以上いる間、このカードの防御力＋１。",
    "title": "アテナイを導く雄弁な将",
    "quote": "声と知恵を合わせ、都市の未来へ！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": "能力の方向性は既存効果文の要約",
    "sourceRow": 84
  },
  {
    "id": "R17",
    "name": "アウグストゥス",
    "rarity": "R",
    "type": "統治",
    "direction": "味方兵力回復＋自己防御強化",
    "cost": 4,
    "attack": 3,
    "defense": 4,
    "troop": 8,
    "skillName": "帝国の安定",
    "skillText": "登場時、味方１体の兵力を２回復する（上限まで）。",
    "traitName": "統治の礎",
    "traitText": "他の味方が２体以上いる間、このカードの防御力＋１。",
    "title": "ローマの秩序を築く初代皇帝",
    "quote": "秩序を築き、安らぎを広げよう！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": "能力の方向性は既存効果文の要約",
    "sourceRow": 85
  },
  {
    "id": "R18",
    "name": "コンスタンティヌス1世",
    "rarity": "R",
    "type": "防御",
    "direction": "登場時防御強化＋兵力最大時強化",
    "cost": 4,
    "attack": 3,
    "defense": 5,
    "troop": 8,
    "skillName": "皇帝の守護",
    "skillText": "登場したターンから次の自分のターン開始時まで、防御力＋２。",
    "traitName": "堅固な備え",
    "traitText": "自分の兵力が初期値の時、このカードの防御力＋１。",
    "title": "新たな都を守る皇帝",
    "quote": "揺るがぬ守りで、未来を支えよう！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": "能力の方向性は既存効果文の要約",
    "sourceRow": 86
  },
  {
    "id": "R19",
    "name": "カール大帝",
    "rarity": "R",
    "type": "統率",
    "direction": "味方攻撃強化＋自己攻撃強化",
    "cost": 4,
    "attack": 4,
    "defense": 4,
    "troop": 8,
    "skillName": "王国の号令",
    "skillText": "登場時、他の味方１体の攻撃力＋１。効果は次の自分のターン開始時まで。",
    "traitName": "王の統率",
    "traitText": "他の味方が２体以上いる間、このカードの攻撃力＋１。",
    "title": "広き王国を束ねる大帝",
    "quote": "心を束ね、王国の明日を築く！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": "能力の方向性は既存効果文の要約",
    "sourceRow": 87
  },
  {
    "id": "R20",
    "name": "ウィリアム・ウォレス",
    "rarity": "R",
    "type": "反撃",
    "direction": "兵力低下時攻撃強化＋戦闘後回復",
    "cost": 4,
    "attack": 4,
    "defense": 3,
    "troop": 8,
    "skillName": "不屈の反撃",
    "skillText": "自分の兵力が４以下の間、このカードの攻撃力＋２。",
    "traitName": "立ち上がる勇気",
    "traitText": "１ターンに１回、戦闘で生き残った時、自分の兵力を１回復する（上限まで）。",
    "title": "自由への意志を貫く勇士",
    "quote": "何度倒れても、自由への意志は折れぬ！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": "能力の方向性は既存効果文の要約",
    "sourceRow": 88
  },
  {
    "id": "R21",
    "name": "フリードリヒ2世",
    "rarity": "R",
    "type": "軍略",
    "direction": "敵防御低下＋劣勢時防御強化",
    "cost": 4,
    "attack": 4,
    "defense": 4,
    "troop": 7,
    "skillName": "大王の軍略",
    "skillText": "登場時、敵１体の防御力を１下げる。効果はこのターン終了時まで。",
    "traitName": "冷静な指揮",
    "traitText": "相手の場のカード数が自分より多い間、このカードの防御力＋１。",
    "title": "戦局を読むプロイセンの大王",
    "quote": "戦局を読み、勝利への一手を！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": "能力の方向性は既存効果文の要約",
    "sourceRow": 89
  },
  {
    "id": "R22",
    "name": "マリア・テレジア",
    "rarity": "R",
    "type": "支援",
    "direction": "味方兵力回復＋自己防御強化",
    "cost": 4,
    "attack": 2,
    "defense": 5,
    "troop": 8,
    "skillName": "女王の支援",
    "skillText": "登場時、味方１体の兵力を２回復する（上限まで）。",
    "traitName": "宮廷の結束",
    "traitText": "他の味方が２体以上いる間、このカードの防御力＋１。",
    "title": "国を支える不屈の女王",
    "quote": "皆の力を合わせ、明日を守ろう！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": "能力の方向性は既存効果文の要約",
    "sourceRow": 90
  },
  {
    "id": "R23",
    "name": "ワシントン",
    "rarity": "R",
    "type": "統率",
    "direction": "味方攻撃強化＋自己防御強化",
    "cost": 4,
    "attack": 4,
    "defense": 4,
    "troop": 7,
    "skillName": "結束の号令",
    "skillText": "登場時、他の味方１体の攻撃力＋１。効果は次の自分のターン開始時まで。",
    "traitName": "指導者の信頼",
    "traitText": "他の味方が２体以上いる間、このカードの防御力＋１。",
    "title": "仲間を率いる建国の指導者",
    "quote": "心を一つに、未来へ進もう！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": "能力の方向性は既存効果文の要約",
    "sourceRow": 91
  },
  {
    "id": "R24",
    "name": "リンカーン",
    "rarity": "R",
    "type": "支援",
    "direction": "味方防御強化＋兵力回復",
    "cost": 3,
    "attack": 2,
    "defense": 4,
    "troop": 7,
    "skillName": "希望の演説",
    "skillText": "登場時、他の味方１体の防御力＋１。効果は次の自分のターン開始時まで。",
    "traitName": "寄り添う心",
    "traitText": "登場時、味方１体の兵力を１回復する（上限まで）。",
    "title": "信念で人々をつなぐ指導者",
    "quote": "希望をつなぎ、共に歩もう！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": "能力の方向性は既存効果文の要約",
    "sourceRow": 92
  },
  {
    "id": "R25",
    "name": "ガリバルディ",
    "rarity": "R",
    "type": "攻撃",
    "direction": "登場時攻撃強化＋味方がいる間の自己強化",
    "cost": 4,
    "attack": 5,
    "defense": 3,
    "troop": 7,
    "skillName": "赤シャツの進撃",
    "skillText": "登場したターン、このカードの攻撃力＋２。",
    "traitName": "義勇の気迫",
    "traitText": "自分の場に他の味方がいる間、このカードの攻撃力＋１。",
    "title": "赤シャツで駆ける義勇の闘士",
    "quote": "情熱を胸に、道を切りひらく！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": "能力の方向性は既存効果文の要約",
    "sourceRow": 93
  },
  {
    "id": "R26",
    "name": "孫文",
    "rarity": "R",
    "type": "改革",
    "direction": "弱い味方の攻防強化＋自己防御強化",
    "cost": 3,
    "attack": 2,
    "defense": 4,
    "troop": 7,
    "skillName": "改革の志",
    "skillText": "登場時、攻撃力３以下の味方１体の攻撃力と防御力をそれぞれ１上げる。",
    "traitName": "志の結束",
    "traitText": "コスト３以下の他の味方がいる間、このカードの防御力＋１。",
    "title": "新たな時代を志す革命家",
    "quote": "志をつなぎ、新しい時代へ！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": "能力の方向性は既存効果文の要約",
    "sourceRow": 94
  },
  {
    "id": "R27",
    "name": "劉邦",
    "rarity": "R",
    "type": "統率",
    "direction": "味方攻撃強化＋自己防御強化",
    "cost": 4,
    "attack": 3,
    "defense": 4,
    "troop": 8,
    "skillName": "人望の采配",
    "skillText": "登場時、他の味方１体の攻撃力＋１。効果は次の自分のターン開始時まで。",
    "traitName": "仲間を生かす才",
    "traitText": "他の味方が２体以上いる間、このカードの防御力＋１。",
    "title": "人を集めて天下を築く英傑",
    "quote": "皆の力で、大きな夢をつかもう！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": "能力の方向性は既存効果文の要約",
    "sourceRow": 95
  },
  {
    "id": "R28",
    "name": "項羽",
    "rarity": "R",
    "type": "攻撃",
    "direction": "登場時攻撃強化＋兵力最大時強化",
    "cost": 4,
    "attack": 6,
    "defense": 2,
    "troop": 8,
    "skillName": "覇王の一撃",
    "skillText": "登場したターン、このカードの攻撃力＋２。",
    "traitName": "猛将の気迫",
    "traitText": "自分の兵力が初期値の時、このカードの攻撃力＋１。",
    "title": "圧倒的な武勇を誇る覇王",
    "quote": "この一撃で、道を切りひらく！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": "能力の方向性は既存効果文の要約",
    "sourceRow": 96
  },
  {
    "id": "R29",
    "name": "曹操",
    "rarity": "R",
    "type": "軍略",
    "direction": "敵攻撃低下＋手札数に応じた自己防御強化",
    "cost": 4,
    "attack": 4,
    "defense": 4,
    "troop": 7,
    "skillName": "乱世の軍略",
    "skillText": "登場時、敵１体の攻撃力を１下げる。効果は次の自分のターン開始時まで。",
    "traitName": "策士の備え",
    "traitText": "自分の手札が４枚以上ある間、このカードの防御力＋１。",
    "title": "乱世を読み解く智勇の将",
    "quote": "機を読み、勝利を手繰り寄せる！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": "能力の方向性は既存効果文の要約",
    "sourceRow": 97
  },
  {
    "id": "R30",
    "name": "劉備",
    "rarity": "R",
    "type": "仲間強化",
    "direction": "味方攻防強化＋自己防御強化",
    "cost": 4,
    "attack": 3,
    "defense": 4,
    "troop": 8,
    "skillName": "仁徳の支え",
    "skillText": "登場時、他の味方１体の攻撃力と防御力をそれぞれ１上げる。",
    "traitName": "絆の力",
    "traitText": "他の味方が２体以上いる間、このカードの防御力＋１。",
    "title": "仁と絆で仲間を導く英傑",
    "quote": "仲間と共に、希望の道を歩もう！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": "能力の方向性は既存効果文の要約",
    "sourceRow": 98
  },
  {
    "id": "R31",
    "name": "関羽",
    "rarity": "R",
    "type": "武勇",
    "direction": "登場時攻撃強化＋自己防御強化",
    "cost": 4,
    "attack": 5,
    "defense": 4,
    "troop": 7,
    "skillName": "義勇の一閃",
    "skillText": "登場したターン、このカードの攻撃力＋２。",
    "traitName": "揺るがぬ忠義",
    "traitText": "自分の場に他の味方がいる間、このカードの防御力＋１。",
    "title": "義を貫く美髯の武人",
    "quote": "義を胸に、仲間の道を守る！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": "能力の方向性は既存効果文の要約",
    "sourceRow": 99
  },
  {
    "id": "R32",
    "name": "張飛",
    "rarity": "R",
    "type": "攻撃",
    "direction": "登場時攻撃強化＋兵力低下時強化",
    "cost": 4,
    "attack": 6,
    "defense": 2,
    "troop": 8,
    "skillName": "猛将の突撃",
    "skillText": "登場したターン、このカードの攻撃力＋２。",
    "traitName": "豪胆な気迫",
    "traitText": "自分の兵力が４以下の間、このカードの攻撃力＋１。",
    "title": "豪胆な叫びで道を拓く猛将",
    "quote": "この一歩は、誰にも止めさせぬ！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": "能力の方向性は既存効果文の要約",
    "sourceRow": 100
  },
  {
    "id": "R33",
    "name": "司馬遷",
    "rarity": "R",
    "type": "知識",
    "direction": "山札の順序操作＋自己防御強化",
    "cost": 3,
    "attack": 2,
    "defense": 4,
    "troop": 6,
    "skillName": "歴史の記録",
    "skillText": "登場時、山札の上から２枚を見て、好きな順番で山札の上に戻す。",
    "traitName": "知識の蓄え",
    "traitText": "自分の手札が４枚以上ある間、このカードの防御力＋１。",
    "title": "歴史を未来へ伝える記録者",
    "quote": "記した言葉を、未来への灯に！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": "能力の方向性は既存効果文の要約",
    "sourceRow": 101
  },
  {
    "id": "R34",
    "name": "玄奘",
    "rarity": "R",
    "type": "探索",
    "direction": "山札からカード選択＋兵力低下時防御強化",
    "cost": 3,
    "attack": 2,
    "defense": 4,
    "troop": 7,
    "skillName": "西方への探求",
    "skillText": "登場時、山札の上から３枚を見る。１枚を手札に加え、残りを山札の下に戻す。",
    "traitName": "旅の忍耐",
    "traitText": "自分の兵力が３以下の間、このカードの防御力＋１。",
    "title": "学びを求めて西へ歩む僧",
    "quote": "一歩ずつ、学びの道を進もう！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": "能力の方向性は既存効果文の要約",
    "sourceRow": 102
  },
  {
    "id": "R35",
    "name": "鄭和",
    "rarity": "R",
    "type": "航海",
    "direction": "山札の順序操作＋自己防御強化",
    "cost": 4,
    "attack": 3,
    "defense": 4,
    "troop": 8,
    "skillName": "大船団の航路",
    "skillText": "登場時、山札の上から３枚を見る。好きな順番で山札の上に戻す。",
    "traitName": "航海の備え",
    "traitText": "自分の手札が４枚以上ある間、このカードの防御力＋１。",
    "title": "大海原を渡る船団の指揮者",
    "quote": "帆を上げ、海の向こうへ進もう！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": "能力の方向性は既存効果文の要約",
    "sourceRow": 103
  },
  {
    "id": "R36",
    "name": "アルキメデス",
    "rarity": "R",
    "type": "発明",
    "direction": "味方攻撃強化＋自己防御強化",
    "cost": 3,
    "attack": 2,
    "defense": 4,
    "troop": 6,
    "skillName": "てこのひらめき",
    "skillText": "登場時、他の味方１体の攻撃力を２上げる。",
    "traitName": "工夫の積み重ね",
    "traitText": "コスト３以下の他の味方がいる間、このカードの防御力＋１。",
    "title": "ひらめきで世界を動かす賢者",
    "quote": "小さなひらめきで、大きな力を！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": "能力の方向性は既存効果文の要約",
    "sourceRow": 104
  },
  {
    "id": "R37",
    "name": "ヒポクラテス",
    "rarity": "R",
    "type": "回復",
    "direction": "味方兵力回復＋味方数に応じた追加回復",
    "cost": 3,
    "attack": 2,
    "defense": 4,
    "troop": 7,
    "skillName": "癒やしの手当て",
    "skillText": "登場時、味方１体の兵力を２回復する（上限まで）。",
    "traitName": "丁寧な看護",
    "traitText": "登場時、他の味方が２体以上いるなら、さらに味方１体の兵力を１回復する。",
    "title": "命に寄り添う医術の探求者",
    "quote": "寄り添う心で、命を支えよう！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": "能力の方向性は既存効果文の要約",
    "sourceRow": 105
  },
  {
    "id": "R38",
    "name": "ミケランジェロ",
    "rarity": "R",
    "type": "強化",
    "direction": "味方攻防強化＋兵力最大時防御強化",
    "cost": 4,
    "attack": 3,
    "defense": 4,
    "troop": 7,
    "skillName": "巨匠の造形",
    "skillText": "登場時、他の味方１体の攻撃力と防御力をそれぞれ１上げる。",
    "traitName": "磨き上げる情熱",
    "traitText": "自分の兵力が初期値の時、このカードの防御力＋１。",
    "title": "石に命を刻む芸術の巨匠",
    "quote": "この手で、眠れる力を形に！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": "能力の方向性は既存効果文の要約",
    "sourceRow": 106
  },
  {
    "id": "R39",
    "name": "ラファエロ",
    "rarity": "R",
    "type": "支援",
    "direction": "味方防御強化＋兵力回復",
    "cost": 3,
    "attack": 2,
    "defense": 4,
    "troop": 6,
    "skillName": "調和の彩り",
    "skillText": "登場時、他の味方１体の防御力＋１。効果は次の自分のターン開始時まで。",
    "traitName": "優美な支え",
    "traitText": "登場時、味方１体の兵力を１回復する（上限まで）。",
    "title": "調和と美を描く絵画の才人",
    "quote": "彩りを重ね、心をつなごう！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": "能力の方向性は既存効果文の要約",
    "sourceRow": 107
  },
  {
    "id": "R40",
    "name": "グーテンベルク",
    "rarity": "R",
    "type": "ドロー",
    "direction": "ドロー＋自己防御強化",
    "cost": 3,
    "attack": 2,
    "defense": 4,
    "troop": 6,
    "skillName": "活版印刷",
    "skillText": "登場時、山札からカードを１枚引く。",
    "traitName": "知識の普及",
    "traitText": "自分の手札が４枚以上ある間、このカードの防御力＋１。",
    "title": "言葉を広める印刷の先駆者",
    "quote": "一枚の紙から、知恵を世界へ！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": "能力の方向性は既存効果文の要約",
    "sourceRow": 108
  },
  {
    "id": "R41",
    "name": "ジェームズ・ワット",
    "rarity": "R",
    "type": "エネルギー",
    "direction": "エネルギー獲得＋自己防御強化",
    "cost": 3,
    "attack": 2,
    "defense": 4,
    "troop": 6,
    "skillName": "蒸気機関",
    "skillText": "登場時、自分のエネルギーを１増やす。",
    "traitName": "改良の積み重ね",
    "traitText": "コスト３以下の他の味方がいる間、このカードの防御力＋１。",
    "title": "蒸気の力で時代を動かす発明家",
    "quote": "蒸気の力で、未来を動かそう！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": "能力の方向性は既存効果文の要約",
    "sourceRow": 109
  },
  {
    "id": "R42",
    "name": "ライト兄弟",
    "rarity": "R",
    "type": "先制",
    "direction": "登場ターンの先制攻撃＋自己攻撃強化",
    "cost": 4,
    "attack": 4,
    "defense": 3,
    "troop": 7,
    "skillName": "はじまりの飛翔",
    "skillText": "登場したターンの最初の戦闘では、相手より先に攻撃する。",
    "traitName": "兄弟の連携",
    "traitText": "自分の場に他の味方がいる間、このカードの攻撃力＋１。",
    "title": "空への夢を翼に変えた兄弟",
    "quote": "二人の知恵で、空への夢を！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": "能力の方向性は既存効果文の要約。ライト兄弟を1組・1カードとして制作",
    "sourceRow": 110
  },
  {
    "id": "R43",
    "name": "ナイチンゲール",
    "rarity": "R",
    "type": "回復",
    "direction": "味方兵力回復＋味方数に応じた追加回復",
    "cost": 3,
    "attack": 2,
    "defense": 4,
    "troop": 7,
    "skillName": "灯りの看護",
    "skillText": "登場時、味方１体の兵力を２回復する（上限まで）。",
    "traitName": "献身の心",
    "traitText": "登場時、他の味方が２体以上いるなら、さらに味方１体の兵力を１回復する。",
    "title": "灯りと献身で命を支える看護者",
    "quote": "この灯りで、希望を届けよう！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": "能力の方向性は既存効果文の要約",
    "sourceRow": 111
  },
  {
    "id": "R44",
    "name": "マリー・キュリー",
    "rarity": "R",
    "type": "科学",
    "direction": "エネルギー獲得＋自己防御強化",
    "cost": 3,
    "attack": 2,
    "defense": 4,
    "troop": 6,
    "skillName": "科学の探究",
    "skillText": "登場時、自分のエネルギーを１増やす。",
    "traitName": "研究の積み重ね",
    "traitText": "自分の手札が４枚以上ある間、このカードの防御力＋１。",
    "title": "見えない力を探究する科学者",
    "quote": "探究の光で、未知への扉を！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": "能力の方向性は既存効果文の要約。背景英字を除去した修正版が最終版",
    "sourceRow": 112
  },
  {
    "id": "R45",
    "name": "野口英世",
    "rarity": "R",
    "type": "回復・研究",
    "direction": "味方兵力回復＋手札交換",
    "cost": 3,
    "attack": 2,
    "defense": 4,
    "troop": 7,
    "skillName": "研究の成果",
    "skillText": "登場時、味方１体の兵力を２回復する（上限まで）。",
    "traitName": "探究する心",
    "traitText": "登場時、手札が３枚以下なら、カードを１枚引き、その後１枚捨てる。",
    "title": "研究への情熱を貫く医学者",
    "quote": "研究を重ね、命の未来へ！",
    "imageStatus": "生成完了",
    "settingStatus": "仮設定・バランス未検証",
    "notes": "能力の方向性は既存効果文の要約",
    "sourceRow": 113
  }
];
