/* 自動効果と選択待ちを含む、JSON保存可能な対戦状態。 */
(function(root){
 'use strict';
 const G=root.Game,clone=G.clone,card=G.card;
 const defaults={...G.defaults,initialHandMode:'random',drawMode:'random',sound:true,effects:true,volume:70};
 function settings(input){const s=G.settings({...defaults,...input});for(const k of ['initialHandMode','drawMode'])check(['random','manual'].includes(s[k]),'選択方法が不正です');check(Number.isInteger(s.volume)&&s.volume>=0&&s.volume<=100,'音量は0～100です');return s;}
 const durationName=m=>m.until?.event==='end'&&m.duration==='THIS_TURN'?'このターン終了まで':m.until?`プレイヤー${m.until.p?'B':'A'}の${m.until.count}回目のターン${m.until.event==='start'?'開始':'終了'}まで`:'場にいる間';
 function normalize(c){if(c.statsVersion===3)return;const raw=card(c.id);c.permanent={attack:(c.baseAttack??raw.attack)-raw.attack,defense:(c.baseDefense??raw.defense)-raw.defense,maxTroop:(c.maxTroop??raw.troop)-raw.troop};c.baseAttack=raw.attack;c.baseDefense=raw.defense;c.baseMaxTroop=raw.troop;c.modifiers ||= [];c.statsVersion=3;for(const m of c.modifiers)m.duration ||= m.until?(m.until.event==='end'?'THIS_TURN':'UNTIL_NEXT_TURN'):'PERMANENT';}
 function addModifier(g,c,m){m.duration ||= m.until?(m.until.event==='end'&&m.until.p===g.active&&m.until.count===g.players[g.active].turns?'THIS_TURN':'UNTIL_NEXT_TURN'):'PERMANENT';c.modifiers.push(m);recompute(g);}

 const check=(ok,msg)=>{if(!ok)throw Error(msg);};
 function meta(id,slot,g){const c=card(id),a=root.CARD_AUTOMATION[id]?.[slot],base=a?.sourceText===c[slot+'Text']&&a?.sourceName===c[slot+'Name']?a:{trigger:'entry',automationType:'MANUAL',sourceText:c[slot+'Text'],sourceName:c[slot+'Name'],reason:'原文が更新されたため自動処理の再確認が必要です。'};return root.SkillPresets?root.SkillPresets.metadata(g,id,slot,base):base;}
 function processingType(id,g){const types=['skill','trait'].map(slot=>meta(id,slot,g).automationType);return types.includes('MANUAL')?'MANUAL':types.includes('PRESET')?'PRESET':'AUTO';}
 function automationType(id){const types=['skill','trait'].map(s=>meta(id,s).automationType);return types.includes('MANUAL')?'MANUAL':types.includes('SELECT')?'SELECT':'AUTO';}
 function random(){if(root.crypto?.getRandomValues){const n=new Uint32Array(1);root.crypto.getRandomValues(n);return n[0]/4294967296;}return Math.random();}
 function shuffle(ids,rng=random){const a=[...ids];for(let i=a.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
 function unit(id){const c={...G.unit(id),baseAttack:card(id).attack,baseDefense:card(id).defense,modifiers:[],manualFlags:{cannotAttack:false,skillDisabled:false,traitDisabled:false},usage:{skill:{},trait:{}},entrySkillResolved:false,skillUsedThisTurn:false,skillUsedThisGame:false};normalize(c);return c;}
 const log=(g,text)=>{g.log.push({at:new Date().toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit',second:'2-digit'}),text});g.log=g.log.slice(-500);};
 function finish(g,winner,reason){g.result={winner,reason};G.settle(g);g.timer.running=false;g.timer.at=null;g.pending=[];g.handoff=null;}
 function lifeCheck(g){const a=g.players[0].life<=0,b=g.players[1].life<=0;if(a||b)finish(g,a&&b?null:a?1:0,'ライフが0になりました');}
 function condition(g,p,c,test='always'){
  const own=g.players[p],enemy=g.players[1-p],others=own.field.filter(x=>x!==c&&x.troop>0);let m;
  if(m=test.match(/^hand(GE|LE)(\d+)$/))return m[1]==='GE'?own.hand.length>=+m[2]:own.hand.length<=+m[2];
  if(m=test.match(/^troopLE(\d+)$/))return c.troop<=+m[1];
  return ({always:true,hasOther:others.length>0,twoOthers:others.length>=2,alone:others.length===0,fewerAllies:own.field.length<enemy.field.length,lessLife:own.life<enemy.life,full:c?.troop===c?.maxTroop,initialFull:c&&c.troop===card(c.id).troop,cheapOther:others.some(x=>card(x.id).cost<=3),cheapAlly:own.field.some(x=>card(x.id).cost<=3),second:p!==g.first,oneEnemy:enemy.field.length===1,enemyTurn:g.active!==p,entryTurn:!!c?.summonedThisTurn&&g.active===p,lostTroop:c&&c.troop<c.maxTroop,debuffEnemy:enemy.field.some(x=>x.attack<card(x.id).attack)})[test]===true;
 }
 function targets(g,p,c,target){const own=g.players[p].field,enemy=g.players[1-p].field;return ({self:c?[c]:[],allies:own,ally:own,otherAlly:own.filter(x=>x!==c),otherAllies:own.filter(x=>x!==c),enemies:enemy,enemy,alliesSelect:own,woundedAllies:own.filter(x=>x.troop<=card(x.id).troop/2)})[target]||[];}
 function value(g,p,c,v){if(typeof v==='number')return v;if(v.lostPer)return Math.min(v.max,Math.floor((c.maxTroop-c.troop)/v.lostPer));if(v.perOther)return Math.min(v.max,(g.players[p].field.length-1)*v.perOther);if(v.troopGE)return c.troop>=v.troopGE?v.value:0;if(v.troopLE)return c.troop<=v.troopLE?v.value:0;return 0;}
 function recompute(g){
  for(const p of g.players)for(const c of p.field)normalize(c);
  for(const p of g.players)for(const c of p.field){c.attack=c.baseAttack+c.permanent.attack;c.defense=c.baseDefense+c.permanent.defense;c.maxTroop=c.baseMaxTroop+c.permanent.maxTroop;c.reduction=0;c.pierce=0;for(const f of ['cannotAttack','skillDisabled','traitDisabled'])c[f]=!!c.manualFlags[f]||c.modifiers.some(m=>m.flags?.includes(f));for(const m of c.modifiers){c.attack+=m.stats?.attack||0;c.defense+=m.stats?.defense||0;c.maxTroop+=m.stats?.maxTroop||0;}}
  for(let p=0;p<2;p++)for(const c of g.players[p].field)for(const slot of ['skill','trait']){const a=meta(c.id,slot,g);if(a.trigger!=='passive')continue;const active=!c[slot+'Disabled']&&condition(g,p,c,a.condition),ts=active?targets(g,p,c,a.target):[],stats={};for(const k of ['attack','defense'])if(a.stats?.[k]!==undefined)stats[k]=value(g,p,c,a.stats[k]);const signature=active?JSON.stringify({targets:ts.map(x=>x.id),stats,reduction:a.reduction,pierce:a.pierce,firstDiscount:a.firstDiscount}):'';c.passiveState ||= {};if(c.passiveState[slot]!==signature&&(signature||c.passiveState[slot]))log(g,card(c.id).name+'「'+a.sourceName+'」継続効果'+(active?'が発動・更新':'が終了')+(active&&Object.keys(stats).length?'／'+Object.entries(stats).map(([k,n])=>({attack:'攻撃力',defense:'防御力'}[k])+` ${n>=0?'+':''}${n}`).join('・'):''));c.passiveState[slot]=signature;if(!active)continue;for(const t of ts)for(const [k,n] of Object.entries(stats))t[k]+=n;c.reduction+=a.reduction||0;c.pierce+=a.pierce||0;}
  for(const p of g.players)for(const c of p.field){c.attack=Math.max(0,c.attack);c.defense=Math.max(0,c.defense);c.maxTroop=Math.max(1,c.maxTroop);c.troop=Math.min(c.troop,c.maxTroop);}
 }
 function expiry(g,p,d){if(!d||d==='IMMEDIATE'||d==='PERMANENT')return null;if(d==='THIS_TURN')d='turnEnd';if(d==='UNTIL_NEXT_TURN')d='nextOwnStart';if(d==='turnEnd')return {event:'end',p:g.active,count:g.players[g.active].turns};if(d==='nextOwnStart')return {event:'start',p,count:g.players[p].turns+1};if(d==='nextEnemyEnd')return {event:'end',p:1-p,count:g.players[1-p].turns+(g.active===p?1:0)};throw Error('不明な期限');}
 function expire(g,event,p){expireResources(g,event,p);const due=m=>m.until&&m.until.event===event&&m.until.p===p&&m.until.count<=g.players[p].turns;for(const pl of g.players){pl.discounts=pl.discounts.filter(m=>!due(m));for(const c of pl.field){for(const m of [...c.modifiers].filter(due)){const old={attack:c.attack,defense:c.defense,maxTroop:c.maxTroop};c.modifiers=c.modifiers.filter(x=>x!==m);recompute(g);log(g,card(c.id).name+'「'+(m.name||'一時補正')+'」の効果終了／'+Object.keys(m.stats||{}).map(k=>({attack:'攻撃力',defense:'防御力',maxTroop:'最大兵力'}[k])+` ${old[k]} → ${c[k]}`).join('・')+(m.flags?'／一時状態を解除':'')+(m.extraAttacks?'／追加攻撃権を解除':''));}}}recompute(g);}
 function draw(g,p,n,label='自動ドロー',normal=false){const pl=g.players[p],old=pl.hand.length;let count=0;while(count<n&&pl.deck.length){const i=normal?Math.floor(random()*pl.deck.length):0;pl.hand.push(pl.deck.splice(i,1)[0]);count++;}if(count)log(g,pl.name+`：カードを${count}枚${label}／手札 ${old} → ${pl.hand.length}`);if(count<n&&!pl.emptyNotified){pl.emptyNotified=true;g.notice='山札がありません。ドローを行わずゲームを続けます。';log(g,pl.name+'：'+g.notice);}recompute(g);}
 function unused(g,c,slot,a){const u=c.usage[slot];return !(a.limit==='game'&&u.game||a.limit==='turn'&&u.turn===g.turn||a.trigger==='entry'&&u.entry||a.trigger==='turnStart'&&u.start===g.turn||a.cap&&u.count>=a.cap);}
 function mark(g,c,slot,a){const u=c.usage[slot];if(a.trigger==='entry'){u.entry=true;c.entrySkillResolved=true;}if(a.trigger==='turnStart')u.start=g.turn;if(a.limit==='game'&&!(a.trigger==='entry'&&a.followup)){u.game=true;c.skillUsedThisGame=true;}u.turn=g.turn;u.count=(u.count||0)+1;c.skillUsedThisTurn=true;}
 function trigger(g,p,c,event){for(const slot of ['skill','trait']){const a=meta(c.id,slot,g);if(a.trigger!==event||!unused(g,c,slot,a)||c[slot+'Disabled']||!condition(g,p,c,a.condition))continue;mark(g,c,slot,a);const source={owner:p,sourceId:c.id,slot,name:a.sourceName,text:a.sourceText};if(a.automationType==='MANUAL')g.pending.push({...source,op:'manual',reason:a.reason,chooser:p});else{log(g,card(c.id).name+'「'+a.sourceName+'」'+(a.automationType==='AUTO'?'自動発動':'発動'));g.pending.push(...(a.effects||[]).map(e=>({...source,...clone(e)})));}}}
 function defeated(g){const dead=[];for(let p=0;p<2;p++)for(const c of g.players[p].field)if(c.troop<=0){const a=meta(c.id,'skill',g);if(a.trigger==='beforeDeath'&&!c.skillDisabled&&unused(g,c,'skill',a)){mark(g,c,'skill',a);c.troop=1;log(g,card(c.id).name+'「'+a.sourceName+'」自動発動：兵力1で残る（1試合に1回）');}else dead.push({p,c});}
  let loss=0;for(const {p,c} of dead){const pl=g.players[p],cost=card(c.id).cost,n=cost>=5?2:cost>=1?1:0,old=pl.life;pl.field=pl.field.filter(x=>x!==c);pl.trash.push(c.id);pl.life=Math.max(0,old-n);log(g,card(c.id).name+` 撃破／トラッシュへ移動／元コスト${cost}のためライフ -${n}／${pl.name} ライフ ${old} → ${pl.life}`);if(p!==g.active)loss+=n;}
  if(g.phase==='attack'&&g.enemyAtStart&&!g.players[1-g.active].field.length){g.phase='ended';g.notice=`敵陣を突破しました！ 撃破ダメージ：ライフ -${loss}。相手の場が空になったため、このターンの攻撃フェイズを終了します。`;log(g,g.notice);}recompute(g);lifeCheck(g);return dead;
 }
 function apply(g,e,selected){const p=e.owner,pl=g.players[p],c=pl.field.find(c=>c.id===e.sourceId),until=expiry(g,p,e.duration);let ts=targets(g,p,c,e.target);if(selected)ts=ts.filter(c=>selected.includes(c.id));
  switch(e.op){
   case 'draw':draw(g,p,e.n);break;
   case 'energy':{const old=pl.energy;pl.energy=Math.min(g.rules.maxEnergy,old+e.n);log(g,pl.name+` エネルギー ${old} → ${pl.energy}`);break;}
   case 'life':{const old=pl.life;pl.life=g.rules.overheal?old+e.n:Math.min(g.rules.life,old+e.n);log(g,pl.name+` ライフ ${old} → ${pl.life}`);break;}
   case 'discount':pl.discounts.push({n:e.n,min:e.min,until});log(g,'次に出すカードのコスト -'+e.n);break;
   case 'damage':for(const t of ts){const old=t.troop,n=Math.max(0,e.n-(t.reduction||0));t.troop=Math.max(0,old-n);log(g,card(t.id).name+` 兵力 ${old} → ${t.troop}（${n}ダメージ）`);}break;
   case 'heal':case 'healCleanse':for(const t of ts){const old=t.troop,cap=e.initialCap?Math.min(t.maxTroop,card(t.id).troop):t.maxTroop;t.troop=Math.max(old,Math.min(cap,old+e.n));if(e.op==='healCleanse'){for(const k of ['cannotAttack','skillDisabled','traitDisabled'])t.manualFlags[k]=false;t.modifiers=t.modifiers.filter(m=>!m.flags);}log(g,card(t.id).name+` 兵力 ${old} → ${t.troop}`+(e.op==='healCleanse'?'／状態異常を解除':''));}break;
   case 'grow':for(const t of ts){t.permanent.maxTroop+=e.n;t.troop+=e.n;log(g,card(t.id).name+` 最大兵力と現在兵力 +${e.n}`);}break;
   case 'buff':for(const t of ts){const stats=clone(e.stats);if(e.targetCap){const amount=t.modifiers.filter(m=>m.source===e.sourceId&&m.slot===e.slot).reduce((n,m)=>n+(m.stats?.attack||0),0);stats.attack=Math.min(stats.attack,Math.max(0,e.targetCap-amount));}const before={attack:t.attack,defense:t.defense};addModifier(g,t,{stats,until,source:e.sourceId,slot:e.slot,name:e.name});log(g,card(t.id).name+'「'+e.name+'」／'+Object.keys(stats).map(k=>`${before[k]} → ${t[k]}`).join('・')+'／有効期限：'+durationName(t.modifiers.at(-1)));log(g,card(t.id).name+' '+Object.entries(stats).map(([k,n])=>({attack:'攻撃力',defense:'防御力'}[k])+` ${n>=0?'+':''}${n}`).join('／'));}break;
   case 'flags':for(const t of ts){addModifier(g,t,{flags:e.flags,until,source:e.sourceId,slot:e.slot,name:e.name});log(g,card(t.id).name+'：'+e.flags.map(f=>({cannotAttack:'攻撃不能',skillDisabled:'スキル無効',traitDisabled:'特性無効'}[f])).join('・'));}break;
  }
  const dead=defeated(g);if(c&&!g.result)for(const d of dead)if(d.p!==p)trigger(g,p,c,'kill');
 }
 function options(g,e){if(e.op==='presetChoice'){const batch=g.presetBatch,c=g.players[e.owner].field.find(c=>c.id===e.sourceId);return targets(g,e.owner,c,batch.effects[e.index].target).filter(c=>c.troop>0).map(c=>({id:c.id,label:card(c.id).name}));}const pl=g.players[e.owner],c=pl.field.find(c=>c.id===e.sourceId);if(['initialHand','normalDraw'].includes(e.op))return pl.deck.map(id=>({id,label:card(id).name}));if(e.op==='choice')return e.options.map((o,i)=>({id:String(i),label:o.label}));if(e.op==='optionalBottom')return pl.deck.length?[{id:'keep',label:'上に残す'},{id:'bottom',label:'下へ移す'}]:[];let ids;if(e.op==='reorderBottom')ids=e.rest;else if(['reorder','discover'].includes(e.op))ids=pl.deck.slice(0,e.n);else if(e.op==='search')ids=pl.deck.filter(id=>!e.filter?.costLE||card(id).cost<=e.filter.costLE);else if(e.op==='discard')ids=g.players[e.target==='enemyHand'?1-e.owner:e.owner].hand;else ids=targets(g,e.owner,c,e.target).filter(t=>t.troop>0&&(!e.filter?.attackLE||t.attack<=e.filter.attackLE)).map(t=>t.id);return ids.map(id=>({id,label:card(id).name}));}
 const selecting=e=>['ally','otherAlly','enemy','alliesSelect'].includes(e.target)||['presetChoice','initialHand','normalDraw','discard','search','reorder','reorderBottom','discover','optionalBottom','choice'].includes(e.op);
 function pump(g){let n=0;while(g.pending.length&&!g.result){check(++n<500,'効果処理が循環しています');const e=g.pending[0],c=g.players[e.owner].field.find(c=>c.id===e.sourceId);if(e.op==='manual')break;if(e.op==='if'){g.pending.shift();g.pending.unshift(...(condition(g,e.owner,c,e.condition)?e.yes:e.no).map(o=>({...e,...o})));continue;}if(selecting(e)){e.chooser=e.target==='enemyHand'?1-e.owner:e.owner;if(options(g,e).length)break;log(g,'「'+e.name+'」：対象なしのため、この効果を省略');g.pending.shift();continue;}g.pending.shift();apply(g,e);}if(!g.result){const who=g.pending[0]?.chooser??g.active;if(g.viewer!==who){g.viewer=null;g.handoff={player:who,reason:g.initializing?'初期手札の選択':who===g.active?'自分のターンの準備':'手札から捨てるカードを選択'};}}}
 function resolve(g,action){const e=g.pending[0];check(e,'選択待ちの効果がありません');check(g.viewer===e.chooser&&!g.handoff,'端末を渡して準備OKを押してください');if(e.op==='manual'){check(action.type==='manualDone','手動処理の完了を選んでください');g.pending.shift();log(g,card(e.sourceId).name+'「'+e.name+'」手動処理済み');pump(g);return;}
  const ids=action.ids||[action.target],valid=options(g,e).map(o=>o.id);check(new Set(ids).size===ids.length&&ids.every(id=>valid.includes(id)),'対象の選択が不正です');const count=e.op==='initialHand'?g.rules.initialHand:['reorder','reorderBottom'].includes(e.op)?valid.length:e.target==='alliesSelect'?null:1;check(count===null?ids.length>=(e.minSelect??1)&&ids.length<=e.maxSelect:ids.length===count,'対象の枚数を確認してください');g.pending.shift();const pl=g.players[e.owner];
  if(e.op==='presetChoice'){g.presetBatch.selected[e.index]=ids[0];continuePreset(g);return;}
  else if(['initialHand','normalDraw'].includes(e.op)){for(const id of ids){pl.deck.splice(pl.deck.indexOf(id),1);pl.hand.push(id);}log(g,pl.name+'：カードを'+ids.length+'枚'+(e.op==='initialHand'?'初期手札に選びました':'引きました')+'（内容は非公開）');if(e.op==='normalDraw'&&e.turnStart)completeStart(g,e.owner);if(e.op==='initialHand'&&!g.pending.length){g.initializing=false;g.viewer=null;g.handoff={player:g.first,reason:'初期手札の準備完了・試合開始'};return;}}
  else if(e.op==='choice')g.pending.unshift(...e.options[+ids[0]].effects.map(o=>({...e,...o})));
  else if(e.op==='discard'){const target=g.players[e.target==='enemyHand'?1-e.owner:e.owner];target.hand.splice(target.hand.indexOf(ids[0]),1);target.trash.push(ids[0]);log(g,target.name+'：手札を1枚捨てる → '+card(ids[0]).name);}
  else if(e.op==='reorder'){pl.deck.splice(0,ids.length,...ids);log(g,'山札の上'+ids.length+'枚の順序を変更（内容は非公開）');}
  else if(e.op==='optionalBottom'){if(ids[0]==='bottom')pl.deck.push(pl.deck.shift());log(g,'山札の一番上を確認・'+(ids[0]==='bottom'?'下へ移動':'上に残す')+'（内容は非公開）');}
  else if(e.op==='search'){pl.deck.splice(pl.deck.indexOf(ids[0]),1);pl.hand.push(ids[0]);if(e.shuffle)pl.deck=shuffle(pl.deck);log(g,'山札から1枚を公開して手札へ：'+card(ids[0]).name+'／山札をシャッフル');}
  else if(e.op==='discover'){const top=pl.deck.splice(0,e.n);pl.hand.push(ids[0]);const rest=top.filter(id=>id!==ids[0]);pl.deck.push(...rest);if(e.reorderRest&&rest.length>1)g.pending.unshift({...e,op:'reorderBottom',n:rest.length,rest,chooser:e.owner});log(g,'山札の上'+top.length+'枚から1枚を手札へ（内容は非公開）');}
  else if(e.op==='reorderBottom'){pl.deck.splice(pl.deck.length-e.n,e.n,...ids);log(g,'山札の下'+ids.length+'枚の順序を変更（内容は非公開）');}
  else apply(g,e,ids);recompute(g);pump(g);
 }
 function startTurn(g){const p=g.active,pl=g.players[p];g.turn++;pl.turns++;pl.summons=0;pl.hidden=false;g.phase='main';g.enemyAtStart=false;g.notice='準備フェイズ：手札からカードを場に出せます。';for(const c of pl.field){c.summonedThisTurn=false;c.attackedThisTurn=false;c.skillUsedThisTurn=false;}expire(g,'start',p);defeated(g);if(g.result)return;log(g,pl.name+' ターン開始');if(g.rules.drawMode==='manual'&&pl.deck.length){g.pending.push({op:'normalDraw',owner:p,chooser:p,turnStart:true,name:'山札から1枚選んでください'});pump(g);return;}draw(g,p,1,'引きました',g.rules.drawMode==='random');completeStart(g,p);pump(g);}
 function completeStart(g,p){const pl=g.players[p];pl.maxEnergy=pl.turns===1?g.rules.startEnergy:Math.min(g.rules.maxEnergy,pl.maxEnergy+1);pl.energy=pl.maxEnergy;log(g,pl.name+` エネルギー ${pl.energy} / ${pl.maxEnergy}へ回復`);recompute(g);for(const c of pl.field)trigger(g,p,c,'turnStart');}
 function create(decks,rules,seconds,first=0,rng=random){const s=settings({...rules,deckOutLose:false});if(s.skillPresets)s.skillPresets=clone(s.skillPresets);check(decks.length===2&&decks.every(d=>G.validateDeck(d.cards).valid),'正しいデッキを2つ選んでください');check(Number.isFinite(seconds)&&seconds>0&&[0,1].includes(first),'試合設定を確認してください');const g={version:2,first,active:first,viewer:null,handoff:{player:first,reason:'対戦開始'},rules:s,players:decks.map((d,i)=>({name:d.player||`プレイヤー${i?'B':'A'}`,team:d.team||'',deckName:d.name,original:[...d.cards],deck:shuffle(d.cards,rng),hand:[],field:[],trash:[],life:s.life,energy:0,maxEnergy:0,turns:0,summons:0,discounts:[],emptyNotified:false,hidden:false})),stage:'battle',turn:0,phase:'main',enemyAtStart:false,pending:[],result:null,notice:'',timer:{remaining:seconds*1000,running:false,at:null},log:[]};if(s.initialHandMode==='manual'&&s.initialHand>0){g.initializing=true;g.pending=[first,1-first].map(owner=>({op:'initialHand',owner,chooser:owner,name:'初期手札を'+s.initialHand+'枚選んでください'}));}else for(let p=0;p<2;p++)draw(g,p,s.initialHand,'初期配布');return g;}
 function cost(g,p,id){const pl=g.players[p];let n=card(id).cost,min=0;for(const d of pl.discounts){n-=d.n;min=Math.max(min,d.min);}if(pl.summons===0&&pl.hand.length<=3)for(const c of pl.field)if(!c.traitDisabled&&meta(c.id,'trait',g).firstDiscount){n--;min=Math.max(min,1);}return Math.max(min,n);}
 function attackable(g,c){return !g.result&&!g.handoff&&!g.pending.length&&g.phase==='attack'&&c.troop>0&&(!c.attackedThisTurn||c.modifiers.some(m=>m.extraAttacks>0))&&!c.cannotAttack&&(g.rules.summonAttack||!c.summonedThisTurn);}
 function damage(g,a,d){return Math.max(0,Math.max(g.rules.minDamage,a.attack-Math.max(0,d.defense-(a.pierce||0)))-(d.reduction||0));}
 function abilities(g,p,c){return ['skill','trait'].map(slot=>{const a=meta(c.id,slot,g);if(['preset','configuredManual'].includes(a.trigger)){const used=presetUsed(g,p,c.id,slot,a.limit);return {slot,...a,used,available:!g.result&&!g.handoff&&!g.pending.length&&g.active===p&&g.viewer===p&&!c[slot+'Disabled']&&!used};}const u=c.usage[slot],pending=g.pending.some(e=>e.sourceId===c.id&&e.owner===p&&e.slot===slot),reactive=a.trigger==='combat'&&g.phase==='attack'&&g.players[1-p].field.some(x=>x.troop>0),followup=!!(a.followup==='kill'&&u.killAvailable);return {slot,...a,used:!!u.entry||u.turn===g.turn||!!u.game,available:!g.result&&!c[slot+'Disabled']&&condition(g,p,c,a.condition)&&(pending||a.trigger==='passive'||a.automationType==='MANUAL'&&(reactive||followup)&&unused(g,c,slot,{...a,trigger:'combat'}))};});}

 function presetUsed(g,p,id,slot,limit){const u=g.presetUsage?.[p]?.[id+':'+slot];return !!u&&(limit==='game'||limit==='turn'&&u.turn===g.players[p].turns);}
 function markPreset(g,p,id,slot){g.presetUsage ||= [{},{}];g.presetUsage[p][id+':'+slot]={turn:g.players[p].turns};}
 function beginPreset(g,p,c,slot,a){for(const e of a.effects)if(!['ownPlayer','enemyPlayer'].includes(e.target))check(targets(g,p,c,e.target).some(t=>t.troop>0),'対象となる場のカードがありません');markPreset(g,p,c.id,slot);g.presetBatch={owner:p,sourceId:c.id,slot,name:a.sourceName,text:a.sourceText,effects:clone(a.effects),selected:{}};continuePreset(g);}
 function continuePreset(g){const b=g.presetBatch;for(let i=0;i<b.effects.length;i++)if(['ally','enemy'].includes(b.effects[i].target)&&!b.selected[i]){g.pending.unshift({op:'presetChoice',owner:b.owner,chooser:b.owner,sourceId:b.sourceId,slot:b.slot,name:b.name,text:'対象を選んでください：効果'+(i+1),index:i});pump(g);return;}applyPreset(g,b);delete g.presetBatch;if(!g.result)pump(g);}
 function applyPreset(g,b){const p=b.owner,c=g.players[p].field.find(c=>c.id===b.sourceId);check(c,'発動元が場にありません');log(g,card(c.id).name+'「'+b.name+'」スキル発動（PRESET）');for(let i=0;i<b.effects.length;i++){const e=b.effects[i],player=['ownPlayer','enemyPlayer'].includes(e.target),ts=player?[g.players[e.target==='ownPlayer'?p:1-p]]:targets(g,p,c,e.target).filter(t=>!b.selected[i]||t.id===b.selected[i]);for(const t of ts){const old=t[e.stat],until=expiry(g,p,e.duration),name=player?t.name:card(t.id).name;if(['attack','defense','maxTroop'].includes(e.stat)){t.modifiers.push({stats:{[e.stat]:e.delta},until,duration:e.duration,name:b.name,source:b.sourceId,slot:b.slot,preset:true});recompute(g);}else{const cap=e.stat==='troop'?t.maxTroop:e.stat==='energy'?g.rules.maxEnergy:g.rules.overheal?Infinity:g.rules.life;t[e.stat]=Math.max(0,Math.min(cap,old+e.delta));if(until){t.resourceModifiers ||= [];t.resourceModifiers.push({stat:e.stat,delta:t[e.stat]-old,until,duration:e.duration,name:b.name});}}log(g,name+' '+root.SkillPresets.stats[e.stat]+` ${e.delta>0?'+':''}${e.delta}／${old} → ${t[e.stat]}／有効期限：`+root.SkillPresets.durations[e.duration]);}}const dead=defeated(g);if(!g.result)for(const d of dead)if(d.p!==p)trigger(g,p,c,'kill');}
 function expireResources(g,event,p){for(const pl of g.players)for(const t of [pl,...pl.field]){const list=t.resourceModifiers||[];for(const m of list.filter(m=>m.until.event===event&&m.until.p===p&&m.until.count<=g.players[p].turns)){const old=t[m.stat],cap=m.stat==='troop'?t.maxTroop:m.stat==='energy'?g.rules.maxEnergy:g.rules.overheal?Infinity:g.rules.life;t[m.stat]=Math.max(0,Math.min(cap,old-m.delta));log(g,(t.id?card(t.id).name:t.name)+'「'+m.name+'」スキル効果終了／'+root.SkillPresets.stats[m.stat]+` ${old} → ${t[m.stat]}`);t.resourceModifiers=t.resourceModifiers.filter(x=>x!==m);}}}
 function lock(g){if(!g||g.result)return g;const c=clone(g);recompute(c);c.viewer=null;c.handoff={player:c.pending[0]?.chooser??c.active,reason:'試合を再開'};return c;}
 function dispatch(original,action){const g=clone(original);recompute(g);G.settle(g);check(!g.result,'この試合は終了しています。Undoで修正できます');const p=action.player??g.active,pl=g.players[p];check(pl,'不明なプレイヤーです');const field=()=>{const c=pl.field.find(c=>c.id===action.id);check(c,'場のカードがありません');return c;};const own=()=>check(p===g.active&&g.viewer===g.active,'自分のターンに操作してください');const free=()=>check(!g.pending.length&&!g.handoff,'効果の選択・交代を先に完了してください');const main=()=>{own();free();check(g.phase==='main','準備フェイズで操作してください');};
  if(g.handoff)check(['ready','timer','timeout'].includes(action.type),'準備OKを押してください');if(g.pending.length)check(['select','manualDone','ready','timer','timeout',...(g.pending[0].op==='manual'?['adjust','flag','note','life','energy','trash','draw']:[])].includes(action.type),'効果の選択を先に完了してください');
  switch(action.type){
   case 'ready':check(g.handoff,'交代画面ではありません');g.viewer=g.handoff.player;g.handoff=null;if(g.turn===0&&!g.initializing){g.timer.running=true;g.timer.at=Date.now();startTurn(g);}else pump(g);break;
   case 'select':case 'manualDone':resolve(g,action);break;
   case 'summon':{main();const i=pl.hand.indexOf(action.id);check(i>=0,'手札にないカードです');check(pl.field.length<g.rules.fieldLimit,'場は最大'+g.rules.fieldLimit+'枚です');const n=action.cost??cost(g,p,action.id);check(Number.isInteger(n)&&n>=0&&pl.energy>=n,'エネルギー不足、またはコストが不正です');const old=pl.energy;pl.energy-=n;pl.hand.splice(i,1);pl.discounts=[];pl.summons++;const c=unit(action.id);pl.field.push(c);recompute(g);log(g,card(c.id).name+`を場に召喚／エネルギー ${old} → ${pl.energy}`);trigger(g,p,c,'entry');pump(g);break;}
   case 'draw':own();draw(g,p,1,'追加ドロー（手動）');break;
   case 'attackPhase':main();g.phase='attack';g.enemyAtStart=g.players[1-p].field.length>0;g.notice=g.enemyAtStart?'相手の場を攻撃できます。敵陣突破で攻撃終了です。':'相手のライフへ直接攻撃できます。';log(g,'攻撃フェイズ開始／敵陣'+g.players[1-p].field.length+'枚');break;
   case 'attack':{own();free();const a=field();check(attackable(g,a),'このカードは今、攻撃できません');const enemy=g.players[1-p];if(a.attackedThisTurn){const extra=a.modifiers.find(m=>m.extraAttacks>0);extra.extraAttacks--;}a.attackedThisTurn=true;if(action.target==='life'){check(!g.enemyAtStart&&!enemy.field.length,'このフェイズは直接攻撃できません');const old=enemy.life;enemy.life=Math.max(0,old-a.attack);log(g,card(a.id).name+` → ${enemy.name} ライフ ${old} → ${enemy.life}`);lifeCheck(g);}else{const d=enemy.field.find(c=>c.id===action.target);check(d&&d.troop>0,'対象がありません');const old=d.troop,n=damage(g,a,d);d.troop=Math.max(0,old-n);log(g,card(a.id).name+' → '+card(d.id).name+` ${n}ダメージ／兵力 ${old} → ${d.troop}`);const dead=defeated(g);if(!g.result){if(dead.some(x=>x.c===d)){trigger(g,p,a,'kill');trigger(g,p,a,'battleKill');for(const slot of ['skill','trait'])if(meta(a.id,slot,g).followup==='kill')a.usage[slot].killAvailable=true;}else trigger(g,1-p,d,'survived');trigger(g,p,a,'survived');}}if(!g.result){trigger(g,p,a,'afterAttack');pump(g);}break;}
   case 'endTurn':own();free();log(g,pl.name+' ターン終了');expire(g,'end',p);defeated(g);if(g.result)break;g.active=1-p;g.viewer=null;g.handoff={player:g.active,reason:'ターン交代'};startTurn(g);break;
   case 'adjust':{const c=field(),key=action.key;check(['attack','defense','troop','maxTroop'].includes(key),'変更項目が不正です');const old=c[key];check(action.reset||Number.isInteger(action.delta),'整数を入力してください');if(key==='troop')c.troop=Math.max(0,c.troop+action.delta);else if(action.reset){c.permanent[key]=0;c.modifiers=c.modifiers.filter(m=>!m.manual||!m.stats?.[key]);}else{const duration=action.duration||'PERMANENT';if(duration==='PERMANENT')c.permanent[key]+=action.delta;else addModifier(g,c,{stats:{[key]:action.delta},until:expiry(g,p,duration),duration,manual:true,name:action.name||'手動補正'});}recompute(g);log(g,card(c.id).name+' '+({attack:'攻撃力',defense:'防御力',troop:'兵力',maxTroop:'最大兵力'}[key])+` ${old} → ${c[key]}`+'／有効期限：'+(key==='troop'?'兵力の増減':action.duration==='THIS_TURN'?'このターン終了まで':action.duration==='UNTIL_NEXT_TURN'?'次の自分のターン開始まで':'場にいる間'));defeated(g);pump(g);break;}
   case 'flag':{const c=field();check(['cannotAttack','skillDisabled','traitDisabled','attackedThisTurn'].includes(action.key),'不明な状態です');if(action.key==='attackedThisTurn'){if(!action.value)addModifier(g,c,{extraAttacks:1,duration:'THIS_TURN',until:expiry(g,p,'THIS_TURN'),name:'追加攻撃権'});else c.attackedThisTurn=true;}else if(!action.value){c.manualFlags[action.key]=false;c.modifiers=c.modifiers.filter(m=>!m.manual||!m.flags?.includes(action.key));}else if(!action.duration||action.duration==='PERMANENT')c.manualFlags[action.key]=true;else addModifier(g,c,{flags:[action.key],duration:action.duration,until:expiry(g,p,action.duration),manual:true,name:'手動状態補正'});recompute(g);log(g,card(c.id).name+'：手動状態変更／'+(action.duration||'THIS_TURN'));break;}
   case 'note':field().note=String(action.value).slice(0,1000);log(g,card(action.id).name+'：効果メモ保存');break;
   case 'life':case 'energy':{check(Number.isInteger(action.delta),'整数を入力してください');const k=action.type,old=pl[k];pl[k]=Math.max(0,old+action.delta);if(k==='energy')pl[k]=Math.min(g.rules.maxEnergy,pl[k]);if(k==='life'&&!g.rules.overheal)pl[k]=Math.min(g.rules.life,pl[k]);log(g,pl.name+' '+(k==='life'?'ライフ':'エネルギー')+` ${old} → ${pl[k]}`);lifeCheck(g);recompute(g);break;}
   case 'trash':{const zone=action.zone||'field';check(['hand','field'].includes(zone),'移動元が不正です');if(zone==='hand')check(p===g.viewer,'相手の手札は操作できません');const i=pl[zone].findIndex(c=>(typeof c==='string'?c:c.id)===action.id);check(i>=0,'カードがありません');const c=pl[zone][i];if(zone==='field'&&c.troop<=0)defeated(g);else{pl[zone].splice(i,1);pl.trash.push(action.id);log(g,card(action.id).name+'：手動でトラッシュへ（撃破ではないためライフ減少なし）');defeated(g);}pump(g);break;}
   case 'hide':check(p===g.viewer,'相手の手札は表示できません');pl.hidden=!pl.hidden;break;
   case 'activate':{free();const c=field(),a=meta(c.id,action.slot,g);if(['preset','configuredManual'].includes(a.trigger)){own();check(!c[action.slot+'Disabled']&&!presetUsed(g,p,c.id,action.slot,a.limit),'この能力は無効、または発動済みです');if(a.trigger==='preset'){beginPreset(g,p,c,action.slot,a);break;}markPreset(g,p,c.id,action.slot);g.pending.push({op:'manual',owner:p,chooser:p,sourceId:c.id,slot:action.slot,name:a.sourceName,text:a.sourceText,reason:a.reason});pump(g);break;}const view=abilities(g,p,c).find(a=>a.slot===action.slot);check(view?.available&&a.automationType==='MANUAL','発動条件を満たしていないか、発動済みです');mark(g,c,action.slot,{...a,trigger:'combat'});c.usage[action.slot].killAvailable=false;g.pending.push({op:'manual',owner:p,chooser:p,sourceId:c.id,slot:action.slot,name:a.sourceName,text:a.sourceText,reason:a.reason});pump(g);break;}
   case 'timer':g.timer.running=!g.timer.running;g.timer.at=g.timer.running?Date.now():null;log(g,g.timer.running?'タイマー再開':'タイマー一時停止');break;
   case 'timeout':{check(G.remaining(g)<=0,'まだ時間が残っています');const score=p=>[p.life,p.field.reduce((n,c)=>n+c.troop,0),p.hand.length],a=score(g.players[0]),b=score(g.players[1]);let winner=null,reason='引き分け／代表カード決戦';for(let i=0;i<3;i++)if(a[i]!==b[i]){winner=a[i]>b[i]?0:1;reason=['ライフ','場の兵力','手札枚数'][i]+'による時間切れ判定';break;}finish(g,winner,reason);g.result.scores=[a,b];log(g,reason);break;}
   default:throw Error('不明な操作です');
  }recompute(g);return g;
 }
 root.Game={...G,defaults,settings,durationName,normalize,metadata:meta,processingType,automationType,shuffle,unit,create,recompute,condition,options,abilities,cost,attackable,damage,dispatch,lock};
})(globalThis);
