/* ユーザー提供の画像とMP3を同じ場面で再生。演出は保存状態を書き換えない。 */
(function(root){
 'use strict';
 let prefs=()=>({sound:true,effects:true,volume:70}),context=null,nodes=new Set(),timers=new Set(),overlays=new Set(),busy=false,epoch=0;
 const later=(fn,ms)=>{const t=setTimeout(()=>{timers.delete(t);fn();},ms);timers.add(t);return t;};
 function unlock(){try{const Audio=root.AudioContext||root.webkitAudioContext;if(!Audio)return;if(!context)context=new Audio();preload();for(const key of Object.keys(media))prepare(key).catch(()=>{});if(context.state==='suspended')return context.resume().catch(()=>{});}catch{}}
 function muteIfNeeded(){if(!prefs().sound||prefs().volume===0)for(const n of nodes){try{n.stop();}catch{}}}
 const media={start:{image:'assets/images/start.png',audio:'assets/audio/start.mp3',ms:2600},attack:{image:'assets/images/attack.png',audio:'assets/audio/attack.mp3',ms:400},trash:{image:'assets/images/trash.png',audio:'assets/audio/trash.mp3',ms:650},end:{image:'assets/images/end.png',audio:'assets/audio/end.mp3',ms:2600}};
 const cache={};let sceneToken=0,lockToken=0;
 function preload(){for(const [key,m] of Object.entries(media)){if(cache[key])continue;const img=new Image();const imageReady=new Promise(resolve=>{img.onload=img.onerror=()=>resolve();});img.src=m.image;const bytes=fetch(m.audio).then(r=>{if(!r.ok)throw Error('音声を取得できません');return r.arrayBuffer();}).catch(()=>null);cache[key]={img,imageReady,bytes};}}
 async function prepare(key){preload();const c=cache[key];await c.imageReady;if(context&&!c.buffer){c.decoding ||= c.bytes.then(b=>b?context.decodeAudioData(b.slice(0)):null).catch(()=>null);c.buffer=await c.decoding;}}
 function sound(kind){const key=({conch:'start',drum:'end',victory:'end'})[kind]||kind;const buffer=cache[key]?.buffer;if(!prefs().sound||!prefs().volume||!context||context.state!=='running'||!buffer)return;try{const source=context.createBufferSource(),gain=context.createGain(),now=context.currentTime,duration=Math.min(buffer.duration,media[key].ms/1000);source.buffer=buffer;gain.gain.setValueAtTime(prefs().volume/100,now);gain.gain.setValueAtTime(prefs().volume/100,now+Math.max(0,duration-.05));gain.gain.linearRampToValueAtTime(0,now+duration);source.connect(gain);gain.connect(context.destination);source.start(now);source.stop(now+duration);nodes.add(source);source.onended=()=>{nodes.delete(source);source.disconnect();gain.disconnect();};}catch{}}
 function stage(key,text,confetti){const m=media[key],el=banner(text,m.ms,confetti);el.dataset.scene=key;el.classList.add('fx-scene');const image=cache[key]?.img;if(image?.complete&&image.naturalWidth){const copy=image.cloneNode();copy.alt='';copy.className='fx-scene-image';el.prepend(copy);}return el;}
 async function scenes(items){const token=++sceneToken;for(const n of nodes){try{n.stop();}catch{}}if(prefs().effects)hold(items.reduce((n,i)=>n+media[i.key].ms,0)+1200);for(const item of items){await Promise.race([prepare(item.key),new Promise(r=>setTimeout(r,1000))]);if(token!==sceneToken||document.hidden)return;if(prefs().effects)stage(item.key,item.text,item.confetti);sound(item.key);await new Promise(r=>setTimeout(r,media[item.key].ms));if(token!==sceneToken)return;}release();}
 function release(){busy=false;document.body.classList.remove('fx-busy');for(const b of document.querySelectorAll('[data-fx-disabled]')){b.disabled=false;delete b.dataset.fxDisabled;}}
 function clear(){epoch++;sceneToken++;lockToken++;for(const t of timers)clearTimeout(t);timers.clear();for(const el of overlays)el.remove();overlays.clear();release();for(const n of nodes){try{n.stop();}catch{}}}
 function syncLock(){if(busy)for(const b of document.querySelectorAll('button:not(:disabled)'))if(b.id!=='sound-toggle'){b.dataset.fxDisabled='true';b.disabled=true;}}
 function hold(ms){const token=++lockToken;busy=true;document.body.classList.add('fx-busy');syncLock();later(()=>{if(token===lockToken)release();},ms);}
 function element(cls,text){const e=document.createElement('div');e.className=cls;e.textContent=text;document.body.append(e);overlays.add(e);return e;}
 function banner(text,ms,confetti=false){const e=element('fx-banner','');const caption=document.createElement('div');caption.className='fx-scene-caption';caption.textContent=text;e.append(caption);e.setAttribute('role','status');if(confetti)for(let i=0;i<24;i++){const bit=document.createElement('i');bit.className='confetti';e.append(bit);bit.animate([{transform:`translate(${i*4}vw,-20px) rotate(0deg)`,opacity:1},{transform:`translate(${i*4-8}vw,100vh) rotate(${300+i*20}deg)`,opacity:0}],{duration:1800+i%5*200,delay:i%6*70,fill:'forwards'});}later(()=>{e.remove();overlays.delete(e);},ms);return e;}
 function start(){unlock();scenes([{key:'start',text:'英雄列伝バトル\n神々編\nいざ、開戦！'}]).catch(()=>clear());}
 function capture(g){const found={};if(!g)return found;for(let p=0;p<2;p++)for(const c of g.players[p].field){const el=document.querySelector(`[data-field-player="${p}"][data-field-id="${c.id}"]`);if(el)found[p+':'+c.id]=el.getBoundingClientRect();}return found;}
 function pop(el,text){if(!el)return;const box=el.getBoundingClientRect(),badge=element('fx-number',text);badge.style.left=(box.left+box.width/2)+'px';badge.style.top=(box.top+10)+'px';badge.animate([{transform:'translateY(0)',opacity:1},{transform:'translateY(-45px)',opacity:0}],{duration:650,fill:'forwards'});el.animate([{transform:'translateX(0)',backgroundColor:'#fff'},{transform:'translateX(-5px)',backgroundColor:'#ffcaca'},{transform:'translateX(5px)'},{transform:'translateX(0)'}],{duration:300});later(()=>{badge.remove();overlays.delete(badge);},650);}
 function transition(before,after,action,rects){const sequence=[];if(action.type==='attack')sequence.push({key:'attack',text:'攻撃！'});let killed=false,damaged=false,trashed=false;
  for(let p=0;p<2;p++){const a=before.players[p],b=after.players[p];if(b.trash.length>a.trash.length)trashed=true;for(const c of a.field){const now=b.field.find(x=>x.id===c.id),death=!now&&b.trash.length>a.trash.length&&action.type!=='trash';if(death){killed=true;const raw=Game.card(c.id),loss=raw.cost>=5?2:raw.cost>=1?1:0;if(prefs().effects){const r=rects[p+':'+c.id];if(r){const el=element('fx-defeat',raw.name+' 撃破！\nコスト '+raw.cost+' ／ ライフ −'+loss);el.style.left=r.left+'px';el.style.top=r.top+'px';el.style.width=r.width+'px';const dest=document.querySelector(`[data-action="zone"][data-player="${p}"][data-zone="trash"]`)?.getBoundingClientRect();el.animate([{transform:'translateX(-5px)',opacity:1,backgroundColor:'#ffe6df'},{transform:'translateX(5px)',offset:.15},{transform:`translate(${dest?dest.left-r.left:0}px,${dest?dest.top-r.top:-70}px) scale(.2)`,opacity:0}],{duration:650,fill:'forwards'});later(()=>{el.remove();overlays.delete(el);},650);}}}else if(now&&now.troop<c.troop){damaged=true;if(prefs().effects)pop(document.querySelector(`[data-field-player="${p}"][data-field-id="${c.id}"]`),'-'+(c.troop-now.troop));}}
   if(b.life<a.life){damaged=true;if(prefs().effects)pop(document.querySelector(`[data-life-player="${p}"]`),'-'+(a.life-b.life));}
  }
  if(trashed)sequence.push({key:'trash',text:killed?'撃破！':'トラッシュへ'});if(killed||damaged||action.type==='attack')hold(300);
  if(!before.result&&after.result){const draw=after.result.winner===null,pl=draw?null:after.players[after.result.winner];sequence.push({key:'end',text:draw?'引き分け！\n代表カード決戦へ':'勝負あり！\n'+(pl.team||pl.name)+'\n勝利！',confetti:!draw});}
  if(sequence.length)scenes(sequence).catch(()=>clear());
 }
 const safe=fn=>(...args)=>{try{return fn(...args);}catch{clear();}};
 root.Presentation={configure:fn=>{prefs=fn;preload();},syncLock,unlock,muteIfNeeded,clear,start:safe(start),capture,transition:safe(transition),sound,get busy(){return busy;}};
})(globalThis);
