/* 特殊スキルの設定画面。対戦開始時に設定をスナップショットする。 */
(function(root){
 'use strict';
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const P=root.SkillPresets;let id='SR04',slot='skill',draft=null,message='';
 const read=()=>{const data=Store.read('skill-presets',{});return data&&typeof data==='object'&&!Array.isArray(data)?data:{};};
 const fresh=()=>({target:'self',stat:'attack',delta:2,duration:'THIS_TURN'});
 function load(){const saved=read()[id]?.[slot],base=Game.metadata(id,slot);draft=saved?Game.clone(saved):{type:base.automationType==='MANUAL'?'MANUAL':'AUTO',limit:'turn',effects:[fresh()]};if(!draft.effects?.length)draft.effects=[fresh()];}
 const select=(name,choices,value,extra='')=>`<select name="${name}" ${extra}>${Object.entries(choices).map(([k,v])=>`<option value="${k}" ${k===value?'selected':''}>${esc(v)}</option>`).join('')}</select>`;
 function inner(){if(!draft)load();const raw=Game.card(id),auto=Game.metadata(id,slot).automationType!=='MANUAL';return `<h2>特殊スキル設定</h2><p>紙カードの本文に従って数値処理を設定します。変更は次の試合から有効です。数値で表せない効果はMANUALで裁定してください。</p><form id="preset-form"><div class="form-grid"><label>カード<select id="preset-card">${CARD_DATA.map(c=>`<option value="${c.id}" ${c.id===id?'selected':''}>${c.id} ${esc(c.name)}</option>`).join('')}</select></label><label>設定する能力${select('slot',{skill:'スキル',trait:'特性'},slot,'id="preset-slot"')}</label></div><h3>${esc(raw[slot+'Name'])}</h3><p class="detail-text">${esc(raw[slot+'Text'])}</p><label>スキル処理<select id="preset-type" name="type"><option value="AUTO" ${draft.type==='AUTO'?'selected':''} ${auto?'':'disabled'}>AUTO · 既存の自動処理</option><option value="PRESET" ${draft.type==='PRESET'?'selected':''}>PRESET · 設定した数値処理</option><option value="MANUAL" ${draft.type==='MANUAL'?'selected':''}>MANUAL · 手動裁定</option></select></label>${!auto?'<p class="muted">この能力には確定したAUTO処理がありません。</p>':''}<p class="muted">AUTOは既存の対象選択付き処理も含みます。PRESETは発動条件を確認してから、自分のターンにボタンで発動します。</p>${draft.type!=='AUTO'?`<label>発動回数${select('limit',P.limits,draft.limit)}</label>`:''}${draft.type==='PRESET'?`<p>簡単プリセット（効果1に設定します。対象は自分自身、効果時間は下で変更できます。）</p><div class="preset-quick">${[['attack','攻撃',[1,2,3,-1,-2]],['defense','防御',[1,2,3,-1,-2]],['troop','兵力',[1,2,3]]].flatMap(([stat,label,values])=>values.map(n=>`<button type="button" data-preset-quick="${stat}" data-delta="${n}">${label} ${n>0?'+':''}${n}</button>`)).join('')}</div>${draft.effects.map((e,i)=>`<fieldset class="preset-effect" data-effect-index="${i}"><legend>効果${i+1}</legend><div class="form-grid"><label>対象${select('target',P.targets,e.target)}</label><label>能力${select('stat',P.stats,e.stat)}</label><label>変更値<input name="delta" type="number" min="-999" max="999" step="1" value="${esc(e.delta)}" list="preset-values" required></label><label>効果時間${select('duration',P.durations,e.duration)}</label></div><button type="button" data-preset-remove="${i}" ${draft.effects.length===1?'disabled':''}>この効果を削除</button></fieldset>`).join('')}<datalist id="preset-values">${[-5,-4,-3,-2,-1,1,2,3,4,5].map(n=>`<option value="${n}">${n>0?'+':''}${n}</option>`).join('')}</datalist><button type="button" id="preset-add" ${draft.effects.length>=3?'disabled':''}>＋ 効果を追加（最大3件）</button><p class="muted">ライフ・エネルギーはプレイヤー、その他はカードが対象です。兵力・ライフ・エネルギーの期限付き変更は、期限に実際の増減分を逆算して解除します（上限・下限あり）。即時は自動で戻しません。</p>`:''}<div class="row"><button type="submit" class="primary">この能力の設定を保存</button><button type="button" id="preset-original">この能力を標準に戻す</button></div><p id="preset-message" role="status">${esc(message)}</p></form><div class="divider"></div><button type="button" id="preset-reset" class="danger">特殊スキル設定を初期化</button><p>Excel・カード本文・保存デッキは変更しません。設定はこのブラウザに保存されます。</p>`;}
 function refresh(){const panel=document.querySelector('#preset-editor');if(panel)panel.innerHTML=inner();}
 function collect(){const form=document.querySelector('#preset-form');if(!form)return;draft.type=form.elements.type.value;draft.limit=form.elements.limit?.value||'turn';draft.effects=[...form.querySelectorAll('[data-effect-index]')].map(row=>Object.fromEntries(['target','stat','delta','duration'].map(k=>[k,k==='delta'?Number(row.querySelector(`[name="${k}"]`).value):row.querySelector(`[name="${k}"]`).value])));}
 document.addEventListener('change',e=>{if(!e.target.closest('#preset-form'))return;message='';if(e.target.id==='preset-card'||e.target.id==='preset-slot'){id=document.querySelector('#preset-card').value;slot=document.querySelector('#preset-slot').value;load();refresh();}else if(e.target.id==='preset-type'){const type=e.target.value;collect();draft.type=type;if(!draft.effects.length)draft.effects=[fresh()];refresh();}else collect();});
 document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled||!b.closest('#preset-editor'))return;const d=b.dataset;collect();if(d.presetQuick){draft.effects[0]={target:'self',stat:d.presetQuick,delta:Number(d.delta),duration:d.presetQuick==='troop'?'IMMEDIATE':'THIS_TURN'};refresh();}else if(d.presetRemove!==undefined){draft.effects.splice(Number(d.presetRemove),1);refresh();}else if(b.id==='preset-add'){if(draft.effects.length<3)draft.effects.push(fresh());refresh();}else if(b.id==='preset-reset'){if(confirm('すべての特殊スキル設定を標準に戻しますか？進行中の試合は変更しません。')){if(Store.write('skill-presets',{})){load();message='特殊スキル設定を初期化しました。';}else message=Store.error;refresh();}}else if(b.id==='preset-original'){const map=read();if(map[id]){delete map[id][slot];if(!Object.keys(map[id]).length)delete map[id];}if(Store.write('skill-presets',map)){load();message='この能力を標準に戻しました。';}else message=Store.error;refresh();}});
 document.addEventListener('submit',e=>{if(e.target.id!=='preset-form')return;e.preventDefault();collect();try{const config=P.validate(id,slot,draft),map=read();map[id] ||= {};map[id][slot]=config;if(!Store.write('skill-presets',map))throw Error(Store.error);message='保存しました。次に始める試合から適用します。';}catch(err){message=err.message;}refresh();});
 root.PresetEditor={screen:()=>`<section id="preset-editor" class="panel">${inner()}</section>`,read};
})(globalThis);
