/* 外部音源を使わない自作の短い合成効果音。演出は保存状態を書き換えない。 */
(function(root){
 'use strict';
 let prefs=()=>({sound:true,effects:true,volume:70}),context=null,nodes=new Set(),timers=new Set(),overlays=new Set(),busy=false,epoch=0;
 const later=(fn,ms)=>{const t=setTimeout(()=>{timers.delete(t);fn();},ms);timers.add(t);return t;};
 function unlock(){try{const Audio=root.AudioContext||root.webkitAudioContext;if(!Audio)return;if(!context)context=new Audio();if(context.state==='suspended')return context.resume().catch(()=>{});}catch{}}
 function muteIfNeeded(){if(!prefs().sound||prefs().volume===0)for(const n of nodes){try{n.stop();}catch{}}}
 function tone(freq,duration,delay=0,type='sine',end=freq,gain=.2){if(!prefs().sound||!prefs().volume||!context||context.state!=='running')return;try{const o=context.createOscillator(),a=context.createGain(),t=context.currentTime+delay;o.type=type;o.frequency.setValueAtTime(freq,t);o.frequency.exponentialRampToValueAtTime(Math.max(20,end),t+duration);a.gain.setValueAtTime(.0001,t);a.gain.exponentialRampToValueAtTime(Math.max(.0001,gain*prefs().volume/100),t+.015);a.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(a);a.connect(context.destination);o.start(t);o.stop(t+duration+.02);nodes.add(o);o.onended=()=>{nodes.delete(o);o.disconnect();a.disconnect();};}catch{}}
 function sound(kind){try{if(kind==='attack'){tone(700,.16,0,'sawtooth',100,.09);tone(100,.18,.08,'sine',40,.3);}if(kind==='trash'){tone(90,.35,0,'triangle',25,.5);tone(250,.15,0,'sawtooth',30,.15);}if(kind==='drum'){tone(110,.3,0,'sine',35,.6);tone(120,.3,.25,'sine',35,.5);}if(kind==='conch'){tone(170,.75,0,'sawtooth',230,.09);tone(340,.7,.03,'sine',460,.12);}if(kind==='victory'){[262,330,392,523].forEach((f,i)=>tone(f,.35,i*.12,'triangle',f,.2));}}catch{}}
 function release(){busy=false;document.body.classList.remove('fx-busy');for(const b of document.querySelectorAll('[data-fx-disabled]')){b.disabled=false;delete b.dataset.fxDisabled;}}
 function clear(){epoch++;for(const t of timers)clearTimeout(t);timers.clear();for(const el of overlays)el.remove();overlays.clear();release();for(const n of nodes){try{n.stop();}catch{}}}
 function syncLock(){if(busy)for(const b of document.querySelectorAll('button:not(:disabled)'))if(b.id!=='sound-toggle'){b.dataset.fxDisabled='true';b.disabled=true;}}
 function hold(ms){busy=true;document.body.classList.add('fx-busy');syncLock();later(release,ms);}
 function element(cls,text){const e=document.createElement('div');e.className=cls;e.textContent=text;document.body.append(e);overlays.add(e);return e;}
 function banner(text,ms,confetti=false){const e=element('fx-banner',text);e.setAttribute('role','status');if(confetti)for(let i=0;i<24;i++){const bit=document.createElement('i');bit.className='confetti';e.append(bit);bit.animate([{transform:`translate(${i*4}vw,-20px) rotate(0deg)`,opacity:1},{transform:`translate(${i*4-8}vw,100vh) rotate(${300+i*20}deg)`,opacity:0}],{duration:1800+i%5*200,delay:i%6*70,fill:'forwards'});}later(()=>{e.remove();overlays.delete(e);},ms);}
 function start(){const current=epoch;const play=()=>{if(current!==epoch||document.hidden)return;sound('conch');later(()=>sound('drum'),750);};const resume=unlock();if(resume?.then)resume.then(play);else play();if(prefs().effects){banner('英雄列伝バトル\n神々編\n\nいざ、開戦！',1600);hold(1600);}}
 function capture(g){const found={};if(!g)return found;for(let p=0;p<2;p++)for(const c of g.players[p].field){const el=document.querySelector(`[data-field-player="${p}"][data-field-id="${c.id}"]`);if(el)found[p+':'+c.id]=el.getBoundingClientRect();}return found;}
 function pop(el,text){if(!el)return;const box=el.getBoundingClientRect(),badge=element('fx-number',text);badge.style.left=(box.left+box.width/2)+'px';badge.style.top=(box.top+10)+'px';badge.animate([{transform:'translateY(0)',opacity:1},{transform:'translateY(-45px)',opacity:0}],{duration:650,fill:'forwards'});el.animate([{transform:'translateX(0)',backgroundColor:'#fff'},{transform:'translateX(-5px)',backgroundColor:'#ffcaca'},{transform:'translateX(5px)'},{transform:'translateX(0)'}],{duration:300});later(()=>{badge.remove();overlays.delete(badge);},650);}
 function transition(before,after,action,rects){if(action.type==='attack')sound('attack');let killed=false,damaged=false;
  for(let p=0;p<2;p++){const a=before.players[p],b=after.players[p];for(const c of a.field){const now=b.field.find(x=>x.id===c.id),death=!now&&b.trash.length>a.trash.length&&action.type!=='trash';if(death){killed=true;const raw=Game.card(c.id),loss=raw.cost>=5?2:raw.cost>=1?1:0;if(prefs().effects){const r=rects[p+':'+c.id];if(r){const el=element('fx-defeat',raw.name+' 撃破！\nコスト '+raw.cost+' ／ ライフ −'+loss);el.style.left=r.left+'px';el.style.top=r.top+'px';el.style.width=r.width+'px';const dest=document.querySelector(`[data-action="zone"][data-player="${p}"][data-zone="trash"]`)?.getBoundingClientRect();el.animate([{transform:'translateX(-5px)',opacity:1,backgroundColor:'#ffe6df'},{transform:'translateX(5px)',offset:.15},{transform:`translate(${dest?dest.left-r.left:0}px,${dest?dest.top-r.top:-70}px) scale(.2)`,opacity:0}],{duration:650,fill:'forwards'});later(()=>{el.remove();overlays.delete(el);},650);}}}else if(now&&now.troop<c.troop){damaged=true;if(prefs().effects)pop(document.querySelector(`[data-field-player="${p}"][data-field-id="${c.id}"]`),'-'+(c.troop-now.troop));}}
   if(b.life<a.life){damaged=true;if(prefs().effects)pop(document.querySelector(`[data-life-player="${p}"]`),'-'+(a.life-b.life));}
  }
  if(killed)sound('trash');if(killed||damaged||action.type==='attack')hold(prefs().effects&&killed?650:300);
  if(!before.result&&after.result){const draw=after.result.winner===null,pl=draw?null:after.players[after.result.winner];sound(draw?'drum':'victory');if(prefs().effects){banner(draw?'引き分け！\n代表カード決戦へ':'勝負あり！\n'+(pl.team||pl.name)+'\n勝利！',2600,!draw);}}
 }
 const safe=fn=>(...args)=>{try{return fn(...args);}catch{clear();}};
 root.Presentation={configure:fn=>prefs=fn,syncLock,unlock,muteIfNeeded,clear,start:safe(start),capture,transition:safe(transition),sound,get busy(){return busy;}};
})(globalThis);
