/* 原文と独立した、ユーザー設定の数値効果。本文の推測・改変はしない。 */
(function(root){
 'use strict';
 const targets={self:'自分自身',ally:'味方1体',allies:'味方全体',enemy:'敵1体',enemies:'敵全体',ownPlayer:'自分プレイヤー',enemyPlayer:'相手プレイヤー'};
 const stats={attack:'攻撃力',defense:'防御力',troop:'現在兵力',maxTroop:'最大兵力',life:'ライフ',energy:'エネルギー'};
 const durations={IMMEDIATE:'即時',THIS_TURN:'このターンのみ',UNTIL_NEXT_TURN:'次の自分のターン開始時まで',nextEnemyEnd:'次の相手ターン終了時まで',PERMANENT:'永続'};
 const limits={turn:'1ターンに1回',game:'1試合に1回',none:'回数制限なし'};
 function validate(id,slot,input){const raw=root.CARD_DATA.find(c=>c.id===id);if(!raw||!['skill','trait'].includes(slot))throw Error('カード・能力を選択してください');if(!['AUTO','PRESET','MANUAL'].includes(input.type))throw Error('処理タイプを選択してください');const base=root.CARD_AUTOMATION[id]?.[slot];if(input.type==='AUTO'&&(!base||base.automationType==='MANUAL'||base.sourceText!==raw[slot+'Text']))throw Error('この能力には確定した自動処理がありません。PRESETまたはMANUALを選択してください。');const result={type:input.type,limit:input.limit||'turn',effects:[],sourceText:raw[slot+'Text'],sourceName:raw[slot+'Name']};if(!limits[result.limit])throw Error('発動回数を選択してください');if(input.type==='PRESET'){if(!Array.isArray(input.effects)||input.effects.length<1||input.effects.length>3)throw Error('効果は1～3件です');result.effects=input.effects.map(e=>{if(!targets[e.target]||!stats[e.stat]||!durations[e.duration])throw Error('対象・能力・効果時間を確認してください');if(!Number.isInteger(e.delta)||e.delta===0||Math.abs(e.delta)>999)throw Error('変更値は0以外の−999～999の整数です');if(['life','energy'].includes(e.stat)!==['ownPlayer','enemyPlayer'].includes(e.target))throw Error('ライフ・エネルギーはプレイヤー、攻撃・防御・兵力はカードを対象にしてください');return {target:e.target,stat:e.stat,delta:e.delta,duration:e.duration};});}return result;}
 function metadata(g,id,slot,base){const input=g?.rules?.skillPresets?.[id]?.[slot];if(!input||input.type==='AUTO')return base;let preset;try{preset=validate(id,slot,input);if(input.sourceText!==preset.sourceText||input.sourceName!==preset.sourceName)throw Error('原文が変更されました');}catch{return {...base,trigger:'configuredManual',automationType:'MANUAL',reason:'プリセットが不正、または原文が変更されています。手動で確認してください。',limit:'turn'};}return {...base,trigger:preset.type==='PRESET'?'preset':'configuredManual',automationType:preset.type,limit:preset.limit,effects:preset.effects,condition:'always',reason:'設定で手動処理を選択しています。'};}
 root.SkillPresets={targets,stats,durations,limits,validate,metadata};
})(globalThis);
