const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{
 const root=path.resolve(__dirname,'..'),base='/hero-battle-github-pages/';
 const server=http.createServer((req,res)=>{const file=path.resolve(root,new URL(req.url,'http://localhost').pathname.slice(base.length)||'index.html');if(!file.startsWith(root+path.sep)||!fs.existsSync(file)){res.writeHead(404);return res.end();}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.mp3':'audio/mpeg'}[path.extname(file)]||'text/plain'));res.end(fs.readFileSync(file));});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const origin='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE}),page=await browser.newPage({viewport:{width:820,height:1180}}),errors=[],external=[],checks=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('request',r=>{if(/^https?:/.test(r.url())&&new URL(r.url()).origin!==origin)external.push(r.url());});
 const act=a=>page.locator(`[data-action="${a}"]`),state=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('hero-battle-v1:match-v2')).game);
 async function fixture(id='UR06',rules={}){await page.evaluate(({id,rules})=>{const cards=CARD_DATA.filter(c=>c.rarity==='R').slice(0,10).map(c=>c.id),deck={cards,name:'試験'};const prefs={...Game.defaults,startEnergy:10,sound:false,effects:true,...rules};let g=Game.dispatch(Game.create([deck,deck],prefs,600),{type:'ready'});g.players[0].hand=[id];g.players[1].field=[Game.unit('R20'),Game.unit('R21')];g.timer.initialDuration=600000;g.timer.lastChecked=600000;Game.recompute(g);localStorage.setItem('hero-battle-v1:settings',JSON.stringify(prefs));sessionStorage.setItem('fixture',JSON.stringify({version:2,game:g,history:[],transactionOpen:false}));},{id,rules});await page.reload();await act('resume').click();await act('ready').click();}
 try{
 await page.addInitScript(()=>{const f=sessionStorage.getItem('fixture');if(f){localStorage.setItem('hero-battle-v1:match-v2',f);sessionStorage.removeItem('fixture');}});await page.goto(origin+base);await page.locator('[data-nav="settings"]').click();assert.equal(await page.locator('[name="skillMode"]').inputValue(),'full');assert.equal(await page.locator('[name="abilityConfirmations"]').isChecked(),false);await page.locator('[name="skillMode"]').selectOption('manual');await page.locator('[name="notificationSeconds"]').selectOption('0');await page.locator('#settings-form button[type="submit"]').click();await page.reload();await page.locator('[data-nav="settings"]').click();assert.equal(await page.locator('[name="skillMode"]').inputValue(),'manual');await act('fastSettings').click();assert.equal(await page.locator('[name="skillMode"]').inputValue(),'full');assert.equal(await page.locator('[name="notificationSeconds"]').inputValue(),'1.5');checks.push('完全自動の初期設定・保存復元・大会設定');
 await fixture();await page.locator('[data-action="handCard"][data-id="UR06"]').click();await act('summon').click();assert.equal((await state()).pending.length,0);assert.ok((await state()).log.some(l=>l.text.includes('自動代替')));await page.waitForFunction(()=>document.querySelector('#ability-toast').classList.contains('visible'));assert.equal(await page.locator('.decision').count(),0);assert.equal(await act('endTurn').isDisabled(),false);assert.equal(await page.evaluate(()=>Presentation.busy),false);const first=await page.evaluate(()=>Game.remaining(JSON.parse(localStorage.getItem('hero-battle-v1:match-v2')).game));await page.waitForTimeout(600);const second=await page.evaluate(()=>Game.remaining(JSON.parse(localStorage.getItem('hero-battle-v1:match-v2')).game));assert.ok(first-second>=450);checks.push('難解能力の自動代替・非停止通知・通知中も操作と時計が動作');
 for(const width of [390,820,1440]){await page.setViewportSize({width,height:1000});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);}
 if(process.env.SCREENSHOT_DIR){fs.mkdirSync(process.env.SCREENSHOT_DIR,{recursive:true});await page.setViewportSize({width:820,height:1180});await page.evaluate(()=>Notifications.push([{type:'ability',text:'真田幸村の必殺技が発動しました！'}]));await page.screenshot({path:path.join(process.env.SCREENSHOT_DIR,'automation-battle.png')});}checks.push('390・820・1440pxで横あふれなし');
 await fixture('R01');await page.locator('[data-action="handCard"][data-id="R01"]').click();await act('summon').click();assert.equal((await state()).pending.length,0);assert.equal(await page.locator('.decision').count(),0);checks.push('対象選択効果を自動確定');
 await fixture('UR06',{abilityNotifications:false});await page.locator('[data-action="handCard"][data-id="UR06"]').click();await act('summon').click();assert.ok((await state()).log.some(l=>l.text.includes('自動代替')));assert.equal(await page.locator('#ability-toast').getAttribute('class'),'');checks.push('通知OFFでも効果は適用');
 await fixture('R03',{autoSkills:false});await page.locator('[data-action="handCard"][data-id="R03"]').click();await act('summon').click();assert.equal((await state()).players[0].energy,7);assert.equal((await state()).pending.length,0);checks.push('自動発動OFFを尊重');
 await fixture('UR06',{sound:true});await page.evaluate(()=>{window.drums=0;const create=AudioContext.prototype.createOscillator;AudioContext.prototype.createOscillator=function(){window.drums++;return create.call(this);};});
 await act('timePanel').click();await page.locator('#time-seconds').fill('299');await act('timeApply').click();await page.waitForFunction(()=>document.querySelector('#ability-toast').textContent.includes('5分'));assert.equal((await state()).timer.warningFlags.five,true);assert.equal((await state()).timer.running,true);await page.waitForFunction(()=>window.drums===1);await page.waitForTimeout(2250);await act('timePanel').click();await page.locator('#time-seconds').fill('59');await act('timeApply').click();await page.waitForFunction(()=>document.querySelector('#ability-toast').textContent.includes('ラスト1分'));assert.equal((await state()).timer.warningFlags.one,true);await page.waitForFunction(()=>window.drums===3);checks.push('時間変更の境界越えで5分・1分通知、太鼓1回・2回、停止なし');
 await page.reload();await act('resume').click();await act('ready').click();await page.waitForTimeout(700);assert.equal(await page.locator('#ability-toast').textContent(),'');assert.deepEqual((await state()).timer.warningFlags,{five:true,one:true});checks.push('再読込で警告を繰り返さない');
 await page.evaluate(()=>{Notifications.clear();Notifications.push([{type:'ability',text:'順番A'},{type:'ability',text:'順番B'}]);});assert.equal(await page.locator('#ability-toast').textContent(),'順番A');await page.waitForFunction(()=>document.querySelector('#ability-toast').textContent==='順番B');checks.push('連続能力通知は順番に表示');
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);console.log(JSON.stringify({passed:checks.length,checks,errors,external},null,2));
 }finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
