const test=require('node:test'),assert=require('node:assert/strict');
require('../cards-data.js');require('../automation-data.js');require('../game.js');require('../skill-presets.js');require('../skill-automation.js');require('../engine.js');require('../session.js');
const G=Game,A=SkillAutomation,ids=CARD_DATA.filter(c=>c.rarity==='R').slice(0,10).map(c=>c.id),deck={cards:ids,name:'試験'};
const fresh=(rules={})=>G.dispatch(G.create([deck,deck],{...G.defaults,startEnergy:10,...rules},600),{type:'ready'});
function summon(id,rules={}){let g=fresh(rules);g.players[0].hand=[id];g.players[1].field=[G.unit('R20'),G.unit('R21')];G.recompute(g);return G.dispatch(g,{type:'summon',id,cost:0});}
const cfg=(slot='skill',id='R03',limit='turn')=>SkillPresets.validate(id,slot,{type:'PRESET',limit,effects:[{target:'self',stat:'attack',delta:2,duration:'THIS_TURN'}]});
test('新規デフォルト完全自動・保存済み旧試合は半自動',()=>{assert.equal(G.defaults.skillMode,'full');assert.equal(G.defaults.notificationSeconds,1.5);assert.equal(G.defaults.autoSkills,true);const g=fresh();delete g.rules.skillMode;assert.equal(A.mode(g),'semi');});
test('108枚全件：登場・攻撃フェイズ・交代の能力処理で選択待ちなし',()=>{for(const raw of CARD_DATA){let g=summon(raw.id);assert.equal(g.pending.length,0,raw.id);assert.equal(g.viewer,0,raw.id);assert.equal(g.pumping,undefined);assert.equal(g.autoSeen,undefined);if(!g.result){g=G.dispatch(g,{type:'attackPhase'});assert.equal(g.pending.length,0,raw.id);g=G.dispatch(g,{type:'endTurn'});assert.equal(g.pending.length,0,raw.id);}}});
test('難解能力は原文を保持して今ターン攻撃+2、敵への元効果は重複しない',()=>{const raw=G.clone(G.card('UR06'));let g=summon('UR06');assert.equal(G.metadata('UR06','skill',g).fallback,true);assert.deepEqual(G.card('UR06'),raw);assert.ok(g.log.some(l=>l.text.includes('自動代替')));assert.equal(g.players[1].field[0].troop,G.card('R20').troop);assert.ok(g.players[0].field[0].modifiers.some(m=>m.name===raw.skillName&&m.stats.attack===2));g=G.dispatch(g,{type:'endTurn'});assert.equal(g.players[0].field[0].modifiers.length,0);});
test('半自動では元の対象選択と手動確認を維持',()=>{let g=summon('R01',{skillMode:'semi',abilityConfirmations:true});assert.ok(g.pending.length);g=summon('UR06',{skillMode:'semi',abilityConfirmations:true});assert.equal(g.pending[0].op,'manual');});
test('完全自動で手動代替を選んでも進行を止めず手動ボタンを残す',()=>{const g=summon('UR06',{difficultFallback:'manual'});assert.equal(g.pending.length,0);assert.ok(g.deferredAbilities.some(e=>e.sourceId==='UR06'&&e.slot==='skill'));assert.ok(G.abilities(g,0,g.players[0].field[0]).find(a=>a.slot==='skill').available);});
test('特技・必殺技OFFと手動モードでは能力を勝手に実行しない',()=>{for(const rules of [{autoSkills:false},{skillMode:'manual'}]){let g=fresh(rules);g.players[0].hand=['R03'];g=G.dispatch(g,{type:'summon',id:'R03'});assert.equal(g.players[0].energy,7);assert.equal(g.pending.length,0);assert.ok(g.deferredAbilities.length);}const g=summon('R03',{autoTraits:false});assert.equal(g.players[0].field[0].passiveState?.trait,undefined);});
function choose(target,op,stats,stat,delta){const g=fresh();g.players[0].field=[G.unit('R03'),G.unit('R04'),G.unit('R05')];g.players[1].field=[G.unit('SR05'),G.unit('R20'),G.unit('R21')];const units=g.players[target==='enemy'?1:0].field;units[0].troop=4;units[0].maxTroop=10;units[0].attack=8;units[0].defense=2;units[1].troop=1;units[1].maxTroop=10;units[1].attack=12;units[1].defense=5;units[2].troop=6;units[2].maxTroop=10;units[2].attack=3;units[2].defense=11;return {g,units,ids:A.choose(g,{owner:0,target,op,stats,stat,delta},units.map(c=>({id:c.id})))};}
test('敵ダメージは兵力最小・攻撃低下は攻撃最大・防御低下は防御最大',()=>{assert.equal(choose('enemy','damage').ids[0],'R20');assert.equal(choose('enemy','buff',{attack:-2}).ids[0],'R20');assert.equal(choose('enemy','buff',{defense:-2}).ids[0],'R21');});
test('味方回復・防御は兵力率最小、攻撃は攻撃最大',()=>{assert.equal(choose('ally','heal').ids[0],'R04');assert.equal(choose('ally','buff',{defense:2}).ids[0],'R04');assert.equal(choose('ally','buff',{attack:2}).ids[0],'R04');});
test('同値は高コスト、その次は場の左順',()=>{const {g,units}=choose('enemy','damage');units.forEach(c=>c.troop=1);assert.equal(A.choose(g,{owner:0,target:'enemy',op:'damage'},units.map(c=>({id:c.id})))[0],'SR05');units[0].id=units[1].id;assert.equal(A.choose(g,{owner:0,target:'enemy',op:'damage'},units.slice(0,2).map(c=>({id:c.id})))[0],units[0].id);});
test('対象なしの効果はスキップしてログに記録',()=>{let g=fresh();g.players[0].hand=['R02'];g.players[1].field=[];g=G.dispatch(g,{type:'summon',id:'R02',cost:0});assert.equal(g.pending.length,0);assert.ok(g.log.some(l=>l.text.includes('対象が存在しない')));});
test('プリセットは登場時に自動発動・期限解除・Undoは召喚まで一括',()=>{const rules={skillPresets:{R03:{skill:cfg()}}};let g=fresh(rules);g.players[0].hand=['R03'];let s=Session.perform({game:g,history:[],transactionOpen:false},{type:'summon',id:'R03',cost:0});assert.equal(s.game.pending.length,0);assert.equal(s.game.players[0].field[0].attack,G.card('R03').attack+2);assert.equal(s.game.presetUsage[0]['R03:skill'].turn,1);s=Session.undo(s);assert.equal(s.game.players[0].field.length,0);assert.equal(s.game.presetUsage,undefined);});
test('回数無制限プリセットでも同一イベントの再帰発動を防止',()=>{let g=fresh({skillPresets:{R03:{trait:cfg('trait','R03','none')}}});g.players[0].field=[G.unit('R04'),G.unit('R05')];g.players[0].hand=['R03'];g=G.dispatch(g,{type:'summon',id:'R03',cost:0});assert.equal(g.pending.length,0);assert.equal(g.players[0].field.find(c=>c.id==='R03').modifiers.filter(m=>m.preset).length,1);});
test('能力通知OFFでも数値効果は変化しない',()=>{const a=summon('UR06'),b=summon('UR06',{abilityNotifications:false});assert.equal(a.players[0].field[0].attack,b.players[0].field[0].attack);assert.ok(b.events.some(e=>e.type==='ability'));});
function clockGame(seconds=600){const g=fresh();g.timer={initialDuration:seconds*1000,lastChecked:seconds*1000,remaining:seconds*1000,at:Date.now(),running:true,warningFlags:{}};return g;}
test('5分・1分は各1回、再読込しても重複しない',()=>{let g=clockGame();g.timer.remaining=299000;g=G.timerNotices(g);assert.equal(g.events.filter(e=>e.type==='timer').length,1);g=G.timerNotices(JSON.parse(JSON.stringify(g)));assert.equal(g.events.filter(e=>e.type==='timer').length,1);g.timer.remaining=59000;g.timer.at=Date.now();g=G.timerNotices(g);assert.equal(g.events.filter(e=>e.type==='timer').length,2);assert.equal(g.timer.running,true);});
test('5分以下の試合は5分通知なし、1分通知あり',()=>{let g=clockGame(300);g.timer.remaining=59000;g=G.timerNotices(g);assert.deepEqual(g.events.filter(e=>e.type==='timer').map(e=>e.warning),['one']);});
test('時間変更で初めて閾値を下回る時に通知、引き延ばしても再通知なし',()=>{let g=clockGame();g=G.dispatch(g,{type:'timerSet',seconds:240});g=G.timerNotices(g);assert.equal(g.timer.warningFlags.five,true);g=G.dispatch(g,{type:'timerSet',seconds:600});g=G.timerNotices(g);g=G.dispatch(g,{type:'timerSet',seconds:200});g=G.timerNotices(g);assert.equal(g.events.filter(e=>e.warning==='five').length,1);});
test('Undoで数値を戻しても表示済み時間警告は消さない',()=>{const original=clockGame();let g=G.clone(original);g.timer.remaining=290000;g=G.timerNotices(g);const result=Session.undo({game:g,history:[original],transactionOpen:false});assert.equal(result.game.timer.warningFlags.five,true);});
test('1分ちょうどで始めた場合・一時停止中に時間変更した場合も1回',()=>{let g=clockGame(60);g=G.timerNotices(g);assert.equal(g.timer.warningFlags.one,true);g=clockGame();g.timer.running=false;g=G.dispatch(g,{type:'timerSet',seconds:50});g=G.timerNotices(g);assert.equal(g.timer.warningFlags.one,true);assert.equal(g.timer.running,false);});

test('手動裁定の発動ボタンも完全自動では確認待ちを作らない',()=>{let g=summon('SR18',{difficultFallback:'manual',abilityConfirmations:true});g.players[0].field.push(G.unit('R03'));g=G.dispatch(g,{type:'attackPhase'});g=G.dispatch(g,{type:'activate',id:'SR18',slot:'skill',player:0});assert.equal(g.pending.length,0);assert.ok(g.log.some(l=>l.text.includes('手動裁定')));});
test('特技OFF・手動モードでは継続コスト割引も停止',()=>{for(const rules of [{autoTraits:false},{skillMode:'manual'}]){const g=fresh(rules);g.players[0].field=[G.unit('SR24')];g.players[0].hand=['R03'];G.recompute(g);assert.equal(G.cost(g,0,'R03'),G.card('R03').cost);}const g=fresh();g.players[0].field=[G.unit('SR24')];g.players[0].hand=['R03'];G.recompute(g);assert.equal(G.cost(g,0,'R03'),G.card('R03').cost-1);});

test('108枚全件：実際の攻撃と防御の連鎖も選択待ちなし',()=>{for(const raw of CARD_DATA){for(const defender of [false,true]){let g=summon(defender?'UR01':raw.id,{summonAttack:true});if(defender)g.players[1].field=[G.unit(raw.id)];G.recompute(g);if(!g.result){g=G.dispatch(g,{type:'attackPhase'});if(G.attackable(g,g.players[0].field[0])&&g.players[1].field.length)g=G.dispatch(g,{type:'attack',id:g.players[0].field[0].id,target:g.players[1].field[0].id});assert.equal(g.pending.length,0,raw.id+':'+defender);}}}});

test('撃破直前PRESETはトラッシュ移動前に自動適用し、再帰しない',()=>{const preset=SkillPresets.validate('SR04','skill',{type:'PRESET',limit:'game',effects:[{target:'self',stat:'troop',delta:3,duration:'IMMEDIATE'}]});let g=fresh({skillPresets:{SR04:{skill:preset}}});g.players[0].field=[G.unit('SR04')];g=G.dispatch(g,{type:'adjust',key:'troop',player:0,id:'SR04',delta:-99});assert.equal(g.players[0].field[0].troop,3);assert.equal(g.pending.length,0);g=G.dispatch(g,{type:'adjust',key:'troop',player:0,id:'SR04',delta:-99});assert.equal(g.players[0].field.length,0);assert.ok(g.players[0].trash.includes('SR04'));});
