const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{const root=path.resolve(__dirname,'..'),base='/hero-battle-github-pages/',server=http.createServer((req,res)=>{const file=path.resolve(root,new URL(req.url,'http://localhost').pathname.slice(base.length)||'index.html');if(!file.startsWith(root+path.sep)||!fs.existsSync(file)){res.writeHead(404);return res.end();}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.wasm':'application/wasm','.png':'image/png','.mp3':'audio/mpeg'}[path.extname(file)]||'application/octet-stream'));res.end(fs.readFileSync(file));});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({headless:true,args:['--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream'],executablePath:process.env.BROWSER_EXECUTABLE}),page=await browser.newPage({viewport:{width:820,height:1180},hasTouch:true}),errors=[],external=[],uploads=[],checks=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('request',r=>{if(/^https?:/.test(r.url())&&new URL(r.url()).origin!==origin)external.push(r.url());if(r.method()!=='GET')uploads.push(r.url());});
 const act=a=>page.locator(`[data-action="${a}"]`),scan=a=>page.locator(`[data-scan="${a}"]`),saved=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('hero-battle-v1:camera-pending')));
 try{await page.goto(origin+base);await act('newDeck').click();await page.locator('#deck-name').fill('写真から登録');await act('cameraSingle').click();assert.equal(await page.locator('#scan-file-camera').getAttribute('capture'),'environment');
 // Permission failure uses the real error branch and leaves the file fallback available.
 await page.evaluate(()=>{navigator.mediaDevices.getUserMedia=async()=>{throw new DOMException('test','NotAllowedError');};});await scan('camera').click();assert.ok((await page.locator('#scan-status').textContent()).includes('カメラを開けません'));assert.equal(await page.locator('#scan-file').isEnabled(),true);checks.push('カメラ拒否時も写真選択に切り替え可能');
 const single=process.env.CAMERA_SINGLE_SAMPLE,multi=process.env.CAMERA_MULTI_SAMPLE;if(!single||!multi)throw Error('CAMERA_SINGLE_SAMPLE と CAMERA_MULTI_SAMPLE に実写真を指定してください');
 await page.locator('#scan-file').setInputFiles(single);await page.waitForFunction(()=>!document.querySelector('#scan-read').disabled,{},{timeout:60000});await scan('read').click();await page.waitForFunction(()=>document.querySelector('#scan-status').textContent.includes('認識が終わりました'),{},{timeout:180000});assert.equal((await saved()).results[0].candidates[0].cardId,'UR04');checks.push('実写真1枚：ルーナを第1候補に認識');
 await scan('close').click();await page.reload();await page.locator('[data-nav="builder"]').click();await act('cameraSingle').click();await scan('restore').click();assert.equal(await page.locator('[data-candidate="0"]').inputValue(),'UR04');await scan('add').click();assert.ok((await page.locator('#selected-cards').textContent()).includes('ルーナ'));assert.equal(await page.locator('#deck-name').inputValue(),'写真から登録');checks.push('認識候補と編集中デッキを再読込後に復元・確認して追加');
 await act('cameraSingle').click();assert.ok((await page.locator('#scan-history').textContent()).includes('ルーナ'));await scan('close').click();await page.locator('#selected-cards [data-action="toggleCard"]').click();await act('cameraMulti').click();await page.locator('#scan-file').setInputFiles(multi);await page.waitForFunction(()=>!document.querySelector('#scan-read').disabled,{},{timeout:60000});assert.equal(await page.locator('#scan-rect option').count(),10);await scan('read').click();await page.waitForFunction(()=>document.querySelector('#scan-status').textContent.includes('認識が終わりました'),{},{timeout:180000});const pending=await saved(),expected=['SR13','SR12','SSR19','SSR02','UR04','R28','R24','R22','R26','SR18'];assert.deepEqual(pending.results.map(r=>r.candidates[0]?.cardId),expected);checks.push('実写真10枚：自動分割・10枚すべて第1候補が正解');
 if(process.env.SCREENSHOT_DIR){fs.mkdirSync(process.env.SCREENSHOT_DIR,{recursive:true});await page.screenshot({path:path.join(process.env.SCREENSHOT_DIR,'camera-results.png')});fs.writeFileSync(path.join(process.env.SCREENSHOT_DIR,'camera-sample-results.json'),JSON.stringify({single:'UR04',multi:pending.results},null,2));}
 await scan('add').click();assert.ok((await page.locator('#scan-status').textContent()).includes('要確認'));checks.push('低一致候補を未確認のまま追加しない');
 await page.locator('[data-find="0"]').fill('ルーナ');await page.locator('[data-search-results="0"] button').click();assert.equal(await page.locator('[data-candidate="0"]').inputValue(),'UR04');for(let i=0;i<10;i++)await page.locator(`[data-reviewed="${i}"]`).check();await scan('add').click();assert.ok((await page.locator('#scan-status').textContent()).includes('重複'));await page.locator('[data-candidate="0"]').selectOption('SR13');checks.push('候補外の108枚検索・修正・重複警告');
 await scan('add').click();assert.equal(await page.locator('#selected-cards .deck-list-item').count(),10);await act('saveDeck').click();await page.reload();await page.locator('[data-nav="decks"]').click();assert.ok((await page.locator('#app').textContent()).includes('写真から登録'));checks.push('既存ルールを通した一括追加・デッキ保存復元');
 await act('newDeck').click();await act('cameraMulti').click();await page.locator('#scan-file').setInputFiles(multi);await page.waitForFunction(()=>!document.querySelector('#scan-read').disabled,{},{timeout:60000});await scan('remove').click();assert.equal(await page.locator('#scan-rect option').count(),9);await scan('draw').click();const bounds=await page.locator('#scan-canvas').boundingBox();await page.mouse.move(bounds.x+bounds.width*.1,bounds.y+bounds.height*.2);await page.mouse.down();await page.mouse.move(bounds.x+bounds.width*.22,bounds.y+bounds.height*.55);await page.mouse.up();assert.equal(await page.locator('#scan-rect option').count(),10);await page.locator('summary').filter({hasText:'切り出し位置'}).click();await page.locator('#scan-x').fill('8');await page.locator('#scan-x').dispatchEvent('change');assert.equal(await page.locator('#scan-x').inputValue(),'8');checks.push('誤検出枠の削除・手動切り出し追加・位置調整');
 await scan('rotate').click();await page.waitForFunction(()=>!document.querySelector('#scan-read').disabled,{},{timeout:60000});for(const width of [390,820,1440]){await page.setViewportSize({width,height:1000});assert.equal(await page.evaluate(()=>document.querySelector('#camera-dialog').scrollWidth>document.querySelector('#camera-dialog').clientWidth),false);}checks.push('90度回転・スマートフォンとタブレット幅');await scan('close').click();await act('cameraSingle').click();await scan('camera').click();await page.waitForFunction(()=>document.querySelector('#scan-video').videoWidth>0);await page.evaluate(()=>window.cameraTracks=document.querySelector('#scan-video').srcObject.getTracks());await scan('capture').click();await page.waitForFunction(()=>!document.querySelector('#scan-read').disabled,{},{timeout:60000});assert.equal(await page.evaluate(()=>window.cameraTracks.every(t=>t.readyState==='ended')),true);await scan('read').click();await scan('cancel').click();assert.ok((await page.locator('#scan-status').textContent()).includes('中断'));await scan('close').click();checks.push('カメラ映像から撮影・撮影後のストリーム停止・OCR中断');assert.deepEqual(errors,[]);assert.deepEqual(external,[]);assert.deepEqual(uploads,[]);checks.push('コンソールエラー0・外部通信0・画像送信0');console.log(JSON.stringify({passed:checks.length,checks,errors,external,uploads},null,2));
 }finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
