const test = require('node:test');
const assert = require('node:assert/strict');
require('../cards-data.js');require('../game.js');
const G=globalThis.Game;
const take=(r,n)=>CARD_DATA.filter(c=>c.rarity===r).slice(0,n).map(c=>c.id);
const valid=[...take('UR',1),...take('SSR',2),...take('SR',3),...take('R',4)];
function match(overrides={}) {const d={name:'テスト',player:'A',team:'チーム',cards:valid};let g=G.create([d,{...d,player:'B'}],{...G.defaults,...overrides},600);for(let p=0;p<2;p++)for(const id of valid.slice(0,g.rules.initialHand))g=G.dispatch(g,{type:'initial',player:p,id});return G.dispatch(g,{type:'start'});}
function ready(){let g=match();g.pendingDraw=false;g.players[0].field=[G.unit('R01')];g.players[0].field[0].summonedThisTurn=false;return g;}
test('Excelデータ：108枚・UR9 SSR27 SR27 R45・ID重複なし',()=>{assert.equal(CARD_DATA.length,108);for(const [r,n] of Object.entries({UR:9,SSR:27,SR:27,R:45}))assert.equal(take(r,999).length,n);assert.equal(new Set(CARD_DATA.map(c=>c.id)).size,108);});
test('全カード主要数値と能力全文がある',()=>{for(const c of CARD_DATA){for(const k of ['cost','attack','defense','troop'])assert.equal(typeof c[k],'number');for(const k of ['name','skillName','skillText','traitName','traitText'])assert.ok(c[k]);}});
for(const [label,ids,fragment] of [
 ['UR2枚',[...take('UR',2),...take('SSR',1),...take('SR',3),...take('R',4)],'URは1枚'],
 ['SSR3枚',[...take('SSR',3),...take('SR',3),...take('R',4)],'SSRは2枚'],
 ['SR4枚',[...take('SSR',2),...take('SR',4),...take('R',4)],'SRは3枚'],
 ['R3枚',[...take('UR',1),...take('SSR',3),...take('SR',3),...take('R',3)],'Rがあと1枚']])test('デッキ違反：'+label,()=>assert.ok(G.validateDeck(ids).errors.some(e=>e.includes(fragment))));
test('UR1 SSR2 SR3 R4 → 有効',()=>assert.ok(G.validateDeck(valid).valid));
test('URなし・R10枚 → 有効',()=>assert.ok(G.validateDeck(take('R',10)).valid));
test('重複カード → 無効',()=>assert.equal(G.validateDeck([...take('R',9),'R01']).valid,false));
test('初期手札は選んだ3枚、山札7枚。開始後は追加ドロー待ち',()=>{const g=match();assert.deepEqual(g.players[0].hand,valid.slice(0,3));assert.equal(g.players[0].deck.length,7);assert.equal(g.players[0].energy,1);assert.ok(g.pendingDraw);});
test('ドローを選ぶまで召喚・攻撃フェイズ・ターン終了不可',()=>{const g=match();for(const a of [{type:'summon',id:valid[0]},{type:'attackPhase'},{type:'endTurn'}])assert.throws(()=>G.dispatch(g,a));});
test('ドローは指定カードのみ移動、1枚登録で待ち解除',()=>{let g=match();const id=g.players[0].deck[2];g=G.dispatch(g,{type:'draw',id});assert.ok(g.players[0].hand.includes(id));assert.equal(g.players[0].deck.length,6);assert.equal(g.pendingDraw,false);});
test('コスト6：エネルギー5では不可、6では消費して場へ',()=>{const c=CARD_DATA.find(c=>c.cost===6);let g=ready();g.players[0].hand=[c.id];g.players[0].energy=5;assert.throws(()=>G.dispatch(g,{type:'summon',id:c.id}),/エネルギー/);g.players[0].energy=6;g=G.dispatch(g,{type:'summon',id:c.id});assert.equal(g.players[0].energy,0);assert.equal(g.players[0].field.length,2);});
test('手動コスト補正：7から5に補正して召喚',()=>{const c=CARD_DATA.find(c=>c.cost===7);let g=ready();g.players[0].hand=[c.id];g.players[0].energy=5;g=G.dispatch(g,{type:'summon',id:c.id,cost:5});assert.equal(g.players[0].energy,0);});
test('場3枚 → 正常、4枚目は不可',()=>{let g=ready();g.players[0].field=take('R',3).map(G.unit);g.players[0].hand=['R04'];g.players[0].energy=10;assert.equal(g.players[0].field.length,3);assert.throws(()=>G.dispatch(g,{type:'summon',id:'R04'}),/最大3枚/);});
test('攻撃7 防御5 → 2、攻撃3 防御8 → 1',()=>{const g=ready();assert.equal(G.damage(g,{attack:7},{defense:5}),2);assert.equal(G.damage(g,{attack:3},{defense:8}),1);});
test('兵力2へ3ダメージ → 0、確認後トラッシュへ',()=>{let g=ready();g.players[0].field[0].attack=5;g.players[1].field=[{...G.unit('R02'),troop:2,defense:2}];g=G.dispatch(g,{type:'attackPhase'});g=G.dispatch(g,{type:'attack',id:'R01',target:'R02'});assert.equal(g.players[1].field[0].troop,0);g=G.dispatch(g,{type:'trash',player:1,id:'R02'});assert.deepEqual(g.players[1].trash,['R02']);});
test('直接攻撃A：開始時敵1枚、撃破・全滅後も直接攻撃不可、再フェイズ不可',()=>{let g=ready();g.players[0].field[0].attack=9;g.players[1].field=[{...G.unit('R02'),troop:1}];g=G.dispatch(g,{type:'attackPhase'});g=G.dispatch(g,{type:'attack',id:'R01',target:'R02'});g=G.dispatch(g,{type:'trash',player:1,id:'R02'});assert.equal(g.phase,'ended');assert.match(g.notice,/敵陣を突破/);g=G.dispatch(g,{type:'flag',id:'R01',key:'attackedThisTurn',value:false});assert.throws(()=>G.dispatch(g,{type:'attack',id:'R01',target:'life'}));assert.throws(()=>G.dispatch(g,{type:'attackPhase'}));});
test('直接攻撃B：最初から敵0枚、各カード1回攻撃',()=>{let g=ready();g.players[0].field.push({...G.unit('R02'),summonedThisTurn:false});g=G.dispatch(g,{type:'attackPhase'});const total=g.players[0].field.reduce((n,c)=>n+c.attack,0);g=G.dispatch(g,{type:'attack',id:'R01',target:'life'});assert.throws(()=>G.dispatch(g,{type:'attack',id:'R01',target:'life'}));g=G.dispatch(g,{type:'attack',id:'R02',target:'life'});assert.equal(g.players[1].life,20-total);});
test('召喚ターン攻撃不可、先生設定で許可',()=>{let g=ready();g.players[0].field[0].summonedThisTurn=true;g=G.dispatch(g,{type:'attackPhase'});assert.equal(G.attackable(g,g.players[0].field[0]),false);g.rules.summonAttack=true;assert.equal(G.attackable(g,g.players[0].field[0]),true);});
test('攻撃不能なら攻撃できない',()=>{let g=ready();g=G.dispatch(g,{type:'attackPhase'});g=G.dispatch(g,{type:'flag',id:'R01',key:'cannotAttack',value:true});assert.equal(G.attackable(g,g.players[0].field[0]),false);});
test('回復上限・最大兵力の補正・攻撃リセット',()=>{let g=ready();const base=g.players[0].field[0].maxTroop;g=G.dispatch(g,{type:'adjust',id:'R01',key:'troop',delta:3});assert.equal(g.players[0].field[0].troop,base);g=G.dispatch(g,{type:'adjust',id:'R01',key:'maxTroop',delta:3});g=G.dispatch(g,{type:'adjust',id:'R01',key:'troop',delta:3});assert.equal(g.players[0].field[0].troop,base+3);g=G.dispatch(g,{type:'adjust',id:'R01',key:'attack',delta:2});g=G.dispatch(g,{type:'adjust',id:'R01',key:'attack',reset:true});assert.equal(g.players[0].field[0].attack,G.card('R01').attack);});
test('次の自分ターンは攻撃状態リセット。一時効果は保存',()=>{let g=ready();Object.assign(g.players[0].field[0],{attackedThisTurn:true,summonedThisTurn:true,cannotAttack:true,note:'次ターンまで',attack:99});g=G.dispatch(g,{type:'endTurn'});assert.equal(g.players[1].energy,1);g=G.dispatch(g,{type:'draw',id:g.players[1].deck[0]});g=G.dispatch(g,{type:'endTurn'});const c=g.players[0].field[0];assert.equal(c.attackedThisTurn,false);assert.equal(c.summonedThisTurn,false);assert.equal(c.cannotAttack,true);assert.equal(c.attack,99);assert.equal(c.note,'次ターンまで');assert.equal(g.players[0].energy,2);});
test('山札切れは敗北しない、設定ONなら敗北',()=>{let g=ready();g.players[1].deck=[];g=G.dispatch(g,{type:'endTurn'});assert.equal(g.result,null);assert.equal(g.pendingDraw,false);assert.match(g.notice,/山札がなく/);g.rules.deckOutLose=true;g=G.dispatch(g,{type:'draw',player:1});assert.equal(g.result.winner,0);});
test('ライフ上限20、設定ONで超過回復。0で勝利',()=>{let g=ready();g=G.dispatch(g,{type:'life',player:0,delta:5});assert.equal(g.players[0].life,20);g.rules.overheal=true;g=G.dispatch(g,{type:'life',player:0,delta:5});assert.equal(g.players[0].life,25);g=G.dispatch(g,{type:'life',player:1,delta:-20});assert.equal(g.result.winner,0);assert.equal(g.timer.running,false);});
for(const [label,change,winner] of [
 ['ライフ',g=>g.players[0].life=19,1],['兵力',g=>g.players[0].field=[G.unit('R01')],0],['手札',g=>g.players[1].hand.push('R45'),1],['完全同点',g=>{},null]])test('時間切れ：'+label,()=>{let g=match();change(g);g.timer.remaining=0;g=G.dispatch(g,{type:'timeout'});assert.equal(g.result.winner,winner);});
test('対戦中の数値・状態・メモ・タイマー・ログのJSON復元',()=>{let g=ready();g=G.dispatch(g,{type:'note',id:'R01',value:'補正を継続'});g=G.dispatch(g,{type:'adjust',id:'R01',key:'defense',delta:-2});g=G.dispatch(g,{type:'flag',id:'R01',key:'traitDisabled',value:true});assert.deepEqual(JSON.parse(JSON.stringify(g)),g);});
test('原本と前のゲーム状態を変更しない（Undo可能）',()=>{const g=ready(),before=JSON.stringify(g),raw=JSON.stringify(CARD_DATA);const next=G.dispatch(g,{type:'adjust',id:'R01',key:'attack',delta:3});assert.equal(JSON.stringify(g),before);assert.equal(JSON.stringify(CARD_DATA),raw);assert.notEqual(next.players[0].field[0].attack,g.players[0].field[0].attack);});
test('設定変更は開始済みの試合へ遡及しない',()=>{const rules={...G.defaults};const g=G.create([{name:'A',cards:valid},{name:'B',cards:valid}],rules,600);rules.life=30;assert.equal(g.rules.life,20);});
test('一時停止は時間を保持、経過時間を引いて復元',()=>{let g=ready();g.timer={remaining:10000,running:true,at:1000};assert.equal(G.remaining(g,4000),7000);g.timer.running=false;assert.equal(G.remaining(g,9000),10000);});
