const test=require('node:test'),assert=require('node:assert/strict');
require('../cards-data.js');require('../automation-data.js');require('../game.js');require('../engine.js');require('../session.js');
const G=Game,ids=CARD_DATA.filter(c=>c.rarity==='R').slice(0,10).map(c=>c.id),deck={cards:ids,name:'試験'};
const create=(rules={})=>G.create([deck,deck],{...G.defaults,...rules},600);
const ready=g=>G.dispatch(g,{type:'ready'});
function field(){const g=ready(create());g.players[0].field=[G.unit('R03')];G.recompute(g);return g;}
const adjust=(g,key,delta,duration)=>G.dispatch(g,{type:'adjust',id:'R03',key,delta,duration});
test('基本値固定・永続とTHIS_TURNの合算・解除と数値ログ',()=>{let g=field(),base=G.card('R03').attack;g=adjust(g,'attack',1,'PERMANENT');g=adjust(g,'attack',2,'THIS_TURN');assert.equal(g.players[0].field[0].attack,base+3);assert.equal(g.players[0].field[0].baseAttack,base);g=G.dispatch(g,{type:'endTurn'});assert.equal(g.players[0].field[0].attack,base+1);assert.ok(g.log.some(l=>l.text.includes(`${base+3} → ${base+1}`)&&l.text.includes('効果終了')));});
test('一時防御低下・最大兵力・攻撃不能・追加攻撃権がターン終了で消える',()=>{let g=field();const raw=G.card('R03');g=adjust(g,'defense',-2,'THIS_TURN');g=adjust(g,'maxTroop',3,'THIS_TURN');g=G.dispatch(g,{type:'flag',id:'R03',key:'cannotAttack',value:true,duration:'THIS_TURN'});g=G.dispatch(g,{type:'flag',id:'R03',key:'attackedThisTurn',value:false});g=G.dispatch(g,{type:'endTurn'});const c=g.players[0].field[0];assert.equal(c.defense,raw.defense);assert.equal(c.maxTroop,raw.troop);assert.equal(c.baseMaxTroop,raw.troop);assert.equal(c.cannotAttack,false);assert.equal(c.modifiers.length,0);});
test('次の持ち主開始まで維持・再読み込み後も指定時点に解除',()=>{let g=adjust(field(),'attack',2,'UNTIL_NEXT_TURN');g=ready(G.lock(JSON.parse(JSON.stringify(g))));g=G.dispatch(g,{type:'endTurn'});assert.equal(g.players[0].field[0].modifiers.length,1);g=ready(g);g=G.dispatch(g,{type:'endTurn'});assert.equal(g.players[0].field[0].modifiers.length,0);});
test('旧Phase2保存の基本値への手動補正を永続へ移行・二重適用なし',()=>{const old=field(),c=old.players[0].field[0];delete c.statsVersion;delete c.permanent;c.baseAttack+=3;c.baseDefense-=1;c.maxTroop+=2;let g=G.lock(old);assert.equal(g.players[0].field[0].baseAttack,G.card('R03').attack);assert.equal(g.players[0].field[0].permanent.attack,3);const value=g.players[0].field[0].attack;g=G.lock(g);assert.equal(g.players[0].field[0].attack,value);assert.equal(old.players[0].field[0].baseAttack,G.card('R03').attack+3);});
test('ランダム初期手札は各3枚・重複なし・残り7枚',()=>{for(let n=0;n<30;n++)for(const p of create().players){assert.equal(p.hand.length,3);assert.equal(p.deck.length,7);assert.equal(new Set([...p.hand,...p.deck]).size,10);}});
for(const initialHandMode of ['random','manual'])for(const drawMode of ['random','manual'])test(`初期${initialHandMode}×通常${drawMode}・両者の手動選択を秘匿`,()=>{let g=create({initialHandMode,drawMode});if(initialHandMode==='manual'){assert.equal(g.timer.running,false);g=ready(g);assert.equal(g.turn,0);assert.throws(()=>G.dispatch(g,{type:'select',ids:ids.slice(0,2)}));assert.throws(()=>G.dispatch(g,{type:'select',ids:[ids[0],ids[0],ids[1]]}));assert.throws(()=>G.dispatch(g,{type:'attackPhase'}));const chosen=g.players[0].deck.slice(2,5);g=G.dispatch(g,{type:'select',ids:chosen});assert.deepEqual(g.players[0].hand,chosen);assert.equal(g.viewer,null);assert.equal(g.handoff.player,1);g=ready(g);g=G.dispatch(g,{type:'select',ids:g.players[1].deck.slice(0,3)});assert.equal(g.timer.running,false);assert.equal(g.handoff.player,0);}
 g=ready(g);if(drawMode==='manual'){assert.equal(g.players[0].hand.length,3);assert.equal(g.players[0].energy,0);assert.throws(()=>G.dispatch(g,{type:'endTurn'}));const target=g.players[0].deck.at(-1);assert.ok(G.options(g,g.pending[0]).some(o=>o.id===target));g=G.dispatch(g,{type:'select',target});assert.ok(!g.players[0].deck.includes(target));assert.equal(g.players[0].hand.at(-1),target);}assert.equal(g.players[0].hand.length,4);assert.equal(g.players[0].deck.length,6);assert.equal(g.players[0].energy,1);assert.equal(g.turn,1);
});
test('ランダム通常ドローは山札の残りだけから1枚、原本変更なし',()=>{let g=create();const remaining=[...g.players[0].deck];g=ready(g);assert.ok(remaining.includes(g.players[0].hand.at(-1)));assert.equal(g.players[0].deck.length,remaining.length-1);assert.equal(new Set([...g.players[0].deck,...g.players[0].hand]).size,10);});
test('手動ドロー待ちの保存・再開とターン全体Undo',()=>{let before=ready(create({drawMode:'manual'}));before=G.dispatch(before,{type:'select',target:before.players[0].deck[0]});let s={game:before,history:[],transactionOpen:false};s=Session.perform(s,{type:'endTurn'});s=JSON.parse(JSON.stringify(s));s.game=G.lock(s.game);s=Session.perform(s,{type:'ready'});s=Session.perform(s,{type:'select',target:s.game.players[1].deck[0]});s=Session.undo(s);assert.equal(s.game.active,0);assert.equal(s.game.players[1].hand.length,3);assert.equal(s.game.players[1].turns,0);});
test('山札なしは手動設定でも選択待ちにならない',()=>{let g=ready(create({drawMode:'manual'}));g=G.dispatch(g,{type:'select',target:g.players[0].deck[0]});g.players[1].deck=[];g=G.dispatch(g,{type:'endTurn'});assert.equal(g.pending.length,0);assert.equal(g.result,null);assert.ok(g.notice.includes('山札'));});
test('音と演出の設定は独立、初期値と音量の範囲',()=>{assert.equal(G.defaults.volume,70);assert.equal(G.defaults.initialHandMode,'random');assert.equal(G.defaults.drawMode,'random');assert.equal(G.settings({sound:false,effects:true}).effects,true);assert.equal(G.settings({sound:true,effects:false}).sound,true);assert.throws(()=>G.settings({volume:101}));assert.throws(()=>G.settings({drawMode:'other'}));});
