const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{
 const root=path.resolve(__dirname,'..'),base='/hero-battle-github-pages/';
 const server=http.createServer((req,res)=>{const name=new URL(req.url,'http://localhost').pathname.slice(base.length)||'index.html',file=path.resolve(root,name);if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css'}[path.extname(file)]||'text/plain')+'; charset=utf-8');res.end(fs.readFileSync(file));});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const origin='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE}),page=await browser.newPage({viewport:{width:820,height:1180}}),errors=[],requests=[],checks=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('request',r=>{if(/^https?:/.test(r.url())&&new URL(r.url()).origin!==origin)requests.push(r.url());});page.on('dialog',d=>d.accept());
 const act=a=>page.locator(`[data-action="${a}"]`),state=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('hero-battle-v1:match-v2')).game);
 try{
 await page.addInitScript(()=>{const f=sessionStorage.getItem('fixture');if(f){localStorage.setItem('hero-battle-v1:match-v2',f);sessionStorage.removeItem('fixture');}window.toneCount=0;if(window.AudioContext){const create=AudioContext.prototype.createBufferSource;AudioContext.prototype.createBufferSource=function(){window.toneCount++;return create.call(this);};}});
 await page.goto(origin+base);await page.evaluate(()=>{const cards=CARD_DATA.filter(c=>c.rarity==='R').slice(0,10).map(c=>c.id);localStorage.setItem('hero-battle-v1:decks',JSON.stringify([{id:'a',cards,name:'大会用',player:'A',team:'雷神'},{id:'b',cards,name:'大会用B',player:'B',team:'風神'}]));});await page.reload();
 await page.locator('[data-nav="settings"]').click();await page.locator('[name="initialHandMode"]').selectOption('manual');await page.locator('[name="drawMode"]').selectOption('manual');await page.locator('[name="volume"]').fill('40');await page.locator('[name="sound"]').uncheck();await page.locator('#settings-form button[type="submit"]').click();await page.reload();await page.locator('[data-nav="settings"]').click();assert.equal(await page.locator('[name="drawMode"]').inputValue(),'manual');assert.equal(await page.locator('[name="volume"]').inputValue(),'40');assert.equal(await page.locator('[name="sound"]').isChecked(),false);checks.push('初期・通常ドロー設定、音量、サウンド設定の保存復元');
 await page.locator('[data-nav="home"]').click();await act('setup').click();await page.locator('#match-deck-1').selectOption('b');await act('createMatch').click();await page.locator('.fx-banner').waitFor();assert.ok(await page.locator('.fx-banner').count());assert.equal(await page.evaluate(()=>toneCount),0);await act('ready').click();assert.ok((await page.locator('.decision').textContent()).includes('0 / 3'));assert.ok(await act('selectMany').isDisabled());for(let i=0;i<3;i++)await act('choiceToggle').nth(i).click();assert.ok((await page.locator('.decision').textContent()).includes('3 / 3'));await act('selectMany').click();assert.equal((await state()).viewer,null);assert.equal(await act('choiceToggle').count(),0);await act('ready').click();for(let i=0;i<3;i++)await act('choiceToggle').nth(i).click();await act('selectMany').click();await act('ready').click();assert.equal(await act('select').count(),7);await act('select').last().click();assert.equal((await state()).players[0].hand.length,4);checks.push('音OFFの開始演出、手動3枚制限、両者の秘匿、残り7枚から手動ドロー');
 await page.reload();await act('resume').click();assert.equal(await page.locator('.fx-banner').count(),0);await act('ready').click();assert.equal((await state()).players[0].hand.length,4);checks.push('再開で演出とドローを重複実行しない');
 await page.locator('#sound-toggle').click();await page.evaluate(()=>{for(const k of ['attack','trash','conch','drum','victory'])Presentation.sound(k);});assert.ok(await page.evaluate(()=>toneCount>0));const on=await page.evaluate(()=>toneCount);await page.locator('#sound-toggle').click();await page.evaluate(()=>{for(const k of ['attack','trash','conch','drum','victory'])Presentation.sound(k);});assert.equal(await page.evaluate(()=>toneCount),on);await page.locator('#sound-toggle').click();await page.evaluate(()=>{const create=AudioContext.prototype.createBufferSource;AudioContext.prototype.createBufferSource=()=>{throw Error('音声失敗の試験');};Presentation.sound('attack');AudioContext.prototype.createBufferSource=create;});await page.locator('#sound-toggle').click();checks.push('ユーザー操作によるAudioContext開始、音OFFで全効果音の生成なし');
 await page.evaluate(()=>{let g=Game.create(JSON.parse(localStorage.getItem('hero-battle-v1:decks')),{...Game.defaults,startEnergy:10},600);g=Game.dispatch(g,{type:'ready'});g.players[0].field=[Game.unit('R03')];g.players[1].field=[Game.unit('SR05')];g.players[0].field[0].summonedThisTurn=false;g.players[1].field[0].troop=1;Game.recompute(g);sessionStorage.setItem('fixture',JSON.stringify({version:2,game:g,history:[],transactionOpen:false}));});await page.reload();await act('resume').click();await act('ready').click();await page.locator('[data-action="effects"][data-player="0"]').click();await page.locator('[data-action="adjust"][data-key="attack"][data-delta="2"]').click();assert.equal((await state()).players[0].field[0].baseAttack,2);await page.locator('#close-modal').click();assert.ok(await page.locator('.temporary-badge').count());await page.locator('[data-action="detail"][data-player="0"]').click();assert.ok((await page.locator('.stat-breakdown').textContent()).includes('一時補正：+2'));await page.locator('#close-modal').click();await act('endTurn').click();await act('ready').click();assert.equal((await state()).players[0].field[0].attack,2);assert.equal(await page.locator('.temporary-badge').count(),0);checks.push('一時効果バッジと基本値内訳、ターン終了で数値と表示を解除');
 await page.evaluate(()=>{let s=JSON.parse(localStorage.getItem('hero-battle-v1:match-v2'));s.game.active=0;s.game.handoff={player:0,reason:'試験'};s.game.phase='attack';s.game.enemyAtStart=true;s.game.players[0].field[0].permanent.attack=30;Game.recompute(s.game);sessionStorage.setItem('fixture',JSON.stringify(s));});await page.reload();await act('resume').click();await act('ready').click();await act('attackSelect').first().click();await act('attackConfirm').first().click();assert.ok(await page.locator('.fx-defeat').count());assert.equal((await state()).players[1].life,18);assert.equal((await state()).players[1].field.length,0);await page.evaluate(()=>{document.querySelector('[data-action="endTurn"]').click();});assert.equal((await state()).active,0);await act('undo').click();await act('ready').click();assert.equal((await state()).players[1].life,20);assert.equal((await state()).players[1].field.length,1);assert.equal(await page.locator('.fx-defeat').count(),0);checks.push('撃破演出・コスト6でライフ−2・連打抑止・Undoで一括復元');
 await page.locator('[data-action="life"][data-player="1"][data-delta="-1"]').click();await page.evaluate(()=>Presentation.clear());await page.evaluate(()=>{const before=JSON.parse(localStorage.getItem('hero-battle-v1:match-v2')).game;const after=Game.clone(before);after.result={winner:0};Presentation.transition(before,after,{type:'timeout'},{});});await page.locator('.confetti').first().waitFor();assert.equal(await page.locator('.confetti').count(),24);assert.ok((await page.locator('.fx-banner').textContent()).includes('雷神'));await page.evaluate(()=>{Presentation.clear();const g=JSON.parse(localStorage.getItem('hero-battle-v1:match-v2')).game;Presentation.transition(g,{...g,result:{winner:null}},{type:'timeout'},{});});assert.equal(await page.locator('.confetti').count(),0);await page.locator('[data-scene="end"]').waitFor();assert.ok((await page.locator('.fx-banner').textContent()).includes('引き分け'));await page.evaluate(()=>Presentation.clear());checks.push('勝者チーム表示と紙吹雪・引き分けは紙吹雪なし');
 await page.locator('[data-nav="settings"]').click();await page.locator('[name="effects"]').uncheck();await page.locator('#settings-form button[type="submit"]').click();await page.locator('[data-nav="home"]').click();await act('setup').click();await act('createMatch').click();assert.equal(await page.locator('.fx-banner').count(),0);await act('ready').click();assert.ok(await page.locator('.decision').count());checks.push('演出OFFで即座に準備・選択可能');
 for(const width of [390,412,820,1440]){await page.setViewportSize({width,height:1000});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);}await page.locator('[data-nav="settings"]').click();await page.setViewportSize({width:390,height:844});if(process.env.SCREENSHOT_DIR){fs.mkdirSync(process.env.SCREENSHOT_DIR,{recursive:true});await page.screenshot({path:path.join(process.env.SCREENSHOT_DIR,'phase3-settings.png'),fullPage:true});}checks.push('390/412/820/1440pxで横溢れなし');assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);checks.push('HTTPサブパスでコンソールエラー・外部通信なし');
 console.log(JSON.stringify({passed:checks.length,checks},null,2));
 }finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
