const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const {chromium,webkit}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{
 const base='/hero-battle/',root=path.resolve(__dirname,'..');
 const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://localhost'),name=url.pathname.slice(base.length)||'index.html',file=path.resolve(root,name);if(!url.pathname.startsWith(base)||!file.startsWith(root+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css'}[path.extname(file)]||'text/plain')+'; charset=utf-8');res.end(fs.readFileSync(file));});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;
 let browser;
 try{
 browser=await (process.env.TEST_WEBKIT?webkit:chromium).launch({headless:true,...(!process.env.TEST_WEBKIT&&process.env.BROWSER_EXECUTABLE?{executablePath:process.env.BROWSER_EXECUTABLE}:{})});
 const ctx=await browser.newContext({viewport:{width:1440,height:1000}}),page=await ctx.newPage(),errors=[],external=[],checks=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('request',r=>{if(/^https?:/.test(r.url())&&new URL(r.url()).origin!==origin)external.push(r.url());});page.on('dialog',d=>d.accept());
 await page.addInitScript(()=>{const fixture=sessionStorage.getItem('test-fixture');if(fixture){localStorage.setItem('hero-battle-v1:match-v2',fixture);sessionStorage.removeItem('test-fixture');}crypto.getRandomValues=array=>{array.fill(4294967295);return array;};});
 const action=a=>page.locator(`[data-action="${a}"]`),shot=async name=>{if(process.env.SCREENSHOT_DIR){fs.mkdirSync(process.env.SCREENSHOT_DIR,{recursive:true});await page.screenshot({path:path.join(process.env.SCREENSHOT_DIR,name+'.png'),fullPage:true});}};
 const stored=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('hero-battle-v1:match-v2')));
 const noHidden=async ids=>{const dom=await page.locator('#app').innerHTML();const names=await page.evaluate(ids=>ids.map(id=>CARD_DATA.find(c=>c.id===id).name),ids);for(const name of names)assert.ok(!dom.includes(name),'非公開カード名がDOMに漏洩：'+name);};
 try{
  await page.goto(origin+base);await action('newDeck').click();assert.equal(await page.locator('#catalog .card').count(),108);
  for(let i=1;i<=10;i++)await page.locator(`#catalog [data-action="toggleCard"][data-id="R${String(i).padStart(2,'0')}"]`).click();await page.locator('#deck-name').fill('Aデッキ');await page.locator('#deck-player').fill('プレイヤーA');await action('saveDeck').click();
  await action('newDeck').click();for(let i=11;i<=20;i++)await page.locator(`#catalog [data-action="toggleCard"][data-id="R${String(i).padStart(2,'0')}"]`).click();await page.locator('#deck-name').fill('Bデッキ');await page.locator('#deck-player').fill('プレイヤーB');await action('saveDeck').click();checks.push('既存デッキ構築・保存・108枚表示');
  await page.locator('[data-nav="settings"]').click();await page.locator('[name="startEnergy"]').fill('10');await page.getByRole('button',{name:'設定を保存',exact:true}).click();await page.locator('[data-nav="home"]').click();await action('setup').click();await page.locator('#match-deck-1').selectOption({index:1});await action('createMatch').click();
  let s=await stored();assert.equal(s.game.players[0].hand.length,3);await noHidden([...s.game.players[0].hand,...s.game.players[1].hand]);await shot('handoff');await action('ready').click();s=await stored();assert.equal(s.game.players[0].hand.length,4);await noHidden(s.game.players[1].hand);checks.push('自動初期配布・開始ドロー・相手手札をDOMから除外');
  await page.locator('[data-action="handCard"][data-id="R03"]').click();await action('summon').click();assert.equal((await stored()).game.players[0].energy,8);assert.equal(await page.locator('.decision').count(),0);checks.push('登場時AUTOは警告・確認なし');
  await page.locator('[data-action="handCard"][data-id="R01"]').click();await action('summon').click();assert.equal(await page.locator('.decision').count(),1);await page.locator('[data-action="select"][data-target="R03"]').click();await page.locator('[data-action="select"][data-target="R01"]').click();assert.equal(await page.locator('.decision').count(),0);checks.push('SELECTの対象選択と後続効果');
  await action('endTurn').click();s=await stored();assert.equal(s.game.players[1].hand.length,4);await noHidden([...s.game.players[0].hand,...s.game.players[1].hand]);assert.equal(await page.locator('.site-header').isVisible(),false);await action('ready').click();await noHidden(s.game.players[0].hand);checks.push('交代画面は両手札を非描画、準備OK後は次の人だけ表示');
  await page.reload();await action('resume').click();await noHidden([...s.game.players[0].hand,...s.game.players[1].hand]);await action('ready').click();assert.equal((await stored()).game.players[1].hand.length,4);checks.push('再読み込みでも手札をロック、二重ドローなし');
  // 以下は状態を固定して、技能・撃破・UndoのUIを検証する。
  async function fixture(id,enemy='R20'){
   await page.evaluate(({id,enemy})=>{const d={cards:CARD_DATA.filter(c=>c.rarity==='R').slice(0,10).map(c=>c.id),name:'試験'};let g=Game.dispatch(Game.create([d,d],{...Game.defaults,startEnergy:10},600),{type:'ready'});g.players[0].hand=[id];g.players[0].deck=['R41','R44','R45'];g.players[1].hand=['SR21','SR22'];g.players[1].deck=['SR23','SR24'];g.players[1].field=[Game.unit(enemy)];Game.recompute(g);sessionStorage.setItem('test-fixture',JSON.stringify({version:2,game:g,history:[],transactionOpen:false}));},{id,enemy});await page.reload();await action('resume').click();await action('ready').click();
  }
  await fixture('SSR01');await page.locator('[data-action="handCard"]').click();await action('summon').click();await action('select').click();await noHidden(['SR21','SR22']);await action('ready').click();assert.equal(await action('select').count(),2);await action('select').first().click();await noHidden(['SR22','R41','R44','R45']);await action('ready').click();checks.push('相手の手札選択で受け渡し→選択→元の人へ受け渡し');
  await action('undo').click();await action('ready').click();s=await stored();assert.deepEqual(s.game.players[0].hand,['SSR01']);assert.equal(s.game.players[0].energy,10);assert.equal(s.game.players[1].hand.length,2);checks.push('召喚と全選択効果を1回のUndoで復元');
  await fixture('R42');await action('handCard').click();await action('summon').click();assert.ok((await page.locator('.decision').textContent()).includes('手動処理が必要'));await shot('manual');await action('manualDone').click();assert.equal(await page.locator('.decision').count(),0);checks.push('MANUALだけ警告、発動済み表示');
  await fixture('R03','SR05');await action('handCard').click();await action('summon').click();await page.locator('[data-action="effects"][data-player="1"]').click();
  const hp=(await stored()).game.players[1].field[0].troop;for(let i=1;i<hp;i++)await page.locator('[data-action="adjust"][data-key="troop"][data-delta="-1"]').click();await page.locator('[data-action="adjust"][data-key="troop"][data-delta="-1"]').click();
  s=await stored();assert.equal(s.game.players[1].field.length,0);assert.equal(s.game.players[1].life,18);await action('undo').click();await action('ready').click();s=await stored();assert.equal(s.game.players[1].field[0].troop,1);assert.equal(s.game.players[1].life,20);checks.push('兵力0を自動トラッシュ・ライフ−2、Undoで同時復元');
  await shot('battle-desktop');
  for(const [w,h] of [[1024,768],[820,1180],[390,844],[412,915]]){await page.setViewportSize({width:w,height:h});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await shot('battle-'+w);}checks.push('Windows・iPad・iPhone・Android幅の表示');
  for(const [name,size] of [['iPad',{width:820,height:1180}],['iPhone',{width:390,height:844}],['Android',{width:412,height:915}]]){const mobile=await browser.newContext({viewport:size,isMobile:true,hasTouch:true}),tab=await mobile.newPage();tab.on('pageerror',e=>errors.push(e.message));await tab.goto(origin+base);await tab.locator('[data-action="newDeck"]').tap();await tab.locator('#search').fill('ゼウス');await tab.locator('[data-action="detail"]').tap();assert.ok((await tab.locator('#modal-body').textContent()).includes('神罰の雷霆'));await mobile.close();checks.push(name+'相当タッチ操作');}
  assert.deepEqual(errors,[]);assert.deepEqual(external,[]);checks.push('HTTPサブパス・コンソールエラー0・外部通信0');console.log(JSON.stringify({passed:checks.length,checks,errors,external},null,2));
 }catch(e){console.error({errors,body:await page.locator('body').innerText()});throw e;}
 }finally{if(browser)await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
