const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
require('../cards-data.js');require('../automation-data.js');require('../game.js');require('../engine.js');require('../session.js');
const G=Game,ids=CARD_DATA.filter(c=>c.rarity==='R').slice(0,10).map(c=>c.id),deck={cards:ids,name:'試験',player:'A'};
function fresh(){return G.dispatch(G.create([deck,{...deck,player:'B'}],{...G.defaults,startEnergy:10},600,0,()=>.999),{type:'ready'});}
function fixture(id='R03'){const g=fresh();g.players[0].hand=[id];g.players[0].deck=ids.filter(x=>x!==id);g.players[1].field=[G.unit('R20')];g.players[1].hand=['R21','R22'];G.recompute(g);return g;}
function settle(g){let i=0;while((g.pending.length||g.handoff)&&!g.result){assert.ok(i++<80,'効果が収束しない');if(g.handoff)g=G.dispatch(g,{type:'ready'});else{const e=g.pending[0],opts=G.options(g,e);g=G.dispatch(g,e.op==='manual'?{type:'manualDone'}:{type:'select',ids:['reorder','reorderBottom'].includes(e.op)?opts.map(x=>x.id):[opts[0].id]});}}return g;}
test('原本108枚の全18列を変更していない',()=>{const source=fs.readFileSync(path.join(__dirname,'../legacy/cards-data.js'),'utf8');assert.equal(fs.readFileSync(path.join(__dirname,'../cards-data.js'),'utf8'),source);assert.equal(CARD_DATA.length,108);});
test('216能力を原文付きで分類、AUTO45 SELECT55 MANUAL8',()=>{const counts={AUTO:0,SELECT:0,MANUAL:0};for(const c of CARD_DATA){counts[G.automationType(c.id)]++;for(const slot of ['skill','trait']){const a=G.metadata(c.id,slot);assert.equal(a.sourceText,c[slot+'Text']);assert.ok(['AUTO','SELECT','MANUAL'].includes(a.automationType));}}assert.deepEqual(counts,{AUTO:45,SELECT:55,MANUAL:8});});
test('シャッフルは全カードを1回ずつ保持、入力を変更しない',()=>{const a=[...ids];const shuffled=G.shuffle(a,()=>0);assert.notDeepEqual(shuffled,a);assert.deepEqual([...shuffled].sort(),[...a].sort());assert.deepEqual(a,ids);});
test('両者に3枚を自動配布、準備OKで先攻1枚ドロー',()=>{let g=G.create([deck,deck],G.defaults,600,0,()=>.999);assert.deepEqual(g.players.map(p=>[p.hand.length,p.deck.length]),[[3,7],[3,7]]);assert.equal(g.viewer,null);g=G.dispatch(g,{type:'ready'});assert.deepEqual(g.players[0].hand.slice(0,3),ids.slice(0,3));assert.equal(g.players[0].hand.length,4);assert.equal(new Set(g.players[0].hand).size,4);assert.ok(ids.slice(3).includes(g.players[0].hand[3]));assert.equal(g.players[0].energy,1);});
test('交代時は自動ドローと回復、準備OKまでは閲覧者なし',()=>{let g=fresh();g=G.dispatch(g,{type:'endTurn'});assert.equal(g.active,1);assert.equal(g.viewer,null);assert.equal(g.players[1].hand.length,4);assert.equal(g.players[1].energy,10);assert.throws(()=>G.dispatch(g,{type:'summon',id:'R03'}));g=G.dispatch(g,{type:'ready'});assert.equal(g.viewer,1);});
test('山札切れ警告は1回のみ・敗北しない',()=>{let g=fresh();g.players[0].deck=[];g.rules.deckOutLose=true;for(let i=0;i<3;i++)g=G.dispatch(g,{type:'draw'});assert.equal(g.result,null);assert.equal(g.log.filter(l=>l.text.includes('山札がありません')).length,1);});
test('R03登場でエネルギー+1、R04で1枚自動ドロー',()=>{let g=fixture('R03');g=G.dispatch(g,{type:'summon',id:'R03'});assert.equal(g.players[0].energy,10-G.card('R03').cost+1);assert.equal(g.pending.length,0);g=fixture('R04');const top=g.players[0].deck[0];g=G.dispatch(g,{type:'summon',id:'R04'});assert.deepEqual(g.players[0].hand,[top]);assert.ok(g.log.some(l=>l.text.includes('自動発動')));});
test('選択型R01：対象選択後に防御+2、次の自分開始で期限解除',()=>{let g=fixture('R01');g.players[0].field=[G.unit('R03')];G.recompute(g);const base=g.players[0].field[0].defense;g=G.dispatch(g,{type:'summon',id:'R01'});assert.equal(g.pending[0].op,'buff');assert.equal(g.players[0].field[0].defense,base);g=G.dispatch(g,{type:'select',target:'R03'});assert.equal(g.players[0].field[0].defense,base+2);g=settle(g);g=settle(G.dispatch(g,{type:'endTurn'}));g=settle(G.dispatch(g,{type:'endTurn'}));assert.equal(g.players[0].field[0].defense,base);});
test('全体強化は対象選択不要、自動期限を手動補正と分離',()=>{let g=fixture('SSR02');g.players[0].field=[G.unit('R03')];G.recompute(g);const base=g.players[0].field[0].attack;g=G.dispatch(g,{type:'summon',id:'SSR02'});assert.equal(g.pending.length,0);assert.equal(g.players[0].field[0].attack,base+2);g=G.dispatch(g,{type:'adjust',id:'R03',key:'attack',delta:1});g=settle(G.dispatch(g,{type:'endTurn'}));assert.equal(g.players[0].field[0].attack,base+1);});
test('MANUAL8枚だけ警告、通常カードには警告なし',()=>{for(const id of ['UR06','SSR05','SSR06','SSR27','SR17','R42']){const g=G.dispatch(fixture(id),{type:'summon',id});assert.equal(g.pending[0].op,'manual');}const g=G.dispatch(fixture('R03'),{type:'summon',id:'R03'});assert.equal(g.pending.length,0);});
test('条件付き継続能力は条件成立時だけ発動表示・重ねがけ不可',()=>{let g=fixture();g.players[0].field=[G.unit('R11')];G.recompute(g);let c=g.players[0].field[0];assert.equal(G.abilities(g,0,c).find(a=>a.slot==='trait').available,false);g=G.dispatch(g,{type:'adjust',id:'R11',key:'troop',delta:3-c.troop});c=g.players[0].field[0];assert.equal(G.abilities(g,0,c).find(a=>a.slot==='trait').available,true);assert.equal(c.attack,G.card('R11').attack+1);assert.throws(()=>G.dispatch(g,{type:'activate',id:'R11',slot:'trait'}));});
test('登場時効果は再発動不可',()=>{let g=G.dispatch(fixture('R03'),{type:'summon',id:'R03'});assert.equal(g.players[0].field[0].entrySkillResolved,true);assert.throws(()=>G.dispatch(g,{type:'activate',id:'R03',slot:'skill'}));});
test('ターン開始特性：通常ドロー→回復→エネルギー効果',()=>{let g=fresh();g.players[1].field=[G.unit('SR23')];g=G.dispatch(g,{type:'endTurn'});assert.equal(g.pending.length,0);const texts=g.log.map(l=>l.text),a=texts.findLastIndex(t=>t.includes('自動ドロー')),b=texts.findLastIndex(t=>t.includes('へ回復')),c=texts.findLastIndex(t=>t.includes('実験の積み重ね'));assert.ok(a<b&&b<c);});
for(const id of ['R03','SR05'])test('撃破の元コスト判定・Undo一括復元：'+id,()=>{let g=fresh();g.players[0].field=[G.unit('R03')];g.players[0].field[0].summonedThisTurn=false;g.players[0].field[0].baseAttack=20;g.players[1].field=[G.unit(id)];g.players[1].field[0].troop=3;G.recompute(g);g=G.dispatch(g,{type:'attackPhase'});const before=G.clone(g);let session={game:g,history:[],transactionOpen:false};session=Session.perform(session,{type:'attack',id:'R03',target:id});assert.equal(session.game.players[1].field.length,0);assert.equal(session.game.players[1].life,20-(G.card(id).cost>=5?2:1));assert.equal(session.game.phase,'ended');assert.match(session.game.notice,/敵陣を突破/);session=Session.undo(session);assert.deepEqual(session.game.players,before.players);assert.equal(session.game.phase,'attack');});
test('召喚コストを0にしても撃破損失は元コスト',()=>{let g=fixture('SR05');g.players[1].field=[];g=settle(G.dispatch(g,{type:'summon',id:'SR05',cost:0}));g=G.dispatch(g,{type:'adjust',id:'SR05',key:'troop',delta:-99});assert.equal(g.players[0].life,18);});
test('手札破棄・兵力のある手動トラッシュに撃破損失なし',()=>{let g=fresh();g=G.dispatch(g,{type:'trash',zone:'hand',id:g.players[0].hand[0]});assert.equal(g.players[0].life,20);g.players[0].field=[G.unit('R03')];g=G.dispatch(g,{type:'trash',id:'R03'});assert.equal(g.players[0].life,20);});
test('1試合1回の兵力1生存→2回目は撃破',()=>{let g=fresh();g.players[0].field=[G.unit('SR04')];g=G.dispatch(g,{type:'adjust',id:'SR04',key:'troop',delta:-99});assert.equal(g.players[0].field[0].troop,1);assert.equal(g.players[0].life,20);g=G.dispatch(g,{type:'adjust',id:'SR04',key:'troop',delta:-1});assert.equal(g.players[0].field.length,0);assert.equal(g.players[0].life,18);});
test('相手手札破棄は相手へ交代、終了後に元の人へ交代',()=>{let g=fixture('SSR01');g=G.dispatch(g,{type:'summon',id:'SSR01'});g=G.dispatch(g,{type:'select',target:'R20'});assert.equal(g.handoff.player,1);assert.equal(g.viewer,null);g=G.dispatch(g,{type:'ready'});assert.equal(g.pending[0].chooser,1);g=G.dispatch(g,{type:'select',target:'R21'});assert.equal(g.handoff.player,0);assert.equal(g.players[1].hand.length,1);});
test('複数選択を含む召喚をUndoするとコスト・手札・全効果を復元',()=>{const before=fixture('SSR01');let s={game:before,history:[],transactionOpen:false};s=Session.perform(s,{type:'summon',id:'SSR01'});s=Session.perform(s,{type:'select',target:'R20'});s=Session.perform(s,{type:'ready'});s=Session.perform(s,{type:'select',target:'R21'});s=Session.perform(s,{type:'ready'});assert.equal(s.history.length,1);s=Session.undo(s);assert.deepEqual(s.game.players,before.players);});
test('選択途中もJSON保存・復元し、Undoグループを維持',()=>{let s=Session.perform({game:fixture('SSR01'),history:[],transactionOpen:false},{type:'summon',id:'SSR01'});s=JSON.parse(JSON.stringify(s));s.game=G.lock(s.game);s=Session.perform(s,{type:'ready'});assert.equal(s.game.pending[0].op,'damage');assert.equal(s.transactionOpen,true);s=Session.undo(s);assert.equal(s.game.players[0].field.length,0);});
test('履歴は50操作保持',()=>{let s={game:fresh(),history:[],transactionOpen:false};for(let i=0;i<60;i++)s=Session.perform(s,{type:'energy',delta:i%2?1:-1});assert.equal(s.history.length,50);});
test('ログには自動ドローしたカード名を記録しない',()=>{let g=fresh();const name=G.card(g.players[0].deck[0]).name;g=G.dispatch(g,{type:'draw'});assert.ok(!g.log.at(-1).text.includes(name));});
test('原文変更時には自動化を停止',()=>{const c=CARD_DATA.find(c=>c.id==='R03'),old=c.skillText;try{c.skillText='登場時、エネルギーを99増やす。';assert.equal(G.metadata('R03','skill').automationType,'MANUAL');}finally{c.skillText=old;}});
test('全108枚の登場・特性・ターン開始処理が収束する',()=>{for(const c of CARD_DATA){let g=fixture(c.id);g.players[0].field=[G.unit(c.id==='R03'?'R04':'R03')];g=settle(G.dispatch(g,{type:'summon',id:c.id,cost:0}));if(!g.result){g=settle(G.dispatch(g,{type:'endTurn'}));g=settle(G.dispatch(g,{type:'endTurn'}));}for(const p of g.players)for(const u of p.field)assert.ok(Number.isFinite(u.attack)&&Number.isFinite(u.defense)&&u.troop>0,c.id);}});
test('直接攻撃は初めから敵陣0の場合のみ・1ターン1回',()=>{let g=fresh();g.players[0].field=[G.unit('R03')];g.players[0].field[0].summonedThisTurn=false;G.recompute(g);g=G.dispatch(g,{type:'attackPhase'});const n=g.players[0].field[0].attack;g=G.dispatch(g,{type:'attack',id:'R03',target:'life'});assert.equal(g.players[1].life,20-n);assert.throws(()=>G.dispatch(g,{type:'attack',id:'R03',target:'life'}));});
test('場3枚制限と不足コストの拒否',()=>{let g=fixture('SR05');g.players[0].energy=5;assert.throws(()=>G.dispatch(g,{type:'summon',id:'SR05'}));g.players[0].energy=10;g.players[0].field=['R01','R02','R03'].map(G.unit);assert.throws(()=>G.dispatch(g,{type:'summon',id:'SR05'}),/最大3枚/);});
test('自動コスト軽減は1枚で消費される',()=>{let g=fixture('SR24');g.players[1].field=[];g=settle(G.dispatch(g,{type:'summon',id:'SR24',cost:0}));g.players[0].hand=['SR05','R03'];assert.equal(G.cost(g,0,'SR05'),G.card('SR05').cost-2);g=settle(G.dispatch(g,{type:'summon',id:'SR05'}));assert.equal(G.cost(g,0,'R03'),G.card('R03').cost);});
test('1ターン1回の生存回復は2回目に発動しない',()=>{let g=fresh();g.players[0].field=['R03','R04'].map(G.unit);for(const c of g.players[0].field){c.summonedThisTurn=false;c.baseAttack=1;}g.players[1].field=[G.unit('R20')];g.players[1].field[0].troop=4;G.recompute(g);g=G.dispatch(g,{type:'attackPhase'});g=G.dispatch(g,{type:'attack',id:'R03',target:'R20'});assert.equal(g.players[1].field[0].troop,4);g=G.dispatch(g,{type:'attack',id:'R04',target:'R20'});assert.equal(g.players[1].field[0].troop,3);});
test('手動の再攻撃は撃破後のみ1試合1回使用可能',()=>{let g=fixture('SSR06');g=settle(G.dispatch(g,{type:'summon',id:'SSR06',cost:0}));g.players[0].field[0].summonedThisTurn=false;g.players[0].field[0].baseAttack=99;g.players[1].field=[G.unit('R03'),G.unit('R04')];G.recompute(g);assert.equal(G.abilities(g,0,g.players[0].field[0])[0].available,false);g=G.dispatch(g,{type:'attackPhase'});g=G.dispatch(g,{type:'attack',id:'SSR06',target:'R03'});assert.equal(G.abilities(g,0,g.players[0].field[0])[0].available,true);g=G.dispatch(g,{type:'activate',id:'SSR06',slot:'skill'});g=G.dispatch(g,{type:'manualDone'});assert.equal(g.players[0].field[0].skillUsedThisGame,true);assert.throws(()=>G.dispatch(g,{type:'activate',id:'SSR06',slot:'skill'}));});
test('山札の並べ替え・選択後の順序を維持',()=>{let g=fixture('SSR26');const top=g.players[0].deck.slice(0,4);g=G.dispatch(g,{type:'summon',id:'SSR26',cost:0});g=G.dispatch(g,{type:'select',target:top[1]});const rest=top.filter(id=>id!==top[1]).reverse();g=G.dispatch(g,{type:'select',ids:rest});assert.deepEqual(g.players[0].hand,[top[1]]);assert.deepEqual(g.players[0].deck.slice(-3),rest);});
test('ライフ勝利と時間切れ判定',()=>{let g=fresh();g=G.dispatch(g,{type:'life',player:1,delta:-20});assert.equal(g.result.winner,0);g=fresh();g.players[1].hand.push('R44','R45');g.timer.remaining=0;g=G.dispatch(g,{type:'timeout'});assert.equal(g.result.winner,1);});
